#include <iostream>
#include <string>
#include "menua.h"

using namespace std;

int c_fifteen()
{
	string ct15 = "The Princess    -    Chapter XV    -    Page ";

	system ("cls");
	cout << "The Princess    -    Chapter Fifteen    -    Page 146\n" << endl;
	cout << "Princess Leanne ran down the hall. She had to try to find clothes and fast. The" << endl;
	cout << "towel that covered her had been lost in the fight and there was no way she" << endl;
	cout << "could retrieve it without being recaptured or killed. Somehow, through all the" << endl;
	cout << "confusion, she had somehow managed to grab her tiara." << endl;
	cout << "    Whoever that captain was, he had been smart in helping her escape the lab." << endl;
	cout << "She did not know where he went, but felt they would meet again." << endl;
	cout << "    The princess entered a room that seemed safe. It was someone's living area," << endl;
	cout << "and no one was there. She looked for some clean clothes and found some." << endl;
	cout << "Fortunately, they were woman's clothes. The pants were a bit big, and the shirt" << endl;
	cout << "was a belly shirt, but they would have to do. After she got dressed, she" << endl;
	cout << "carefully left the room, hoping to pass as a loran." << endl;
	cout << "    She walked out of the room trying to appear calm. Two guards ran past her" << endl;
	cout << "as she walked down the hall, not even seeming to notice her. Feeling a bit more" << endl;
	cout << "comfortable, the princess tried to find a way out, despite the occasional power" << endl;
	cout << "outages. Not long after, she met up with Captain Al'Fraize." << endl;
	cout << "    \"This way,\" said the captain as the princess followed him, \"It's good to" << endl;
	cout << "see you with clothes on.\"" << endl;
	cout << "    \"Thanks,\" said the princess, \"The guards didn't even recognize me.\"" << endl;
	cout << "    \"That's probably because they're looking for a naked woman,\" said the" << endl;
	cout << "captain." << endl;
	cout << "    \"It's a bit more than I'm used to,\" said the princess, \"but it's" << endl;
	cout << "appropriate for this culture. I don't think going naked is appropriate or" << endl;
	system ("pause");
	system ("cls");
	cout << ct15 << "147.\n" << endl;
	cout << "accepted in any civilized culture.\"" << endl;
	cout << "    \"I don't think so, either,\" said the captain, \"What's in your hand?\"" << endl;
	cout << "    \"My tiara,\" replied the princess as she put it on her head and secured it" << endl;
	cout << "\"I grabbed it off a table just before one of the men in a white coat fell on" << endl;
	cout << "it.\"" << endl;
	cout << "    \"How did you see it in the dark?\" the captain asked, curious." << endl;
	cout << "    \"It wasn't that dark,\" said the princess." << endl;
	cout << "    \"I see,\" said the captain, \"I take it you're a princess or something.\"" << endl;
	cout << "    \"Something like that,\" said the princess, \"I am princess Leanne of Cosha;" << endl;
	cout << "daughter of King Toran; ruler of the seas.\"" << endl;
	cout << "    \"I see,\" said the captain, \"Well, your heinous, I'm Captain Louis Al'Fraize" << endl;
	cout << "of the EA Valkyries.\"" << endl;
	cout << "    \"Good to formally meet you,\" said the princess, \"You don't have to address" << endl;
	cout << "me as your heinous. We're not in Cosha, and you're not coshen. You can address" << endl;
	cout << "me simply as Princess Leanne, or you can call me Princess.\"" << endl;
	cout << "    \"Okay, Princess,\" said the captain, \"How did you get in this mess, anyhow?\"" << endl;
	cout << "    \"It's a long story, and I'm not sure if I understand it,\" said the" << endl;
	cout << "princess." << endl;
	cout << "    \"I won't ask questions then,\" said the captain, \"I'm curious, what do you" << endl;
	cout << "usually wear?\"" << endl;
	cout << "    \"Well,\" said the princess, \"If you really must know, for this time of the" << endl;
	cout << "year I usually wear a skimmie and no bottom. That is, unless I'm leaving the" << endl;
	system ("pause");
	system ("cls");
	cout << ct15 << "148.\n" << endl;
	cout << "castle or dressing formal, in which case I wear a dress.\"" << endl;
	cout << "    The two turned a corridor to face a security team on the other end of that" << endl;
	cout << "corridor. The guards began to fire their weapons. The captain and princess" << endl;
	cout << "retreated around the corner while the captain fired a few shots." << endl;
	cout << "    \"Come on,\" said the captain, as they ran down that corridor. \"We'll have to" << endl;
	cout << "find another way around.\"" << endl;
	cout << "    The guards were following, so the captain decided to try the nearest door," << endl;
	cout << "hoping it was empty. As the princess opened it, two security guards rounded the" << endl;
	cout << "corner, and the captain shot them. They were not dead, just knocked" << endl;
	cout << "unconscious. The captain and the princess ducked into the empty conference room" << endl;
	cout << "and the captain locked the door by breaking the small control panel on the left" << endl;
	cout << "side of it." << endl;
	cout << "    \"Captain,\" said the princess, \"Since they want me, and probably unharmed, I" << endl;
	cout << "should cover while you make leeway.\"" << endl;
	cout << "    \"It's not that simple, Princess,\" said the captain, \"If they stun you, I" << endl;
	cout << "won't be able to carry you and get away that fast. No, we have to find an" << endl;
	cout << "alternate route.\"" << endl;
	cout << "    The captain looked around for ventilation shafts, and found a large vent" << endl;
	cout << "cover on the far wall." << endl;
	cout << "    \"You know, I bet we can fit in there,\" said the captain, thoughtfully. He" << endl;
	cout << "went to the vent cover, stood at a distance, and shot one side of the door-like" << endl;
	cout << "cover. He then opened it. The shaft lead to another room that was a bit further" << endl;
	system ("pause");
	system ("cls");
	cout << ct15 << "149.\n" << endl;
	cout << "down the corridor. It would be a tight fit, but it was manageable." << endl;
	cout << "    The captain and the princess climbed into the shaft and to the adjacent" << endl;
	cout << "room. The room was a storage room, and had a door in front of them. The captain" << endl;
	cout << "took out his palm scanner and scanned beyond the door." << endl;
	cout << "    \"I think we're in a closet,\" said the captain, \"The room ahead is a storage" << endl;
	cout << "facility, and is cornered on two corridors. We should be able to find an" << endl;
	cout << "alternate route if we're careful.\"" << endl;
	cout << "    The captain opened the door, and saw just what he expected. The large room" << endl;
	cout << "was used to store various equipment. It would be easy to get lost through the" << endl;
	cout << "maze of small machinery and other equipment, but the far door lead to a small" << endl;
	cout << "corridor, which had an access hatch at the end." << endl;
	cout << "    The two made their way to the other side at the far end of the room. The" << endl;
	cout << "captain then scanned the access panel, and was able to figure the code to" << endl;
	cout << "unlock the door. The door slid open, and the captain and princess carefully" << endl;
	cout << "entered the corridor." << endl;
	cout << "    There was a guard at the end of the corridor, and when he saw the two the" << endl;
	cout << "captain stunned him with his pistol. He and the princess went down to the end" << endl;
	cout << "of the corridor. They stopped in front of the access hatch." << endl;
	cout << "    \"Right here,\" said the captain as he shot an access panel to the door." << endl;
	cout << "    The panel shattered, exposing the circuits and wiring behind it. He reached" << endl;
	cout << "inside the small hole and started to feel around." << endl;
	cout << "    \"What are you doing?\" asked the princess." << endl;
	system ("pause");
	system ("cls");
	cout << ct15 << "150.\n" << endl;
	cout << "    \"There's got to be a manual release switch somewhere in there,\" said the" << endl;
	cout << "captain." << endl;
	cout << "    The captain looked at the door, and realized that the panel on the front of" << endl;
	cout << "the door contained the manual release. At the same time, he also figured out" << endl;
	cout << "how to hotwire the door." << endl;
	cout << "    \"Why are you working with those strings if you're looking for a switch?\"" << endl;
	cout << "asked the princess." << endl;
	cout << "    \"Strings?\" asked the captain, not sure what the princess was talking about." << endl;
	cout << "    \"Yes,\" said the princess, \"The colored ones to be exact. Red, blue, orange," << endl;
	cout << "brown, green.\"" << endl;
	cout << "    \"Oh, the wires. The manual switch is on the front of the door, just behind" << endl;
	cout << "that panel, and I don't want to set off an alarm yet, so I'm hot-wiring the" << endl;
	cout << "door just in case.\"" << endl;
	cout << "    \"Hot-wiring?\" asked the princess." << endl;
	cout << "    \"It's an old term,\" said the captain, \"It means I'm directly wiring the" << endl;
	cout << "hatch to bypass the front panel, so I don't need an access code. It's a bit" << endl;
	cout << "tricky, but I can do it.\"" << endl;
	cout << "    \"Different,\" said the princess, \"I have another question.\"" << endl;
	cout << "    \"What's that?\" asked the captain." << endl;
	cout << "    \"What does the EA stand for in E.A. Valkyries?\" asked the princess." << endl;
	cout << "    \"Earth Alliance, for now,\" said the captain, \"It means it's a ship that's" << endl;
	cout << "part of the Galactic Alliance, and it's from Earth.\"" << endl;
	system ("pause");
	system ("cls");
	cout << ct15 << "151.\n" << endl;
	cout << "    \"What's the Galactic Alliance?\" asked the princess." << endl;
	cout << "    \"It's an alliance of planets working together to maintain peace in this" << endl;
	cout << "part of the galaxy,\" said the captain." << endl;
	cout << "    \"Wow...\" said the princess in wonder, \"That sounds nice.\"" << endl;
	cout << "    \"It's not that bad, but does have its problems,\" said the captain, \"Believe" << endl;
	cout << "me, we've had our share of them.\"" << endl;
	cout << "    \"I'm sure you have,\" said the princess, \"The galaxy is a big place to" << endl;
	cout << "watch.\"" << endl;
	cout << "    \"Actually, it's a small part of the galaxy,\" said the captain, \"Most of the" << endl;
	cout << "galaxy hasn't even been explored yet.\"" << endl;
	cout << "    The hatch clicked, unlocking." << endl;
	cout << "    \"All you have to do is pull the handle and the hatch should swing open,\"" << endl;
	cout << "said the captain." << endl;
	cout << "    The princess grabbed the hatch's handle and pulled. The hatch opened" << endl;
	cout << "easily. The captain then pulled the wires that he had twisted together apart." << endl;
	cout << "    \"Stand back,\" said the captain as he positioned himself in front of the" << endl;
	cout << "open door." << endl;
	cout << "    The princess stood back to give the captain clearance. The captain fires" << endl;
	cout << "several times at the rectangular panel in the center of the hatch door. There" << endl;
	cout << "was a small explosion, ant then just smoke." << endl;
	cout << "    The captain then aimed his pistol inside the hole and fired a couple of" << endl;
	cout << "more shots. Sparks flew everywhere as circuits were destroyed and shorted," << endl;
	system ("pause");
	system ("cls");
	cout << ct15 << "152.\n" << endl;
	cout << "leaving the smell of burnt circuits and hot metal." << endl;
	cout << "    \"Okay,\" said the captain, \"Let's go.\"" << endl;
	cout << "    \"Why did you do that to the door?\" asked the princess as they climbed into" << endl;
	cout << "the tunnel, princess first." << endl;
	cout << "    \"To destroy the manual override,\" said the captain, \"the locks work only" << endl;
	cout << "when there is power. When there is no power, they're in the locked position," << endl;
	cout << "which means, if there's a power failure, you can't release the manual locks." << endl;
	cout << "The panel on the front held a manual override for the locks. I just broke it." << endl;
	cout << "Once we close the hatch, I'm going to blast the inside access panel, then" << endl;
	cout << "disable the power to the lock. When the hatch is closed, it will be very hard" << endl;
	cout << "to get it open again. They'll basically have to cut it open.\"" << endl;
	cout << "    \"I see,\" said the princess as the captain closed the hatch, automatically" << endl;
	cout << "locking it to the now approaching guards." << endl;
	cout << "    \"Hold your position!\" was the last words the captain and princess heard the" << endl;
	cout << "lead guard yell." << endl;
	cout << "    The captain carefully tuned his laser-pistol and shot the inside panel," << endl;
	cout << "causing it to shatter. He then reached in and carefully pulled as some wires. A" << endl;
	cout << "moment later, the lights in the tunnel flickered. The captain then crawled pass" << endl;
	cout << "the princess, leading the way." << endl;
	cout << "    \"By the way,\" said the princess, \"Where are you from?\"" << endl;
	cout << "    \"I'm from a planet called Earth,\" replied the captain, as they made their" << endl;
	cout << "way down the tunnel, \"It's about eight-thousand light years from here.\"" << endl;
	system ("pause");
	system ("cls");
	cout << ct15 << "153.\n" << endl;
	cout << "    \"I've heard rumors of land-dwellers from very far away were visiting the" << endl;
	cout << "Lorans,\" said the princess, \"Up until now, that's exactly what I thought they" << endl;
	cout << "were; just rumors.\"" << endl;
	cout << "    \"Well,\" said the captain, \"The rumors are true.\"" << endl;
	cout << "    They crawled down the tunnel and reached an alcove. It was globe shaped and" << endl;
	cout << "was barely large enough for both the captain and the princess to stand. On the" << endl;
	cout << "top and bottom were hatches, and there were other access tunnels connected to" << endl;
	cout << "the globe on the sides." << endl;
	cout << "    \"We're on level three,\" said the captain, \"the landing pad is on level one." << endl;
	cout << "We're going to have to climb to get there. Every level has an area like this" << endl;
	cout << "one, and these hatches lead to vertical tunnels with a ladder leading up. It's" << endl;
	cout << "not that long of a climb, so there shouldn't be any problems.\"" << endl;
	cout << "    \"Alright,\" said the princess, unsure of her legs, \"Let's do it.\"" << endl;
	cout << "    The princess was not used to this much exercise on her legs. She spent most" << endl;
	cout << "of her time in coshen form, and when she was on land, she only spent a couple" << endl;
	cout << "of hours there because of the long swim. She never had to do any climbing, and" << endl;
	cout << "the run had made her legs a bit tired." << endl;
	cout << "    \"There's one small problem,\" said the princess, \"I've never had to climb" << endl;
	cout << "before.\"" << endl;
	cout << "    The captain hesitated for a moment, then said, \"I'll teach you. It's" << endl;
	cout << "actually very simple, just watch what I do, and follow.\"" << endl;
	cout << "    The captain opened the top hatch and grabbed on to a small landing on the" << endl;
	system ("pause");
	system ("cls");
	cout << ct15 << "154.\n" << endl;
	cout << "inside of the tunnel, just before the hatch." << endl;
	cout << "    \"Okay,\" said the captain, \"This is slightly different than expected. I'll" << endl;
	cout << "give you a lift, then follow just behind you.\"" << endl;
	cout << "    The captain helped the princess into the tunnel, then lifted himself up" << endl;
	cout << "into it." << endl;
	cout << "    \"Okay, princess here how to do this,\" said the captain, \"First you grab the" << endl;
	cout << "rung like this, then plant a foot on a lower one, then you climb, alternating" << endl;
	cout << "your hands and feet like this.\"" << endl;
	cout << "    The captain climbed a bit up the ladder to demonstrate, and the princess" << endl;
	cout << "followed." << endl;
	cout << "    \"You're a fast learner,\" said the captain." << endl;
	cout << "    \"Thank you,\" said the princess, \"I think we should get going.\"" << endl;
	cout << "    \"You sure you got this?\" asked the captain." << endl;
	cout << "    \"Pretty much,\" said the princess." << endl;
	cout << "    \"Okay,\" said the captain, \"Let's go. Don't forget, hold on the rungs" << endl;
	cout << "tightly, and make sure your footing is sure. Believe me, you don't want to slip" << endl;
	cout << "and fall. Oh, and one more thing.\"" << endl;
	cout << "    \"What's that?\" asked the princess." << endl;
	cout << "    \"Make sure the hatches are closed behind you,\" said the captain." << endl;
	cout << "    \"Got it,\" said the princess, as she climbed down to close the hatch beneath" << endl;
	cout << "her." << endl;
	cout << "    The captain and the princess started up the ladder." << endl;
	system ("pause");
	system ("cls");
	cout << ct15 << "155.\n" << endl;
	cout << "    After a few minutes the princess said, \"This is the first time I've had to" << endl;
	cout << "climb up anything. Usually, I can just swim up it\"" << endl;
	cout << "    \"Not me,\" said the captain, \"I remember one time I had to do a long climb." << endl;
	cout << "I was on a transport ship called the Alamo when we were hit by an asteroid. We" << endl;
	cout << "sustained damage to the primary inertia dampeners. It was only a matter of time" << endl;
	cout << "before they failed completely, so I, being the chief engineer, had to go and" << endl;
	cout << "jury-rig a bypass to prevent that from happening. I had to climb to get to it," << endl;
	cout << "and the decks were bigger than these levels. This is a short climb compared to" << endl;
	cout << "that.\"" << endl;
	cout << "    The captain opened the hatch to the next level and climbed into the alcove." << endl;
	cout << "He stopped to let the princess catch up and close the hatch." << endl;
	cout << "    \"Want to take a short rest, or are you okay?\" asked the captain." << endl;
	cout << "    \"Well,\" said the princess, \"we only have one level to go. I'll be fine.\"" << endl;
	cout << "    \"Are you sure?\" asked the captain." << endl;
	cout << "    \"Yep,\" said the princess." << endl;
	cout << "    \"Okay,\" said the captain." << endl;
	cout << "    The captain opened the above hatch to the next tunnel and lifted himself" << endl;
	cout << "into it. He then helped the princess up. They both then started climbing with" << endl;
	cout << "the captain in the lead." << endl;
	cout << "    \"How long was your climb?\" asked the princess." << endl;
	cout << "    \"Huh?\" asked the captain." << endl;
	cout << "    \"On the Alamo,\" said the princess, \"How far did you have to climb?\"" << endl;
	system ("pause");
	system ("cls");
	cout << ct15 << "156.\n" << endl;
	cout << "    \"Oh, of course,\" said the captain, \"I had to climb nine decks, then crawl" << endl;
	cout << "about fifteen meters down an access way. I did end up completing the bypass in" << endl;
	cout << "time. After that climb, I decided to work on a pair of jet-boots.\"" << endl;
	cout << "    The princess laughed softly." << endl;
	cout << "    \"Did they work?\" asked the princess." << endl;
	cout << "    \"Don't know,\" said the captain, \"I never got to test them.\"" << endl;
	cout << "    \"How unfortunate,\" said the princess." << endl;
	cout << "    \"I know,\" said the captain, \"they would have been really handy, too.\"" << endl;
	cout << "    \"I have two questions,\" said the princess." << endl;
	cout << "    \"What's that?\" asked the captain." << endl;
	cout << "    \"What's an asteroid, and what are inertia dampeners?\" asked the princess." << endl;
	cout << "    \"Well,\" said the captain, \"an asteroid is basically a huge rock in space." << endl;
	cout << "Inertia dampeners are devices used to absorb a ship's inertia, so the crew" << endl;
	cout << "doesn't get thrown around every time the ship accelerates, decelerates, or" << endl;
	cout << "takes turns. Without them, the ship would have to do these things slowly, and" << endl;
	cout << "it would take months just to get from one star system to another.\"" << endl;
	cout << "    A few minutes later, they were on the top level and started to crawl down" << endl;
	cout << "another access tunnel." << endl;
	cout << "    \"Where are we heading again?\" asked the princess." << endl;
	cout << "    \"Landing pad three,\" answered the captain, \"We shouldn't have much of a" << endl;
	cout << "problem if Lieutenant Warren got my signal.\"" << endl;
	cout << "    \"Your signal?\" asked the princess." << endl;
	system ("pause");
	system ("cls");
	cout << ct15 << "157.\n" << endl;
	cout << "    \"I had a feeling something would go wrong,\" said the captain, \"It was" << endl;
	cout << "something with the way the prime leader presented himself, like he was hiding" << endl;
	cout << "something precious, so I gave Lieutenant Warren a transponder just in case. I" << endl;
	cout << "also took one so I could signal her and gave her instructions on what to do if" << endl;
	cout << "she got signaled.\"" << endl;
	cout << "    \"Interesting,\" said the princess." << endl;
	cout << "    \"I signaled her the last time the lights went out,\" said the captain." << endl;
	cout << "    \"It's a good thing they haven't gone out while we are in these tunnels,\"" << endl;
	cout << "said the princess." << endl;
	cout << "    \"They could have,\" said the captain, \"We'd never know it in these access" << endl;
	cout << "tunnels. The tunnels run on an independent power source in case the compound" << endl;
	cout << "loses both primary power and emergency power. This way emergency work can still" << endl;
	cout << "be done.\"" << endl;
	cout << "    \"Seems efficient,\" said the princess." << endl;
	cout << "    \"Normally, it is,\" said the captain, \"For some reason the storms are" << endl;
	cout << "knocking out both primary and emergency power. The only way that happens is if" << endl;
	cout << "the generators aren't working, or if there is too much power being pulled from" << endl;
	cout << "them. The storms also seem to be interfering with communications. I just hope" << endl;
	cout << "we don't have too much trouble with the shuttle.\"" << endl;
	cout << "    The captain and the princess made their way down the tunnel until they" << endl;
	cout << "reached an access hatch. The hatch was similar to the one they entered. The" << endl;
	cout << "captain stopped at a safe, but effective, distance from a panel on the left" << endl;
	system ("pause");
	system ("cls");
	cout << ct15 << "158.\n" << endl;
	cout << "hand side of the door." << endl;
	cout << "    \"Okay,\" said the captain, \"here goes.\"" << endl;
	cout << "    The captain drew his laser-pistol, adjusted it, and then shot the panel. He" << endl;
	cout << "was rewarded with a shattering panel and flying sparks. There was now a shallow" << endl;
	cout << "hole with exposed circuits and wires where the panel used to be." << endl;
	cout << "    \"M-hm,\" said the captain, \"Low security, just as I thought. This looks" << endl;
	cout << " good.\"" << endl;
	cout << "    \"Why are these tunnels low security?\" asked the princess." << endl;
	cout << "    \"Probably for two reasons,\" said the captain, \"easy access in case of an" << endl;
	cout << "emergency, or for maintenance, and two, they're not expecting anyone to break" << endl;
	cout << "into them.\"" << endl;
	cout << "    The captain went to the shallow hole where the access panel used to be." << endl;
	cout << "    \"Don't worry, Princess,\" said the captain, \"we'll be out and on our way in" << endl;
	cout << "no time.\"" << endl;
	cout << "    The captain started working with the exposed wires inside the small hole." << endl;
	cout << "    \"I'm not worried,\" said the princess, \"Well, maybe a little, but not much.\"" << endl;
	cout << "    \"Good,\" said the captain, \"that'll make things much easier. Hold on... stand" << endl;
	cout << "by... There!\"" << endl;
	cout << "    There was a pop and a spark, and then the lights went out in the tunnel," << endl;
	cout << "leaving the captain and princess in total darkness." << endl;
	cout << "    \"Better reset that,\" said the captain." << endl;
	system ("pause");
	system ("cls");
	cout << ct15 << "159.\n" << endl;
	cout << "    \"What happened?\" asked the princess." << endl;
	cout << "    After a moment of silence, the lights came back on." << endl;
	cout << "    \"What did you do?\" asked the princess." << endl;
	cout << "    \"Connected what I was sure was the lock,\" said the captain, \"I got proven" << endl;
	cout << "wrong and tripped a circuit.\"" << endl;
	cout << "    \"Are you sure you can do this?\" asked the princess." << endl;
	cout << "    \"I'm sure,\" said the captain, \"It's just wired a bit differently than I" << endl;
	cout << "expected. This was modified for some reason.\"" << endl;
	cout << "    \"Can you... hotwire it?\" asked the princess." << endl;
	cout << "    \"I think so,\" said the captain, \"I'll give it a couple more tries. If I" << endl;
	cout << "can't get it, we'll have to go down another tunnel. We don't have a whole lot" << endl;
	cout << "of time, and it's best if we keep moving as much as possible. I think I got it" << endl;
	cout << "now.\"" << endl;
	cout << "    Nothing happened." << endl;
	cout << "    \"Hmm...\" the captain said in thought, \"it's dead.\"" << endl;
	cout << "    \"Do you need me to help?\" asked the princess." << endl;
	cout << "    \"Nope,\" said the captain, \"Like I said, it's been modified. It's just a" << endl;
	cout << "matter of finding the right wires.\"" << endl;
	cout << "    A couple of seconds passed before the princess asked, \"How long do you" << endl;
	cout << "think it will take them to find us?\"" << endl;
	cout << "    \"It'll take a while. Their internal sensors can't detect us in the access" << endl;
	cout << "tunnels,\" said the captain, \"so they're doing a manual search. Of course, when" << endl;
	system ("pause");
	system ("cls");
	cout << ct15 << "160.\n" << endl;
	cout << "we get back into the halls, we'll be detected easily.\"" << endl;
	cout << "    \"Can their sensor things actually distinguish the difference?\" asked the" << endl;
	cout << "princess." << endl;
	cout << "    \"You bet,\" said the captain, \"trust me we'll stick out like sore thumbs. It" << endl;
	cout << "won't be hard to track a human and a... What's your species anyway?\"" << endl;
	cout << "    \"Coshen,\" said the princess, \"I'm a coshen.\"" << endl;
	cout << "    \"And a coshen,\" said the captain." << endl;
	cout << "    \"I just thought of something,\" said the princess." << endl;
	cout << "    \"What's that?\" asked the captain." << endl;
	cout << "    \"I might be detected as a loran,\" said the princess." << endl;
	cout << "    \"Really?\" asked the captain, \"Actually, now that I think of it, I can see" << endl;
	cout << "how that can be. Still, since we're not sure, we should proceed as if you won't" << endl;
	cout << "be detected as a loran.\"" << endl;
	cout << "    \"Good idea,\" said the princesses, \"Actually, according to my limited" << endl;
	cout << "studies, lorans and humans aren't all that different. Unfortunately, my studies" << endl;
	cout << "are inconclusive. Either way, you're right. We should be careful. One thing I" << endl;
	cout << "have learned is these people seem devious and somewhat violent.\"" << endl;
	cout << "    The captain worked with the wires for a few more seconds." << endl;
	cout << "    \"There!\" he finally said, \"It's that or nothing.\"" << endl;
	cout << "    There was a click from the hatch's lock." << endl;
	cout << "    \"There we go,\" said the captain, \"I told you I could do it.\"" << endl;
	cout << "    \"Ready to get out of this contraption of a tunnel?\" asked the princess." << endl;
	system ("pause");
	system ("cls");
	cout << ct15 << "161.\n" << endl;
	cout << "    \"Are you claustrophobic?\" asked the captain." << endl;
	cout << "    \"It's a bit late to be asking me that; isn't it?\" asked the princess," << endl;
	cout << "\"Besides I'm not claustrophobic, now let's get going.\"" << endl;
	cout << "    \"Right,\" said the captain." << endl;
	cout << "    The captain drew his laser-pistol then quickly opened the hatch. He checked" << endl;
	cout << "both ways of the corridor for security personnel. He then climbed out of the" << endl;
	cout << "tunnel." << endl;
	cout << "    \"You okay?\" the captain asked the princess as he helped her out." << endl;
	cout << "    \"Yes, thank you,\" said the princess, \"I'm glad to get out of there. My legs" << endl;
	cout << "were getting crampy.\"" << endl;
	cout << "    The captain looked at the princess." << endl;
	cout << "    \"I told you I'm not used to any of this,\" said the princess." << endl;
	cout << "    \"Right,\" said the captain as he reached back into the tunnel." << endl;
	cout << "    The captain climbed about half way into the tunnel to where the panel used" << endl;
	cout << "to be, felt for the wires and yanked on a handful of them. There were sparks" << endl;
	cout << "and a brief smell of acrid smoke. The lights in the tunnel went out and the" << endl;
	cout << "hatch's locks engaged. The captain got out of the tunnel and closed the door," << endl;
	cout << "locking it." << endl;
	cout << "    \"What did you just do?\" asked the princess." << endl;
	cout << "    \"I pulled some of the wires out,\" said the captain, \"Now they won't be able" << endl;
	cout << "to open the hatch from the inside.\"" << endl;
	cout << "    \"In case we were being followed,\" said the princess." << endl;
	system ("pause");
	system ("cls");
	cout << ct15 << "162.\n" << endl;
	cout << "    \"Exactly,\" said the captain, \"Come on, we're almost there.\"" << endl;
	cout << "    The captain and the princes carefully started up the corridor. The captain" << endl;
	cout << "led the way with his pistol drawn, while the princess kept a lookout behind" << endl;
	cout << "them. The two went up the corridor, took a couple of turns down some other" << endl;
	cout << "corridors, then stopped at a large split door. The captain reached into his" << endl;
	cout << "right pocket and pulled out a keycard." << endl;
	cout << "    \"Let's hope this guy had the proper clearance,\" said the captain." << endl;
	cout << "    The captain stuck the keycard into the security slot. There was a series of" << endl;
	cout << "electronic beeps, and the doors opened." << endl;
	cout << "    \"Where did you get that?\" asked the princess." << endl;
	cout << "    \"Off a guard I stunned,\" answered the captain, as he pulled the card out of" << endl;
	cout << "the security slot, \"Well, there's our ride.\"" << endl;
	cout << "    The captain and the princess ran over to the shuttle through the cold wind" << endl;
	cout << "and rain. The small shuttle had already been prepared for flight by Lieutenant" << endl;
	cout << "Warren, and the side hatch was opened awaiting the captain and the princess." << endl;
	cout << "The two boarded the shuttle and the captain pressed the hatch buttons to close it." << endl;
	cout << "    \"Good job, Lieutenant,\" said the captain." << endl;
	cout << "    The captain took the pilot's seat as the princess sat in one of the four" << endl;
	cout << "passenger's seats." << endl;
	cout << "    \"Thank you, sir,\" said the lieutenant, \"I hope you didn't have too much" << endl;
	cout << "trouble.\"" << endl;
	system ("pause");
	system ("cls");
	cout << ct15 << "163.\n" << endl;
	cout << "    \"Not too much,\" said the captain." << endl;
	cout << "    The captain introduced the princess to Lieutenant Warren." << endl;
	cout << "    \"It's a pleasure to meet you, Lieutenant,\" said the princess." << endl;
	cout << "    \"Same here,\" said the Lieutenant." << endl;
	cout << "    \"Okay,\" said the captain, \"Let's get this show on the road.\"" << endl;
	cout << "    \"Aye, sir,\" said the lieutenant, \"Thrusters at one tenth.\"" << endl;
	cout << "    The shuttle rumbled slightly as it lifted off." << endl;
	cout << "    \"Where to, sir?\" asked the lieutenant." << endl;
	cout << "    \"Princess,\" said the captain, \"Would you care to show the way?\"" << endl;
	cout << "    \"Well,\" said the princess, \"Cosha is underwater, so you'll have to drop me" << endl;
	cout << "off at the shore. The west shoreline of this continent just north of the" << endl;
	cout << "seasonal divider should do just fine.\"" << endl;
	cout << "    \"I'm not exactly sure what you're talking about,\" said the captain, \"so" << endl;
	cout << "we'll start by heading for the west shoreline.\"" << endl;
	cout << "    \"Once you come to the shoreline,\" said the princess, \"You should head south" << endl;
	cout << "until you are at the seasonal divider.\"" << endl;
	cout << "    \"Captain,\" said Lieutenant Warren, \"If I'm right, she means the equator." << endl;
	cout << "Since the seasons are opposite on either side, it could be considered a" << endl;
	cout << "seasonal divider.\"" << endl;
	cout << "    \"Let's head there, then,\" said the captain." << endl;
	cout << "    \"Aye, sir,\" said the Lieutenant, \"setting course.\"" << endl;
	cout << "    \"We'll have you home in no time, Princess,\" said the captain." << endl;
	system ("pause");
	system ("cls");
	cout << ct15 << "164.\n" << endl;
	cout << "    \"Thank you for rescuing me, Captain,\" said the princess, \"It will not be" << endl;
	cout << "forgotten.\"" << endl;
	cout << "    \"You're welcome,\" said the captain." << endl;
	cout << "    \"At least when I get back the weather will return to normal,\" said the" << endl;
	cout << "princess." << endl;
	cout << "    \"What do you mean?\" asked the captain, \"Does your kidnapping have something" << endl;
	cout << "to do with it?\"" << endl;
	cout << "    \"Indirectly, yes,\" said the princess, \"At least I think it does. You see," << endl;
	cout << "my father is close friends with the sky king, Honmar. He can control anything" << endl;
	cout << "of the sky, birds, weather, wind, and such. This weather didn't start until" << endl;
	cout << "after I was kidnapped. I fear that if I don't return soon, worse will happen.\"" << endl;
	cout << "    \"Don't worry,\" said the lieutenant, \"we'll get you back soon enough.\"" << endl;
	cout << "    \"I'm certain you will,\" said the princess." << endl;
	cout << "    \"Approaching the equator,\" said the lieutenant." << endl;
	cout << "    \"Beginning decent and reducing speed,\" said the captain." << endl;
	cout << "    \"Scanning shoreline for suitable landing area,\" said the lieutenant." << endl;
	cout << "    \"That looks good,\" said the captain, pointing at the sensor display." << endl;
	cout << "    \"Agreed,\" said the lieutenant, \"We'll be landing shortly, princess, so sit" << endl;
	cout << "tight for a bit.\"" << endl;
	cout << "    The shuttle landed on a nearby beach, and the princess stood up as the" << endl;
	cout << "shuttle's side hatch opened up." << endl;
	cout << "    \"Sorry I couldn't give you the grand tour,\" said the captain to the" << endl;
	system ("pause");
	system ("cls");
	cout << ct15 << "165.\n" << endl;
	cout << "princess, \"but time is short.\"" << endl;
	cout << "    \"It's okay,\" said the princess, \"I understand. I wish I had something to" << endl;
	cout << "give you as a token of my gratitude.\"" << endl;
	cout << "    \"Just keep safe,\" said the captain." << endl;
	cout << "    \"I hope we can meet again under better circumstances,\" said the princess." << endl;
	cout << "    \"So do I,\" said the captain." << endl;
	cout << "    \"Farewell, Captain, and Lieutenant Warren,\" said the princess, \"It's been a" << endl;
	cout << "pleasure meeting both of you.\"" << endl;
	cout << "    Before anything else could be said, the princess left the shuttle. She" << endl;
	cout << "watched as the side hatch closed. The shuttle lifted off the ground and started" << endl;
	cout << "its accent. When the princess could no longer see the shuttle, she took off the" << endl;
	cout << "wet clothes and left them on the beach. She then ran in the water, dove in" << endl;
	cout << "while changing to coshen form, and started swimming for home." << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	cout << "" << endl;
	system ("pause");
	menua();
	return 0;
}
