#include <iostream>
#include <string>
#include "menu.h"

using namespace std;

int c_five()
{
	string ct5 = "The Princess    -    Chapter V    -    Page ";

	system ("cls");
	cout << "The Princess    -    Chapter Five    -    Page 84\n" << endl;
	cout << "The swim back to Cosha-Prime had seemed like an eternity to the princess. The" << endl;
	cout << "land-dwellers had startled her. She had not expected them to be there or pursue" << endl;
	cout << "her as fervently as they did. They were not like other land-dwellers she had" << endl;
	cout << "met in the past. These land-dwellers looked like some sort of officials and she" << endl;
	cout << "feared they might have tried to take her into some sort of custody if she had" << endl;
	cout << "not run. She had only been dressed in her top. Bottom clothing was unnecessary," << endl;
	cout << "but not unworn to the Coshens, but needed and considered highly inappropriate" << endl;
	cout << "to go without among the Lorans. Fortunately, for the princess, she was fast" << endl;
	cout << "enough to avoid any unnecessary or unpleasant confrontation." << endl;
	cout << "    When the princess finally arrived at the palace, she went directly in. The" << endl;
	cout << "guards, recognizing her, let her through without saying anything and just" << endl;
	cout << "showing a gesture of respect. Soon after, another female coshen approached the" << endl;
	cout << "princess." << endl;
	cout << "    She was several years older than the princess was, though less than ten." << endl;
	cout << "She had long, straight, brown hair, a fair complexion, and dark brown eyes. She" << endl;
	cout << "was a little shorter than the princess was, and about the same weight. Her name" << endl;
	cout << "was Monia Tranko, and was the Princess's personal servant and best friend." << endl;
	cout << "    \"Your heinous,\" said Monia, \"Where have you been?\"" << endl;
	cout << "    \"Monia!\" said the princess, surprised, \"What in the sea are you doing in" << endl;
	cout << "the main halls without me? You know you're not supposed to do that. Do you want" << endl;
	cout << "to get in trouble?\"" << endl;
	cout << "    Normally, servants were not allowed to travel in the main halls of the" << endl;
	system ("pause");
	system ("cls");
	cout << ct5 << "85\n" << endl;
	cout << "castle without either the person they served, or another member of royalty." << endl;
	cout << "There were secondary halls that the servants used. They were a bit smaller and" << endl;
	cout << "less decorative." << endl;
	cout << "    \"Forgive me,\" said Monia, \"His majesty sent me to help look for you. He's" << endl;
	cout << "really upset about something, though I don't know what. I think I heard him" << endl;
	cout << "mention you, but I can't be sure.\"" << endl;
	cout << "    Monia looked at the princess for a moment ,then said, \"Are you okay? You" << endl;
	cout << "look shaken.\"" << endl;
	cout << "    \"I'm fine,\" said the princess, suddenly, \"What does my father want with" << endl;
	cout << "me?\"" << endl;
	cout << "    \"He didn't say exactly,\" said Monia, \"All I know is he's really upset, and" << endl;
	cout << "I have an awful feeling it's something to do with you. Did you do something" << endl;
	cout << "wrong?\"" << endl;
	cout << "    \"Um, no,\" said the princess, \"Look. You haven't seen me. Okay?\"" << endl;
	cout << "    \"What about his majesty?\" asked Monia, \"What should I tell him? I can't lie" << endl;
	cout << "to the king.\"" << endl;
	cout << "    \"You can, and you will,\" warned the princess, \"I'll take full" << endl;
	cout << "responsibility for whatever happens. Now, go somewhere else before someone else" << endl;
	cout << "sees me and tells my father. I'll try to explain to you later.\"" << endl;
	cout << "    \"As you wish,\" said Monia, realizing that asking questions would not be" << endl;
	cout << "wise at that time." << endl;
	cout << "    Monia knew the princess had been up to something. Usually she did not leave" << endl;
	system ("pause");
	system ("cls");
	cout << ct5 << "86\n" << endl;
	cout << "without notice or taking Monia with her. Wherever she had been, something had" << endl;
	cout << "happened to upset the princess." << endl;
	cout << "    Monia left down the hall even more curious and concerned than before, while" << endl;
	cout << "the princess quickly and cautiously headed for her chambers." << endl;
	cout << "    Princess Leanne made it to the final corridor to her chambers without being" << endl;
	cout << "detected. She was approaching her door when suddenly-" << endl;
	cout << "    \"Leanne!\" came the angry voice of the king from behind her, \"Where have you" << endl;
	cout << "been?\"" << endl;
	cout << "    Uh oh, thought the princess, he's really mad." << endl;
	cout << "    The princess turned around to the king and said in a very sweet voice, \"Hi" << endl;
	cout << "Daddy.\"" << endl;
	cout << "    \"Don't you 'hi daddy' me,\" said the king, furiously, \"I know where you've" << endl;
	cout << "been!\"" << endl;
	cout << "    \"Where have I been then?\" asked the princess, being smart." << endl;
	cout << "    \"As if you didn't know,\" said the king, \"You know very well that you've" << endl;
	cout << "been visiting land - and don't you dare try to deny it! Are you trying to get" << endl;
	cout << "caught by one of those, land-dwelling barbarians?\"" << endl;
	cout << "    \"No,\" said the princess, \"I was just curious.\"" << endl;
	cout << "    \"You know that's forbidden, as is surfacing and the use of the" << endl;
	cout << "transformation! All of which you've been doing for at least the past few" << endl;
	cout << "weeks!\"" << endl;
	cout << "    \"How would you know?\" asked the princess, becoming angry and feeling she" << endl;
	system ("pause");
	system ("cls");
	cout << ct5 << "87\n" << endl;
	cout << "had been spied on, \"All you-\"" << endl;
	cout << "    \"How would I know?\" asked the king, interrupting, \"That's being pretty" << endl;
	cout << "arrogant! I found out from King Honmar who was wondering why the princess of" << endl;
	cout << "Cosha, you, were on the beach looking like one of those barbarians!\"" << endl;
	cout << "    \"Well,\" said the princess, \"If I show up like this, it's impossible to walk" << endl;
	cout << "or avoid the Lorans. I don't see what's so wrong with it. Besides the beach was" << endl;
	cout << "abandoned, and the danger-\"" << endl;
	cout << "    \"What's wrong with it?\" said the king, interrupting again, \"Let's see" << endl;
	cout << "what's wrong with it! First, you surfaced and used the transformation; both of" << endl;
	cout << "which are forbidden. Then you go on land where the land-dwellers can easily see" << endl;
	cout << "you, and as if that wasn't bad enough, you collect their garbage! Did you think" << endl;
	cout << "you could hide it from me? Well, you were very mistaken! I am very disappointed" << endl;
	cout << "with you. You, the princess of Cosha, of all people, breaking the very laws you" << endl;
	cout << "are supposed to be upholding and enforcing!\"" << endl;
	cout << "    \"What are you talking about?\" asked the princess, \"I don't collect" << endl;
	cout << "garbage.\"" << endl;
	cout << "    \"Really?\" asked the king, \"Then why did I find their garbage in a small" << endl;
	cout << "cave accessible to your bedroom, but not easily accessible otherwise? In" << endl;
	cout << "addition, why did I find some of your possessions there? If you weren't" << endl;
	cout << "collecting that junk, then who was?\"" << endl;
	cout << "    The princess suddenly realized that the king was referring to a collection" << endl;
	cout << "of loran items she had started years ago. The collection consisted of various" << endl;
	system ("pause");
	system ("cls");
	cout << ct5 << "88\n" << endl;
	cout << "loran things, from utensils to gold coins. There were relics that were hundreds" << endl;
	cout << "of years old, while some items were fairly knew. She collected what she found" << endl;
	cout << "in the ocean that did not look too destroyed, and recently, she had started" << endl;
	cout << "collecting things from the surface." << endl;
	cout << "    \"You mean my collection?\" asked the princess, \"What did you do with it?\"" << endl;
	cout << "    The princess feared that something terrible had happened to her collection." << endl;
	cout << "She felt hurt at being spied on and frustrated that her father was not" << endl;
	cout << "listening to her." << endl;
	cout << "    \"Your collection?\" said the king, \"Is that what you call it? Well I" << endl;
	cout << "destroyed it! I never want to see anything near like it again!\"" << endl;
	cout << "    \"What?!\" exclaimed the princess, feeling crushed, \"Do you know how long I" << endl;
	cout << "spent getting some of that?! Do you know what I went through?! How could you?!\"" << endl;
	cout << "    \"Don't yell at me, young lady!\" said the king, \"We don't keep garbage here!" << endl;
	cout << "You should've known-\"" << endl;
	cout << "    \"It's not garbage!\" the princess said, really yelling this time and" << endl;
	cout << "interrupting the king, \"It's culture! You had no right to-\"" << endl;
	cout << "    \"I said don't yell at me!\" interrupted the king, \"It was and is garbage!" << endl;
	cout << "All land-dweller things are garbage. I had every right destroying it! I will" << endl;
	cout << "not have that kind of thing in the castle or any part of Cosha-Prime! It's bad" << endl;
	cout << "enough they litter the seas with it, and now you go collecting it? Not as long" << endl;
	cout << "as I'm king! Do you understand me?\"" << endl;
	cout << "    \"Yes, father,\" said the princess with a shaky voice, trying very hard to" << endl;
	system ("pause");
	system ("cls");
	cout << ct5 << "89\n" << endl;
	cout << "control herself." << endl;
	cout << "    The princess was shaky with fury and sadness for what had happened. She" << endl;
	cout << "felt embarrassed, betrayed, and violated." << endl;
	cout << "    \"Now,\" said the king, \"because of your disobedience, I'm restricting you to" << endl;
	cout << "your chambers, and stripping you of all privileges until I say otherwise. Is" << endl;
	cout << "that understood?\"" << endl;
	cout << "    \"Yes, father,\" said the princess, quietly, and angry." << endl;
	cout << "    The princess was very upset, angry, and frustrated. Her father had not" << endl;
	cout << "listened to her, destroyed that which she held dear, and invaded her privacy." << endl;
	cout << "She may not have quite been an adult yet, but she felt she still had a right to" << endl;
	cout << "privacy." << endl;
	cout << "    \"Good,\" said the king, \"Now go to your chambers.\"" << endl;
	cout << "    The princess turned stiffly and quickly swam to her chambers. She realized" << endl;
	cout << "that anything else she might say would either not be listened to, or only serve" << endl;
	cout << "to further anger her father." << endl;
	cout << "    The king had it in his mind that the land-dwellers were nothing more than" << endl;
	cout << "savage barbarians. The princess had seen so much more from them, and wished she" << endl;
	cout << "could get her father to see it to." << endl;
	cout << "    When the princess got to her chambers, she went in, then slammed the door" << endl;
	cout << "closed. Her emotions raged through her like a hurricane. Anger, sorrow," << endl;
	cout << "frustration, pity, hopelessness, desires she could not explain, not even to" << endl;
	cout << "herself. These tormented her soul and confused her mind. She wanted to strike" << endl;
	system ("pause");
	system ("cls");
	cout << ct5 << "90\n" << endl;
	cout << "out, but at whom and what she did not know. The loss she felt seemed like a" << endl;
	cout << "nightmare. She wanted to scream and cry, both at the same time." << endl;
	cout << "    The princess's chambers consisted of a bedroom, a large bathroom, a" << endl;
	cout << "dressing, or changing, room, and a guest room." << endl;
	cout << "    There were two guard outside and two inside her chambers for security. Upon" << endl;
	cout << "entering her chambers, there was the reception room. Straight ahead was the" << endl;
	cout << "changing room, also known as the powder room. Not only was it used for" << endl;
	cout << "changing, but there was also a sink for someone to quickly wash up, or freshen" << endl;
	cout << "themselves. To the right was the princess's bedroom. That was off-limits to" << endl;
	cout << "guests. Finally, to the left was a large bathroom." << endl;
	cout << "    After slamming the door to her chambers, the princess went into her" << endl;
	cout << "bedroom, and slammed that door too. She then locked it, fell face down on her" << endl;
	cout << "bed with her face in her pillow, and screamed as loud as she could. When she" << endl;
	cout << "was done, she began to cry." << endl;
	cout << "    Her father yelling at her in the open hall, combined with her own display" << endl;
	cout << "of lack of control, was both upsetting and embarrassing for her. His intrusion" << endl;
	cout << "and destruction of her hard-earned collection was an invasion of her personal" << endl;
	cout << "life. It would be very hard to forgive him for that, if at all." << endl;
	cout << "    The princess had spent years collecting land-dweller items, and many of the" << endl;
	cout << "items were irreplaceable. She was very sad at the loss, and very angry with her" << endl;
	cout << "father for destroying it. She also felt humiliated for him yelling at her in" << endl;
	cout << "the open halls." << endl;
	system ("pause");
	system ("cls");
	cout << ct5 << "91\n" << endl;
	cout << "    The princess had visited all sorts of places to find items. She would go to" << endl;
	cout << "sunken ships, deep caverns, and even to land. Some items were common, while" << endl;
	cout << "others were rare, or even unique. The only item she had left was the strange" << endl;
	cout << "silver-hinged object she found at the beach. She almost had to leave it behind" << endl;
	cout << "as the land-dwellers had shown up, but she was just able to yank it out of the" << endl;
	cout << "mud and escape." << endl;
	cout << "    It was fortunate for the princess that her father either had missed it, or" << endl;
	cout << "mistook the item for a coshen item. Had the king known the true nature of the" << endl;
	cout << "item, he probably would have destroyed it too, and the princess would have been" << endl;
	cout << "in even more trouble." << endl;
	cout << "    Princess Leanne had been taught from childhood that land-dwellers were" << endl;
	cout << "barbaric, war-like, and uncivilized. The princess became curious of these" << endl;
	cout << "strange creatures, and decided to learn more about. She questioned the" << endl;
	cout << "teachings, as there did not seem to be any scientific basis behind them, only" << endl;
	cout << "strange stories of fishermen slaughtering thousands of fish and other sea-life." << endl;
	cout << "    There were also stories of the land-dwellers dumping toxins into the ocean." << endl;
	cout << "The latter did have evidence to support it. Cosha had a clean-up program just" << endl;
	cout << "for that to keep Cosha-Prime clean of such toxins and garbage." << endl;
	cout << "    The princess started to visit land and observe the land-dwellers. She" << endl;
	cout << "learned their language, how they interacted with each other, and a bit about" << endl;
	cout << "their culture. Through these observations, she became aware that the land" << endl;
	cout << "dwellers were not as barbaric and uncivilized as she had been taught." << endl;
	system ("pause");
	system ("cls");
	cout << ct5 << "92\n" << endl;
	cout << "    One summer, the princess decided to learn even more about the land" << endl;
	cout << "dwellers. She used the transformation, somewhere private where she would not be" << endl;
	cout << "seen, and learned to use her legs for walking and swimming. She then carefully" << endl;
	cout << "approached the land-dwellers and introduced herself. Over time, she started to" << endl;
	cout << "get to know a couple of them." << endl;
	cout << "    Naturally, the teen land-dwellers were curious and wanted to know where she" << endl;
	cout << "came from. She simply told them it was far away, but would not specify. The" << endl;
	cout << "teenagers began to notice that she never left the deeper waters, and would" << endl;
	cout << "sometimes ask why. The princess always had some excuse or reason. The truth" << endl;
	cout << "remained that she was left half-naked when she used the transformation, and did" << endl;
	cout << "not want to reveal it. She had thought of making something to cover herself," << endl;
	cout << "but did not know how, and did not want to ask anyone she knew, for fear that" << endl;
	cout << "her father would find out." << endl;
	cout << "    After the warm season was over and most of the lorans stopped coming to the" << endl;
	cout << "beach, the princess stopped making contact with the land-dwellers, and always" << endl;
	cout << "kept the experiences to herself. Even Monia had no idea what she had done." << endl;
	cout << "    Through these experiences, the princess had learned a lot about the land" << endl;
	cout << "dwellers, and quickly discovered that they called themselves lorans. They did" << endl;
	cout << "have a violent streak, but despite it, were quite civilized. The Lorans" << endl;
	cout << "reminded the princess of the stories about early Coshens. They reminded her of" << endl;
	cout << "the stories before Cosha was united. So much in fact that they almost seemed to" << endl;
	cout << "be the same people." << endl;
	system ("pause");
	system ("cls");
	cout << ct5 << "93\n" << endl;
	cout << "    The Lorans seemed more peaceful and acceptant of different people than she" << endl;
	cout << "had been taught. They were also not as warlike or barbaric as believed." << endl;
	cout << "    Contact between the Lorans and the Coshens was bound to happen. It was only" << endl;
	cout << "a matter of time before the loran technology saw through the coshen's" << endl;
	cout << "disguises. After that happened, there was no way to tell how the Lorans would" << endl;
	cout << "react." << endl;
	cout << "    The princess was hoping to make a case before her father. She would argue" << endl;
	cout << "that Coshens should make peaceful first contact with the Lorans to avoid any" << endl;
	cout << "major problems. She would argue that the loran's technology is becoming capable" << endl;
	cout << "of detecting them, and it was only a matter of time, and not much at that," << endl;
	cout << "before the Lorans made contact. She would point out that the lorans may not" << endl;
	cout << "react well, and as civil as they were, her father was right in the aspect that" << endl;
	cout << "there is some less civilized behavior within them." << endl;
	cout << "    The encounters and interactions that the princess did have with the Lorans," << endl;
	cout << "taught her three important things. First, there were two intelligent races on" << endl;
	cout << "this planet, her people who lived in the seas, and the Lorans who lived on" << endl;
	cout << "land. Second, she learned the Lorans were not warlike barbarians, though less" << endl;
	cout << "civil. The Lorans reminded the princess of stories about early Cosha, before it" << endl;
	cout << "came united. It seemed the Lorans were very much like the Coshens used to be." << endl;
	cout << "Third, and what could be the most important thing, she learned the Coshens and" << endl;
	cout << "Lorans could very likely be related to each other. She deducted this from the" << endl;
	cout << "fact that when she used the transformation, she looked just like one of them." << endl;
	system ("pause");
	system ("cls");
	cout << ct5 << "94\n" << endl;
	cout << "    At the present, though, the princess felt more like a prisoner than a" << endl;
	cout << "princess. Sure, the prison cells were more confined and lacked any luxury at" << endl;
	cout << "all, but she was not used to being confined like that." << endl;
	cout << "    Thought it was forbidden to surface, never mind use the transformation, she" << endl;
	cout << "felt that because she was the princess of Cosha, heiress to the throne and all" << endl;
	cout << "power in the seas, she should have some special privileges. She felt she should" << endl;
	cout << "be able to at least surface, even if she could not use the transformation." << endl;
	cout << "    The princess viewed her father's destroying of her collection to be a" << endl;
	cout << "severe and thoughtless invasion of her privacy. She felt the things that she" << endl;
	cout << "had were harmless and were not bothering anyone. She also considered them very" << endl;
	cout << "special. They were certainly not junk, as the things were very well intact. Her" << endl;
	cout << "surfacing and going on land did not seem to be a problem, as she made sure that" << endl;
	cout << "no Lorans were around, and she could easily get away if anything happened, as" << endl;
	cout << "she had earlier." << endl;
	cout << "    The princess stopped crying after a few minutes, or so and decided to see" << endl;
	cout << "the damage her father had done to her collection. She got up, wiped her face," << endl;
	cout << "then pulled her dresser away from the wall. She then searched for a certain" << endl;
	cout << "notch in the coral wall. When she found what she was looking for, she pressed" << endl;
	cout << "it." << endl;
	cout << "    A small part of the wall, next to the floor and about center where the" << endl;
	cout << "dresser was, slid in then to the right, revealing a small, dark, passage that" << endl;
	cout << "spiraled downward. There was no room to stand, but one could swim through the" << endl;
	system ("pause");
	system ("cls");
	cout << ct5 << "95\n" << endl;
	cout << "passage. The princess ducked down, then swam down the passage." << endl;
	cout << "    The passage was just large enough to swim in, and it spiraled downward," << endl;
	cout << "below the castle's lowest floor. At the end of the spiral was a cave that led" << endl;
	cout << "away from the castle at a slight incline. The long, poorly lit cave led to a" << endl;
	cout << "somewhat round and well-lit cavern." << endl;
	cout << "    The cavern was decorated with naturally occurring crystals and had an" << endl;
	cout << "opening in the top that let light into the cavern. The crystals varied in color" << endl;
	cout << "and shape. They caught the dimmer light from above and amplified it while" << endl;
	cout << "simultaneously refracting it filling the cavern with strange and beautiful" << endl;
	cout << "light patterns." << endl;
	cout << "    The cavern was where the princess stored her collection, and as she swam" << endl;
	cout << "into it, she saw the damage her father had done. Her entire collection was" << endl;
	cout << "gone. Only a few bits remained. Some of the crystals had also been damaged. The" << endl;
	cout << "rest of her collection lay as debris on the cavern floor. Saddened even more," << endl;
	cout << "the princess picked up a larger piece, and looked at it. She then let it fall" << endl;
	cout << "to the floor." << endl;
	cout << "    The princess silently swore to herself that she would start another" << endl;
	cout << "collection, this time in Fiana. It would be, if for any reason, to spite her" << endl;
	cout << "father." << endl;
	cout << "    The princess swam back to her bedroom, then pressed the small notch on the" << endl;
	cout << "wall. The small section of the wall closed, matching the rest of the wall to" << endl;
	cout << "hide that it was there. The princess then pushed her dresser back in its place," << endl;
	system ("pause");
	system ("cls");
	cout << ct5 << "96\n" << endl;
	cout << "opened one of the four top drawers, and placed the object she had picked out of" << endl;
	cout << "the mud on the beach in it. She then closed the drawer and lay down on her bed." << endl;
	cout << "    With her collection now in ruins, and being confined to her chambers, the" << endl;
	cout << "princess wondered what she was going to do, and how long the punishment was" << endl;
	cout << "going to last. Her twentieth birthday was coming soon, and she would be an" << endl;
	cout << "adult by coshen standards. Her father couldn't keep her in her chambers for" << endl;
	cout << "too long." << endl;
	cout << "    The princess thought about her collection, and became angry as well as sad." << endl;
	cout << "She promised herself that as soon as she was able, she would start her" << endl;
	cout << "collection again, except this time she would find a place where her father" << endl;
	cout << "would never find it, and she did not care if she had to store it in Fiana.\n\n\n\n\n\n\n\n\n\n\n" << endl;
	system ("pause");
	menu();
	return 0;
}
