#include <iostream>
#include <string>
#include "menu.h"

using namespace std;

int c_four()
{
	string ct4 = "The Princess    -    Chapter IV    -    Page ";

	system ("cls");
	cout << "The Princess    -    Chapter Four    -    Page 78\n" << endl;
	cout << "Zenron searched for the strange woman while Kang and Slan looked for the" << endl;
	cout << "missing engine core. They were almost done with their search when Slan said" << endl;
	cout << "something softly." << endl;
	cout << "    \"What was that?\" asked Kang." << endl;
	cout << "    \"What was what?\" asked Slan." << endl;
	cout << "    \"What did you say?\" asked Kang." << endl;
	cout << "    \"I said, 'What was what?',\" said Slan." << endl;
	cout << "    \"I meant before that,\" said Kang." << endl;
	cout << "    \"Before what?\" asked Slan." << endl;
	cout << "    \"Before you asked me what was what,\" said Kang, becoming frustrated with" << endl;
	cout << "Slan's stupidity." << endl;
	cout << "    Slan stared blankly at Kang, truly having no idea what Kang was talking" << endl;
	cout << "about." << endl;
	cout << "    \"You know what?\" said Kang, \"Just forget it.\"" << endl;
	cout << "    \"These scanners need more range,\" said Zenron, \"I don't care if it has a" << endl;
	cout << "thousand different functions, without the range it's practically useless.\"" << endl;
	cout << "    \"True,\" said Kang, stopping as his scanner changed tones, \"but I think we" << endl;
	cout << "just found the Zenix.\"" << endl;
	cout << "    Slan and Zenron stopped to confirm what Kang had said." << endl;
	cout << "    \"How did ya know that?\" asked Slan, \"Is your scanner pickin' it up? \"'Cuz" << endl;
	cout << "mine says it's about hundred and fifteen feet from here.\"" << endl;
	cout << "    \"It's not,\" said Kang, \"It's right there, about twenty-five feet in front" << endl;
	system ("pause");
	system ("cls");
	cout << ct4 << "79\n" << endl;
	cout << "of us.\"" << endl;
	cout << "    Slan looked where Kang was looking, then said, \"I knew that.\"" << endl;
	cout << "    \"Sure you did,\" said Zenron, sarcastically." << endl;
	cout << "    The three scientists approached the washed-up engine core, and Kang turned" << endl;
	cout << "his com-link on." << endl;
	cout << "    Com-link stood for COMmunication LINK-up device. It was a small transceiver" << endl;
	cout << "device that was strapped around the wrist. This device allowed the scientists" << endl;
	cout << "to communicate to each other and their superiors." << endl;
	cout << "    All three of the scientists were equipped with one. They were part of the" << endl;
	cout << "standard equipment given to people that went on an assignment." << endl;
	cout << "    \"Central Command,\" Kang said into the com-link." << endl;
	cout << "    \"Central Command, Prime Leader Shako Lotan speaking,\" came the response." << endl;
	cout << "    \"This is Kang,\" said Kang, \"We have located the Zenix, but it's not the" << endl;
	cout << "source of the Zeta radiation. We are still picking up low levels of the" << endl;
	cout << "radiation about one hundred and ten feet in the water from our present" << endl;
	cout << "position. The signature matches the Zenix's almost exactly. If I were to" << endl;
	cout << "speculate, part of the core is here, and the rest is in the water.\"" << endl;
	cout << "    \"Understood, Kang,\" responded the prime leader, \"Maintain your position and" << endl;
	cout << "await further orders.\"" << endl;
	cout << "    \"Got it,\" said Kang, \"We'll stay where we are.\"" << endl;
	cout << "" << endl;
	cout << "" << endl;
	system ("pause");
	system ("cls");
	cout << ct4 << "80\n" << endl;
	cout << "    \"What's the condition of the Zenix?\" asked the prime leader." << endl;
	cout << "    \"It's inactive, but intact,\" said Kang, \"Basically it's dead, but still in" << endl;
	cout << "one piece. There is no radiation coming from it at all.\"" << endl;
	cout << "    \"Are the fuel cells intact?\" asked the prime leader." << endl;
	cout << "    \"Stand by,\" said Kang, \"We're going to check the core for damage now.\"" << endl;
	cout << "    Kang put his com-link on standby." << endl;
	cout << "    \"Zenron,\" said Kang, \"give me a hand here.\"" << endl;
	cout << "    Zenron turned off his scanner, folded it, and then put it in its pocket on" << endl;
	cout << "his utility belt. He and Kang then went to the cylindrical core and inspected" << endl;
	cout << "it for any damage." << endl;
	cout << "    The Zenix core was about two meters long and almost the same in" << endl;
	cout << "circumference. It was shaped like a cylinder and had three even sections. The" << endl;
	cout << "middle section looked as if it was made of yellow glass. The material was not" << endl;
	cout << "glass, but a strong, thin material that could withstand high amounts of" << endl;
	cout << "pressure and heat and block allot of radiation. The bottom section had two" << endl;
	cout << "connections that had been broken on either side, making it look like a steel" << endl;
	cout << "shaft had been driven through it. The top of the core had several connections" << endl;
	cout << "with various wires hanging out of them." << endl;
	cout << "    \"The fuel cells have been broken off,\" said Zenron, \"and it looks like" << endl;
	cout << "wires were stripped out of it.\"" << endl;
	cout << "    \"I bet the fuel cells are in the water,\" said Slan." << endl;
	cout << "    Kang switched his com-link back on." << endl;
	system ("pause");
	cout << ct4 << "81\n" << endl;
	cout << "    \"The fuel cells have been broken off,\" said Kang into the com-link, \"We" << endl;
	cout << "believe they are the source of the radiation. That would put them about one" << endl;
	cout << "hundred and ten feet in the water.\"" << endl;
	cout << "    \"Hold your position,\" said the prime leader, \"I want you to wait for" << endl;
	cout << "another team to arrive. They're going to relieve you, and they'll be the ones" << endl;
	cout << "to locate the fuel cells. After they relieve you, I want you to return here and" << endl;
	cout << "give a full report.\"" << endl;
	cout << "    \"Understood,\" said Kang." << endl;
	cout << "    \"Good,\" said the prime leader, \"and excellent job. Central Command out.\"" << endl;
	cout << "    The com-link went to static, and Kang switched it off." << endl;
	cout << "    \"What now?\" asked Slan." << endl;
	cout << "    \"We wait,\" said Kang, \"Then we go back to Central Command and give a full" << endl;
	cout << "report to the prime leader. Just like he said. Then we get paid.\"" << endl;
	cout << "    \"What about the water girl, or woman, or whatever?\" asked Slan." << endl;
	cout << "    \"She's not our responsibility,\" said Kang, \"Central Command will deal with" << endl;
	cout << "her, though I wish we could. It would be very interesting to learn more about" << endl;
	cout << "her.\"" << endl;
	cout << "    \"I know what you mean,\" said Zenron, \"This is a very interesting discovery." << endl;
	cout << "I mean, what if somehow our species has evolved into two different species? One" << endl;
	cout << "like her, and one like us? It would be fascinating if we were somehow related.\"" << endl;
	cout << "    \"Well,\" said Kang, \"according to the preliminary data, that could very" << endl;
	cout << "likely be possible. Just think; our cousins could have been here for who knows" << endl;
	system ("pause");
	system ("cls");
	cout << ct4 << "82\n" << endl;
	cout << "how many millennium, and we never knew it until now.\"" << endl;
	cout << "    Kang, Slan, and Zenron waited for the other team of specialists to arrive," << endl;
	cout << "after witch, the three left for Loran's Central Command. Upon arriving, they" << endl;
	cout << "went to the Prime leader's office." << endl;
	cout << "    \"Can I help you?\" asked the secretary." << endl;
	cout << "    The office was adjacent to a waiting room. There was a desk on the right" << endl;
	cout << "side where the secretary sat. She would greet guests, handle messages for the" << endl;
	cout << "prime leader, set up appointments, and handle paperwork." << endl;
	cout << "    \"Yes,\" said Kang, \"My name is Kang Krillon, these are my associates Slan" << endl;
	cout << "and Zenron. We're here to see the prime leader. He's expecting us.\"" << endl;
	cout << "    \"Hold on a minute,\" said the secretary." << endl;
	cout << "    The secretary pressed a button and spoke." << endl;
	cout << "    \"Prime Leader,\" she said." << endl;
	cout << "    \"Yes Jilane,\" was the answer." << endl;
	cout << "    \"Three men are here to see you,\" said Jilane, \"They say they are Kang" << endl;
	cout << "Krillon, Slan, and Zenron. They say you are expecting them.\"" << endl;
	cout << "    \"Yes,\" said the prime leader, \"Send them right in.\"" << endl;
	cout << "    \"Go right in,\" said Jilane." << endl;
	cout << "    The three scientists went into the prime leader's office." << endl;
	cout << "    \"Ahh,\" said the prime leader, \"come right in.\"" << endl;
	cout << "    \"We have a full report,\" said Kang, \"I think you will find it interesting.\"" << endl;
	cout << "    Kang handed the prime leader the report. The prime leader took the report" << endl;
	system ("pause");
	system ("cls");
	cout << ct4 << "83\n" << endl;
	cout << "and looked it over thoroughly. After a few minutes, he spoke." << endl;
	cout << "    \"This is very interesting,\" he said, handing Kang an envelope with a check" << endl;
	cout << "in it, \"Very interesting indeed. I have a new job for you. I'm going to have a" << endl;
	cout << "discrete watch put on Ashton beach. I want to try to capture this creature. I" << endl;
	cout << "promise the three of you will be paid very nicely for this.\"" << endl;
	cout << "    \"Understood,\" said Kang." << endl;
	cout << "    \"Did you collect any more information than this?\" asked the prime leader." << endl;
	cout << "    \"Everything we know is in the report,\" said Kang." << endl;
	cout << "    \"Everything except for your opinion on this water creature,\" said the prime" << endl;
	cout << "leader." << endl;
	cout << "    \"I didn't think that was important,\" said Kang." << endl;
	cout << "    \"Well, it is now,\" said the prime leader, \"I want to know what you think.\"" << endl;
	cout << "    \"We think that her people might be somehow related to us,\" said Kang, \"We" << endl;
	cout << "figure this because of her ability to somehow transform between our species and" << endl;
	cout << "hers. Who knows how long they have been in the oceans. This could be a very big" << endl;
	cout << "discovery.\"" << endl;
	cout << "    \"I see,\" said the prime leader, \"Is there anything else?\"" << endl;
	cout << "    \"I believe that's it, sir,\" said Kang." << endl;
	cout << "    \"Then I suggest you three get going,\" said the prime leader, \"and good" << endl;
	cout << "luck.\"" << endl;
	cout << "" << endl;
	cout << "" << endl;
	system ("pause");
	menu();
	return 0;
}
