#include <iostream>
#include <string>
#include "menua.h"

using namespace std;

int c_fourteen()
{
	string ct14 = "The Princess    -    Chapter XIV    -    Page ";

	system ("cls");
	cout << "The Princess    -    Chapter Fourteen    -    Page 133\n" << endl;
	cout << "The weather was unusually bad for the mild-weathered planet of Loran. Strong" << endl;
	cout << "winds and rain pounded the ground and buildings. People were getting worried" << endl;
	cout << "about the increasingly bad weather and the weather service was powerless to do" << endl;
	cout << "anything about it. It was as if something else had taken control over the" << endl;
	cout << "weather, and was punishing the people of the planet." << endl;
	cout << "    It was raining everywhere and the seas were wild. It was as if the oceans" << endl;
	cout << "were somehow creating the weather. The amount of water vapor and unusual water" << endl;
	cout << "temperatures were the cause of these storms. The prime leader had ordered a" << endl;
	cout << "full investigation to find out what was happening. He was in his office, which" << endl;
	cout << "was a small, plain, room with a green, carpeted floor. There were two chairs" << endl;
	cout << "against one wall and a desk in front of a large window. Behind the desk was a" << endl;
	cout << "very comfortable desk chair in which the prime leader sat. On the walls were" << endl;
	cout << "various pictures and awards that the prime leader had accumulated over his" << endl;
	cout << "years of service and beforehand. On the desk were a flat computer terminal and" << endl;
	cout << "a small keypad that one could type with. In the lower right hand of the desk a" << endl;
	cout << "series of buttons in a diamond-shaped panel, and each of the nine buttons had a" << endl;
	cout << "different function." << endl;
	cout << "    The prime leader was sitting at his desk reviewing a report on the" << endl;
	cout << "watergirl they had captured two days ago. The watch and three scientists had" << endl;
	cout << "made contact when she was in her loran form, and when they stunned her, she" << endl;
	cout << "changed back to her original state." << endl;
	cout << "    The watergirl had not attempted to transform since her capture, nor had she" << endl;
	system ("pause");
	system ("cls");
	cout << ct14 << "134.\n" << endl;
	cout << "attempted to communicate with anyone." << endl;
	cout << "    The report the prime was looking over showed the watergirl had no sign of" << endl;
	cout << "damage, chemical trauma, radiation poisoning, or any other problems. It showed" << endl;
	cout << "her to be in good health, and she seemed similar to the lorans in many ways." << endl;
	cout << "    Scientists were theorizing that if lorans had to adapt to living in water," << endl;
	cout << "they would look similar to the watergirl. They also thought that if evolution" << endl;
	cout << "never put them on land, they would probably evolve similar to the watergirl's" << endl;
	cout << "species. There was a third theory that the watergirl's species was another" << endl;
	cout << "evolutionary stage of the Lorans. The ability to adapt to water or land brought" << endl;
	cout << "that theory on." << endl;
	cout << "    The answer to these theories lied in genetics. They scientists were" << endl;
	cout << "planning to do a complete genetic workup on the new life form, then compare it" << endl;
	cout << "to loran genetics. This would tell them how similar the two really were, and if" << endl;
	cout << "there was a common ancestor." << endl;
	cout << "    The prime leader knew the captured woman would have to be released soon. It" << endl;
	cout << "was against the law to keep intelligent non-animal beings captive for more than" << endl;
	cout << "seventy- two hours, unless it was medically necessary, or the being had" << endl;
	cout << "committed a crime. In this case, neither was true." << endl;
	cout << "    Although the beach was technically off-limits, there was no way the" << endl;
	cout << "watergirl could have known. On the other hand, the law did not leave much room" << endl;
	cout << "for ignorance." << endl;
	cout << "    The prime leader was seriously considering pressing charges, which would by" << endl;
	system ("pause");
	system ("cls");
	cout << ct14 << "135.\n" << endl;
	cout << "him and the science team time to study the captured watergirl." << endl;
	cout << "    He was about to document the charges when his intercom chimed. He pressed" << endl;
	cout << "one of the buttons on the panel on his desk." << endl;
	cout << "    \"What is it?\" asked the prime leader." << endl;
	cout << "    \"Communication for you on priority, sir,\" came a cute female voice over the" << endl;
	cout << "intercom." << endl;
	cout << "    \"Thank you, Jilane,\" said the prime leader, \"Put it through to my" << endl;
	cout << "terminal.\"" << endl;
	cout << "    The prime leader pressed another button to turn off the intercom while his" << endl;
	cout << "computer terminal's display dissolved to the face of an Earth Alliance captain." << endl;
	cout << "    \"This is Prime Leader Shako Lotan,\" said the prime leader, \"Greetings," << endl;
	cout << "Captain. How may I help you?\"" << endl;
	cout << "    \"I'm Captain Louis Al'Fraize of the Earth Alliance vessel Valkyries,\" was" << endl;
	cout << "the response, \"Greetings to you and peace to your people.\"" << endl;
	cout << "    \"Thank you, Captain,\" said the prime leader." << endl;
	cout << "    \"The Earth Alliance counsel has received your petition to join the" << endl;
	cout << "alliance,\" said the captain, \"We should be arriving at your planet in two days" << endl;
	cout << "for inspection.\"" << endl;
	cout << "    \"I'll presume this is a standard inspection,\" said the prime leader." << endl;
	cout << "    \"No,\" said the captain, \"this will be a thorough inspection of your central" << endl;
	cout << "facilities. Is there a problem?\"" << endl;
	cout << "    \"No,\" replied the prime leader, \"No problem, just wanted to know.\"" << endl;
	system ("pause");
	system ("cls");
	cout << ct14 << "136.\n" << endl;
	cout << "    \"Good,\" said the captain, \"We'll see you in two days.\"" << endl;
	cout << "    \"I look forward to it, captain,\" said the prime leader." << endl;
	cout << "    The prime leader pressed one of the buttons in the diamond panel on his" << endl;
	cout << "desk. His computer terminal's display dissolved back to the report on the" << endl;
	cout << "watergirl. The prime leader finished looking it over then added the following:\n" << endl;
	cout << "NOTE: Subject above has been charged with the following crimes:" << endl;
	cout << "  Trespassing on government property" << endl;
	cout << "  Unauthorized entry into a secured zone" << endl;
	cout << "  Unauthorized entry into a restricted zone" << endl;
	cout << "  Espionage" << endl;
	cout << "Subject is currently being held pending prosecution\n" << endl;
	cout << "    The prime leader sent a copy of the charges to the chief of security along" << endl;
	cout << "with a summary of the report." << endl;
	cout << "    That should do it, thought the prime leader before turning his computer" << endl;
	cout << "terminal off." << endl;
	cout << "    The prime leader felt satisfied with the report, and that he had bought a" << endl;
	cout << "substantial amount of time for the scientists. The charges were serious, and" << endl;
	cout << "the woman would eventually be brought to trial, until then she would be held in" << endl;
	cout << "the lab. The prime leader did not care what happened to her after that." << endl;
	cout << "    Two days passed and the E.A. Valkyries arrived at Loran and assumed a" << endl;
	system ("pause");
	system ("cls");
	cout << ct14 << "137.\n" << endl;
	cout << "standard orbit. Aboard, things were going smoothly, except for some unusual" << endl;
	cout << "storms and ionic interference, which would interfere with communications. There" << endl;
	cout << "was also some sort of fluctuation from inside the compound. At first, it was" << endl;
	cout << "thought to be a glitch in the sensors, but that was quickly ruled out." << endl;
	cout << "    The captain took a small shuttle and a co-pilot, Lieutenant Sandra Warren," << endl;
	cout << "down to the planet's surface. Lieutenant Warren was going to talk to one of the" << endl;
	cout << "planet leader's aids about the loran political structure while the captain" << endl;
	cout << "performed his inspection." << endl;
	cout << "    Captain Louis Al'Fraize and his co-pilot landed the shuttle on a landing" << endl;
	cout << "pad just outside the central compound. Fortunately, the interference and storms" << endl;
	cout << "only had a minor effect on the shuttle. This was one of the reasons the captain" << endl;
	cout << "had decided to go anyway." << endl;
	cout << "    The prime leader and one of his aids approached the captain when he cleared" << endl;
	cout << "the shuttle." << endl;
	cout << "    \"Greetings, Captain,\" said the prime leader, \"Welcome to Central Loran; I" << endl;
	cout << "am Prime Leader Shako Lotan.\"" << endl;
	cout << "    \"It's good to finally meet you in person, Prime Leader,\" said the captain," << endl;
	cout << "\"This is my co-pilot Lieutenant Sandra Warren.\"" << endl;
	cout << "    Lieutenant Sandra Warren was five feet and six inches tall, had" << endl;
	cout << "shoulder-length, dark blond hair, and brown eyes. She was a medium built woman" << endl;
	cout << "and had a light complexion." << endl;
	cout << "    \"My aid here will show her around while you do your inspection,\" said the" << endl;
	system ("pause");
	system ("cls");
	cout << ct14 << "138.\n" << endl;
	cout << "prime leader." << endl;
	cout << "    \"Right this way,\" said the aid." << endl;
	cout << "    \"Thank you,\" said Lieutenant Warren." << endl;
	cout << "    \"Interesting weather you're having here,\" said the captain, as the aid and" << endl;
	cout << "his lieutenant went off on their tour." << endl;
	cout << "    The captain had detected the same fluctuation as the Valkyries did in the" << endl;
	cout << "central compound. During the inspection, he identified it as being produced by" << endl;
	cout << "some sort of a sensor shield." << endl;
	cout << "    He stopped at a secured corridor where the shield was near." << endl;
	cout << "    The captain decided to check in with his ship." << endl;
	cout << "    \"Al'Fraize to Valkyries,\" he said into his communicator." << endl;
	cout << "    The communicator looked like a flip-phone, and had much more range. This" << endl;
	cout << "time, however, he only got static. He tried a couple of more times before" << endl;
	cout << "putting it away." << endl;
	cout << "    \"There's been a lot of ionic interference,\" said the prime leader, \"Our" << endl;
	cout << "communications have been affected as well.\"" << endl;
	cout << "    \"Ya,\" said the captain, \"I kind of expected this. Just as long as the" << endl;
	cout << "shuttle works, there should be no problems.\"" << endl;
	cout << "    \"Prime leader,\" came a voice from an approaching loran official." << endl;
	cout << "    Once the official had the prime leader's attention and met up with him, he" << endl;
	cout << "handed the prime leader some sort of report." << endl;
	cout << "    \"I think you should take a look at this,\" said the official." << endl;
	system ("pause");
	system ("cls");
	cout << ct14 << "139.\n" << endl;
	cout << "    The prime leader quickly looked over the report." << endl;
	cout << "    \"I'm sorry, captain,\" said the prime leader, \"I have to go. This shouldn't" << endl;
	cout << "take too long. Why don't you complete your inspection and meet back here in," << endl;
	cout << "say ten minutes.\"" << endl;
	cout << "    \"Not a problem,\" said the captain, \"Duty calls.\"" << endl;
	cout << "    \"Indeed it does,\" said the prime leader, then left the captain." << endl;
	cout << "    The captain tried again to reach his ship, but got the expected static. He" << endl;
	cout << "then pulled out his palm-scanner and started to scan the shield, wondering why" << endl;
	cout << "such a place was shielded in the first place. He found a weakness in the shield" << endl;
	cout << "and got a partial reading, but nothing conclusive. After a few minutes, the" << endl;
	cout << "captain put the scanner away." << endl;
	cout << "    \"What's down that corridor?\" asked the captain when the prime leader got" << endl;
	cout << "back." << endl;
	cout << "    \"This corridor is secured for a reason, Captain,\" said the prime leader," << endl;
	cout << "evading the question." << endl;
	cout << "    \"Can I ask why it's shielded from sensors?\" asked the captain." << endl;
	cout << "    \"How do you know it's shielded?\" asked the prime leader." << endl;
	cout << "    \"We detected it from orbit,\" said the captain, \"and I'm still getting it on" << endl;
	cout << "my scanner.\"" << endl;
	cout << "    \"What are you doing scanning a restricted corridor?\" asked the prime" << endl;
	cout << "leader." << endl;
	cout << "    \"Confirming my ship's readings,\" said the captain, \"I thought this was" << endl;
	system ("pause");
	system ("cls");
	cout << ct14 << "140.\n" << endl;
	cout << "going to be an open inspection.\"" << endl;
	cout << "    \"It is,\" said the prime leader." << endl;
	cout << "    \"Then why the shield,\" asked the captain, \"especially in an area that" << endl;
	cout << "doesn't seem to need it?\"" << endl;
	cout << "    \"That's not important,\" said the prime leader." << endl;
	cout << "    \"Look,\" said the captain, becoming annoyed, \"in order to complete this" << endl;
	cout << "inspection, I need to inspect all central facilities. Your petition said you" << endl;
	cout << "would be completely compliant to all inspections, and that's something you" << endl;
	cout << "wrote yourself. If you can't keep your word on a simple petition, then how are" << endl;
	cout << "you going to keep your word on an official agreement?\"" << endl;
	cout << "    \"Very well, Captain,\" said the prime leader, realizing he had no choice in" << endl;
	cout << "the matter, \"right this way.\"" << endl;
	cout << "    The prime leader led the captain down the restricted corridor, which was" << endl;
	cout << "just a plain white corridor with a secured door at the far wall. He led him to" << endl;
	cout << "the secured door at the end. The prime leader showed the two guards standing on" << endl;
	cout << "either side of the door his badge, and the one on the left slid his card into" << endl;
	cout << "the small card slot on the wall and let the captain and prime leader into the" << endl;
	cout << "secured room." << endl;
	cout << "    The prime leader and the captain entered the large room, which consisted of" << endl;
	cout << "all sorts of machines and consoles. There were two levels with stairs leading" << endl;
	cout << "up to the second level. The second level was plates that went to form a circle." << endl;
	cout << "In the middle of the room was a large tank filled with water. In the tank was" << endl;
	system ("pause");
	system ("cls");
	cout << ct14 << "141.\n" << endl;
	cout << "what seemed to be a naked loran woman that had fins instead of feet. The top of" << endl;
	cout << "the tank came just over the plating of the second level in the room." << endl;
	cout << "    \"What is all this?\" asked the captain, \"And who's that?\"" << endl;
	cout << "    \"That is a new lifeform, Captain,\" responded the prime leader, \"We're" << endl;
	cout << "making sure she's healthy.\"" << endl;
	cout << "    \"What do you mean you're 'making sure she's healthy'?\" asked the captain," << endl;
	cout << "\"How are you doing that?\"" << endl;
	cout << "    \"These machines are monitoring her life signs and collecting valuable data" << endl;
	cout << "for us,\" explained the prime leader, \"Through this data, we are able to tell" << endl;
	cout << "how she's doing and what we need to do for her. You see, Captain, we found her" << endl;
	cout << "unconscious on a beach, and are trying to get her back to health.\"" << endl;
	cout << "    The captain looked at the woman and thought, She seems very sad. I wonder" << endl;
	cout << "if they're really just trying to care for her. These machines aren't standard" << endl;
	cout << "loran medical equipment. It looks almost like they're studying her like a" << endl;
	cout << "specimen or some sort of animal." << endl;
	cout << "    \"Are you sure she's okay?\" the captain asked the prime leader, \"I get the" << endl;
	cout << "impression she doesn't want to be here.\"" << endl;
	cout << "    \"I assure you she's just fine,\" said the prime leader, \"In fact, we will be" << endl;
	cout << "releasing her soon.\"" << endl;
	cout << "    The lights briefly flickered from the storm and the prime leader briefly" << endl;
	cout << "looked up, concerned." << endl;
	cout << "    \"Why don't you try to talk to her?\" asked the prime leader, \"We've tried" << endl;
	system ("pause");
	system ("cls");
	cout << ct14 << "142.\n" << endl;
	cout << "everything we can think of, but haven't had any luck yet.\"" << endl;
	cout << "    \"That's a good idea,\" said the captain." << endl;
	cout << "    The captain took out his palm-scanner and spent about five minutes" << endl;
	cout << "adjusting it. When he was done, he turned it on." << endl;
	cout << "    The palm-scanner was a small rectangular item that had a flip-open readout," << endl;
	cout << "buttons on both sides, and a digital interface below the display." << endl;
	cout << "    \"Hello, there,\" he said to the princess, \"I'm Captain Al'Fraize, what's" << endl;
	cout << "your name?\"" << endl;
	cout << "    There was no response, so the captain made a few more adjustments to his" << endl;
	cout << "scanner then tried again." << endl;
	cout << "    \"You don't want to be here, do you?\" the captain asked the woman." << endl;
	cout << "    The woman slowly shook her head." << endl;
	cout << "    No, thought the captain, after studying the woman a little closer, she's" << endl;
	cout << "not sad; she's sedated." << endl;
	cout << "    \"That's amazing, captain,\" said the prime leader, \"How did you do that?\"" << endl;
	cout << "    \"I turned my scanner into a temporary universal translator. It won't last" << endl;
	cout << "long, but it's a start.\"" << endl;
	cout << "    \"We tried universal translators, but got nothing,\" said the prime leader." << endl;
	cout << "    \"Well,\" said the captain, \"she is quite sedated.\"" << endl;
	cout << "    \"Do you want to get out?\" asked the captain, addressing the woman." << endl;
	cout << "    The woman nodded her head, strongly indicating she wanted to be released." << endl;
	cout << "    \"I can't blame you,\" said the captain." << endl;
	system ("pause");
	system ("cls");
	cout << ct14 << "143.\n" << endl;
	cout << "    \"Well,\" said the captain to the prime leader, \"I don't know about you, but" << endl;
	cout << "I don't think she wants to be here.\"" << endl;
	cout << "    \"Captain,\" said the prime leader, \"you can't be absolutely sure she" << endl;
	cout << "understood what you said, or that her signals meant what you think they meant.\"" << endl;
	cout << "    \"Okay,\" said the captain, \"Enough of this. According to your regulation" << endl;
	cout << "one-forty, section six, no intelligent being is to be confined in an" << endl;
	cout << "observatory, lab, facility, or other environment intended for or designed for" << endl;
	cout << "study or scientific observation, except under signed contract. Now, I can" << endl;
	cout << "clearly see that the woman is unwilling to be here and is groggy from" << endl;
	cout << "sedation.\"" << endl;
	cout << "    \"I don't know what you mean,\" said the prime leader." << endl;
	cout << "    \"I mean this setup,\" said the captain, \"It looks more like a lab than a" << endl;
	cout << "medical facility. You're going to have to let the woman go.\"" << endl;
	cout << "    \"I'm sorry captain,\" said the prime leader, \"but I can't do that, and in" << endl;
	cout << "case you forgot-\"" << endl;
	cout << "    The prime leader was interrupted by a power failure, which knocked out the" << endl;
	cout << "lights." << endl;
	cout << "    When the lights came back on, the woman was trying to get out of the tank." << endl;
	cout << "She had transformed into loran form and was making quick progress." << endl;
	cout << "    \"The watergirl's escaping!\" warned the primary leader, \"Get her!\"" << endl;
	cout << "    One of the technicians approached the woman with some kind of medical" << endl;
	cout << "injector to sitting her. Meanwhile, two other technicians ran toward her to" << endl;
	system ("pause");
	system ("cls");
	cout << ct14 << "144.\n" << endl;
	cout << " counter any resistance." << endl;
	cout << "    \"Move away from her!\" Captain Al'Fraize warned as he drew his laser-pistol." << endl;
	cout << "    The technicians turned to see the captain, and then slowly moved away from" << endl;
	cout << "the woman." << endl;
	cout << "    \"Move away from the tank and let her get out,\" said the captain." << endl;
	cout << "    The woman climbed out of the tank to the stairs, then carefully walked down" << endl;
	cout << "the steps as not to slip or fall. The captain grabbed a nearby towel and gave" << endl;
	cout << "it to the princess." << endl;
	cout << "    The princess took the, towel and wrapped it around her body." << endl;
	cout << "    Suddenly, three loran guards came in through the door with their weapons" << endl;
	cout << "drawn." << endl;
	cout << "    \"Drop your weapon!\" the lead guard yelled." << endl;
	cout << "    The captain turned toward the guards to see darkness. The lights had gone" << endl;
	cout << "out again." << endl;
	cout << "    Suddenly, in the darkness, there were a series of 'oof's and 'oh's and" << endl;
	cout << "other various noises. Something shattered and weapons were fired, missing their" << endl;
	cout << "intended targets. When the lights finally came back on, the guards and the" << endl;
	cout << "technicians were getting up. Two technicians lay on the floor, unconscious." << endl;
	cout << "There was broken glass and some blood on the floor. A table was overturned and" << endl;
	cout << "a technician lay on the other side. The prime leader somehow through it all," << endl;
	cout << "was untouched." << endl;
	cout << "    The prime leader noticed that the captain and the princess were gone." << endl;
	system ("pause");
	system ("cls");
	cout << ct14 << "145.\n" << endl;
	cout << "    \"They've escaped!\" yelled the prime reader, \"Find them!\"" << endl;
	cout << "    The guards scrambled to their feet and ran out of the lab to find the woman" << endl;
	cout << "and captain.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" << endl;
	system ("pause");
	menua();
	return 0;
}
