#include <iostream>
#include <string>
#include "menua.h"

using namespace std;

int c_nineteen()
{
	string ct19 = "The Princess    -    Chapter XIX    -    Page ";

	system ("cls");
	cout << "The Princess    -    Chapter Nineteen    -    Page 172\n" << endl;
	cout << "The captain and his co-pilot, Lieutenant Warren, had successfully maneuvered" << endl;
	cout << "through the storms, with little difficulty and were now making their way back" << endl;
	cout << "to the Valkyries. The shuttle was made to handle much worse than the storms," << endl;
	cout << "and Lieutenant Warren was able to easily pilot through it. This was fun" << endl;
	cout << "compared to some other things she had to pilot through." << endl;
	cout << "    \"Sir,\" said the lieutenant, \"are you sure we did the right thing back" << endl;
	cout << "there? I mean, couldn't we have handled the situation more... I don't know," << endl;
	cout << "delicately?\"" << endl;
	cout << "    \"I don't think we had much of a choice,\" said the captain, \"If we had" << endl;
	cout << "followed standard procedures, the princess most likely would've gotten lost in" << endl;
	cout << "the bureaucracy, and never freed. The Lorans would then have been free to do as" << endl;
	cout << "they pleased, including conduct their so-called observations. I don't know if I" << endl;
	cout << "could live with knowing I could have done something about it instead of just" << endl;
	cout << "blindly following procedures. If you had seen what was happening, I think you" << endl;
	cout << "would understand.\"" << endl;
	cout << "    \"Probably,\" said Lieutenant Warren, \"In fact, from the sound of it, if it" << endl;
	cout << "were me, I probably would've done the same.\"" << endl;
	cout << "    They broke through the Loran atmosphere and began their final approach to" << endl;
	cout << "the Valkyries. The easy part was over. The hard part would be facing Fleet" << endl;
	cout << "Command." << endl;
	cout << "    The captain opened a com-link to the ship to confirm clearance to land in" << endl;
	cout << "the shuttle bay." << endl;
	system ("pause");
	system("cls");
	cout << ct19 << "173.\n" << endl;
	cout << "    \"Shuttle one to Valkyries,\" he said, \"we are on final approach; request" << endl;
	cout << "clearance for landing.\"" << endl;
	cout << "    \"Copy that, shuttle one,\" was the response, \"You are clear for final" << endl;
	cout << "approach and landing.\"" << endl;
	cout << "    \"Thank you Valkyries,\" said the captain, \"Shuttle one out.\"" << endl;
	cout << "    The captain pressed the com button to close the channel." << endl;
	cout << "    \"I hope Fleet Command agrees with what we did,\" said the lieutenant." << endl;
	cout << "    \"So do I,\" said the captain, feeling they would not, \"If not, we could be" << endl;
	cout << "facing a court martial, depending how who gets upset and how much.\"" << endl;
	cout << "    The shuttle arrived in the Valkyrie's landing bay, and Lieutenant Warren" << endl;
	cout << "gently set it down. The captain opened the shuttle's hatch, then went directly" << endl;
	cout << "to the bridge while the lieutenant secured the shuttle." << endl;
	cout << "    \"Contact Fleet Command,\" said the captain, upon arriving on the bridge," << endl;
	cout << "\"Notify them of the incident, and send them my report.\"" << endl;
	cout << "    \"Aye, sir,\" said the communications officer." << endl;
	cout << "    The captain then sat down in the command chair. Captain Al'Fraize had sent" << endl;
	cout << "a report about the incident from the shuttle with a notice that Fleet Command" << endl;
	cout << "would be notified upon their arrival on the Valkyries." << endl;
	cout << "    Lieutenant Warren arrived on the bridge a few moments later and took the" << endl;
	cout << "navigation counsel, relieving the current officer." << endl;
	cout << "    \"Fleet Command has been notified, sir,\" said the communications officer," << endl;
	cout << "after a few minutes." << endl;
	system("pause");
	system("cls");
	cout << ct19 << "174.\n" << endl;
	cout << "    \"Very good,\" said the captain." << endl;
	cout << "    \"What exactly happened down there?\" asked Commander Lestler." << endl;
	cout << "    Commander Kevin Lestler was six feet and two inches tall with short, brown," << endl;
	cout << "hair, and blue eyes. He was a clean-shaven man of medium build, and was a very" << endl;
	cout << "confident person." << endl;
	cout << "    \"Let's put it this way,\" said the captain, \"things didn't go according to" << endl;
	cout << "plan, and due to unexpected and unusual circumstances, we were forced to" << endl;
	cout << "improvise.\"" << endl;
	cout << "    The commander gave the captain a concerned look, knowing that was not good" << endl;
	cout << "news." << endl;
	cout << "    \"That doesn't sound very good,\" said the commander." << endl;
	cout << "    \"It's not,\" said the captain, \"The Loran government is going to have a fit." << endl;
	cout << "I just don't see how else I could've both protected her and stayed out of" << endl;
	cout << "trouble.\"" << endl;
	cout << "    \"Sounds complicated,\" said the commander." << endl;
	cout << "    \"It was one of those decisions that had to be made swiftly,\" said the" << endl;
	cout << "captain, \"I didn't have time to sit and negotiate it. Besides, they weren't" << endl;
	cout << "listening to me anyway.\"" << endl;
	cout << "    \"Captain,\" announced Lieutenant Swasey after a few minutes, \"We're" << endl;
	cout << "receiving a transmission from Fleet Command. It's Admiral Carey; he wants to" << endl;
	cout << "speak to you.\"" << endl;
	cout << "    \"Put him through,\" said the captain." << endl;
	system("pause");
	system("cls");
	cout << ct19 << "175.\n" << endl;
	cout << "    The viewscreen, which was located in the front-center of the bridge," << endl;
	cout << "switched to show a man of about fifty years old with thin spectacles, short," << endl;
	cout << "dark-brown hair, and a clean-shaven face." << endl;
	cout << "    \"Captain Al'Fraize,\" said the admiral, sounding very annoyed." << endl;
	cout << "    \"Admiral,\" responded the captain, professionally, \"I know what this is" << endl;
	cout << "about, and the explanation is in my report.\"" << endl;
	cout << "    The captain knew Fleet Command would not be happy with what he had done," << endl;
	cout << "and had expected to be chewed out for it. It was no surprise to him that the" << endl;
	cout << "admiral seemed upset." << endl;
	cout << "    \"Well, this certain isn't a congratulatory speech,\" said the admiral," << endl;
	cout << "clearly unhappy with what had happened, \"What the hell do you think you were" << endl;
	cout << "doing down there, anyway?\"" << endl;
	cout << "    \"Well, sir,\" responded the captain, \"I had just about completed a full," << endl;
	cout << "thorough inspection of the loran's facilities when I discovered the woman in a" << endl;
	cout << "lab set-up the Lorans were trying to pass of as a medical treatment center. It" << endl;
	cout << "was actually more like a medical research lab; the description is in the" << endl;
	cout << "report. I then discovered the Lorans were performing what would be considered" << endl;
	cout << "to be immoral and unethical studies in the name of so-called science, if you" << endl;
	cout << "catch my drift. Even by their own laws, the Lorans were committing several" << endl;
	cout << "crimes by performing these procedures.\"" << endl;
	cout << "    \"So you decided to play judge and jury,\" said the admiral, \"and took" << endl;
	cout << "matters into your own hands.\"" << endl;
	system("pause");
	system("cls");
	cout << ct19 << "176.\n" << endl;
	cout << "    \"It wasn't exactly like that, admiral,\" said the captain, \"I decided I had" << endl;
	cout << "to take the chance and free her. I figured that if I went to Fleet Command, she" << endl;
	cout << "would have just gotten lost in paperwork and technicalities. I knew what they" << endl;
	cout << "were doing was wrong, even by their own standards, and I know there are laws" << endl;
	cout << "against this sort of thing in the Alliance as well.\"" << endl;
	cout << "    \"First of all,\" said the admiral, obviously still aggravated, \"Loran isn't" << endl;
	cout << "part of the alliance, yet. Second, you allowed your personal feelings to get in" << endl;
	cout << "the way of your judgment, and as if that weren't enough, you attacked several" << endl;
	cout << "Loran guards and sabotaged their equipment. Because of this, I have complaints" << endl;
	cout << "up to my neck from the Loran government. The board is not going to look kindly" << endl;
	cout << "upon this. You'd better hope they feel your actions are justified, because I" << endl;
	cout << "don't. Your orders are to maintain orbit around Loran. The board will be" << endl;
	cout << "reviewing your report in the meantime. Admiral Carey out.\"" << endl;
	cout << "    The viewscreen switched back to show the planet. Interference with another" << endl;
	cout << "culture, whether it was minor or not, was taken seriously by Fleet Command." << endl;
	cout << "    \"Now we wait,\" said the captain." << endl;
	cout << "    \"He didn't even give you a chance,\" Said Commander Lestler." << endl;
	cout << "    \"I guess this means we're going to be here for a while,\" said Lieutenant" << endl;
	cout << "Warren." << endl;
	cout << "    \"Depends on how long the board decides to take,\" said the captain, \"Most" << endl;
	cout << "likely they won't like what we did. I just don't see any other way I could've" << endl;
	cout << "handled it. I couldn't just let the so-called observations continue, and I knew" << endl;
	system("pause");
	system("cls");
	cout << ct19 << "177.\n" << endl;
	cout << "the Lorans weren't going to release her. If we went through standard channels," << endl;
	cout << "nothing would've been done for at least six months and by that time she" << endl;
	cout << "could've been dead, or worse.\"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" << endl;
	system("pause");
	menua();
	return 0;
}
