#include <iostream>
#include <string>
#include "menu.h"

using namespace std;

int c_nine()
{
	string ct9 = "The Princess    -    Chapter IX    -    Page ";

	system ("cls");
	cout << "The Princess    -    Chapter Nine    -    Page 116\n" << endl;
	cout << "Princess Leanne swam to land in loran form, and then started to look around for" << endl;
	cout << "something nice to bring to Monia. It was at the end of summer, and the weather" << endl;
	cout << "was pleasant. It was a perfect day for staying on the surface." << endl;
	cout << "    Monia and the princess had been swimming most of the day, and it was" << endl;
	cout << "starting to get dark, making it difficult to find anything on the beach. The" << endl;
	cout << "princess decided it was time to head back, seeing as it was getting late. She" << endl;
	cout << "and Monia could always return the next day." << endl;
	cout << "    The princess went back into the water, waded in up to waist, dove in, and" << endl;
	cout << "then changed back to coshen. After doing this, she swam over to where Monia was" << endl;
	cout << "waiting to talk with her." << endl;
	cout << "    \"Come on,\" said the princess, \"It's getting late, and I can't see much in" << endl;
	cout << "this light.\"" << endl;
	cout << "    \"Did you find anything?\" asked Monia." << endl;
	cout << "    \"No,\" said the princess, \"It's too dark to see in that form. We'll come" << endl;
	cout << "back tomorrow.\"" << endl;
	cout << "    Monia and the princess swam back to Cosha-Prime and to the palace slightly" << endl;
	cout << "disappointed. The guards let them in, and they went to the princess's chambers" << endl;
	cout << "to have dinner. Monia prepared then served the princess's food, then went and" << endl;
	cout << "prepared her bed and nightwear." << endl;
	cout << "    The next day was sunny and warm. It was a perfect day for searching the" << endl;
	cout << "beach. When the princess awoke that morning, she summoned Monia, who brought" << endl;
	cout << "the princess her breakfast. After breakfast was finished, Monia helped the" << endl;
	system ("pause");
	system ("cls");
	cout << ct9 << "117\n" << endl;
	cout << "princess decide what to wear." << endl;
	cout << "    \"Do you know what I should do?\" asked the princess as she put on a strapped" << endl;
	cout << "skimmie." << endl;
	cout << "    The skimmie was the bikini-like tops that coshen women wore in the warm" << endl;
	cout << "waters. They came in a variety of designs, colors, and patterns. The particular" << endl;
	cout << "type she was wearing had shoulder straps and tied in the back." << endl;
	cout << "    \"What should you do?\" asked Monia." << endl;
	cout << "    \"I should have the seamstress,\" said the princess, \"make me something to" << endl;
	cout << "cover my lower half in loran form. Something to go with one or more of my" << endl;
	cout << "skimmies, or a long shirt that goes halfway down my lower body.\"" << endl;
	cout << "    \"You could just wear a long top that covers you,\" said Monia, \"I think you" << endl;
	cout << "might have one or two that are that long. That way you don't have to worry" << endl;
	cout << "about the seamstress making something. Or you could just wear a dress without a" << endl;
	cout << "slip.\"" << endl;
	cout << "    \"No slip?\" the princess looked at Monia as if she had lost her mind," << endl;
	cout << "\"You're kidding, right?\"" << endl;
	cout << "    \"You got some dresses that won't show anything,\" said Monia." << endl;
	cout << "    \"Okay,\" said the princess, \"Two things: One, any dress worn without a slip" << endl;
	cout << "is both improper and uncomfortable; and two, I'm not wearing a dress to the" << endl;
	cout << "beach. I don't want to swim that far in a dress, and I can't swim that fast in" << endl;
	cout << "a dress, so If any sharks come by, I'm done for. The idea is out of the" << endl;
	cout << "question.\"" << endl;
	system ("pause");
	system ("cls");
	cout << ct9 << "118\n" << endl;
	cout << "    \"Okay,\" said Monia in a definite tone, \"No dress. What about one of your" << endl;
	cout << "long tops?\"" << endl;
	cout << "    \"I don't have any tops long enough to cover me that much,\" said the" << endl;
	cout << "princess, \"I'll worry more about this later. I have a meeting to attend in less" << endl;
	cout << "than two hours.\"" << endl;
	cout << "    \"Got it,\" said Monia as the princess sat down to have her hair done, \"How" << endl;
	cout << "about if I talk to the seamstress while you're at the meeting?\"" << endl;
	cout << "    \"No,\" said the princess, \"I want to talk to her personally, so she gets an" << endl;
	cout << "idea of exactly what I want.\"" << endl;
	cout << "    \"Very well,\" said Monia." << endl;
	cout << "    \"Why don't we go to the beach when I come back from my meeting?\" asked the" << endl;
	cout << "princess \"It shouldn't take that long.\"" << endl;
	cout << "    \"Okay,\" said Monia, enthusiastically." << endl;
	cout << "    \"Great,\" said the princess, \"We'll leave as soon as we're ready.\"" << endl;
	cout << "    The princess and Monia chatted while Monia fixed up the princess's hair." << endl;
	cout << "    \"Now,\" said Monia, while handing the princess her tiara, \"don't forget to" << endl;
	cout << "wear this when we go to the beach later. I noticed you didn't wear it last" << endl;
	cout << "night.\"" << endl;
	cout << "    \"I didn't want to lose it,\" said the princess." << endl;
	cout << "    \"You won't,\" said Monia, \"It stays on too well.\"" << endl;
	cout << "    \"Well, alright,\" said the princess, \"I'll wear it, but if something happens" << endl;
	cout << "to it...\"" << endl;
	system ("pause");
	system ("cls");
	cout << ct9 << "119\n" << endl;
	cout << "    \"If something happens to it,\" said Monia, \"you can blame me for it.\"" << endl;
	cout << "    \"That's not the point,\" said the princess, \"This tiara was my mothers. It's" << endl;
	cout << "all I have of her.\"" << endl;
	cout << "    \"Well, then,\" said Monia, \"You'll have to be sure you don't take it off; I" << endl;
	cout << "can make sure it's secure. You can't leave the castle without it; at least" << endl;
	cout << "you're not supposed to, anyway. Not only that, but it reminds people you are" << endl;
	cout << "the princess of Cosha, and makes it easier to get in and out of the castle.\"" << endl;
	cout << "    \"Okay,\" said the princess, \"It's just that we're going into Fiana, and I" << endl;
	cout << "don't want to lose it. If I lose my tiara in Fiana, we'll never find it.\"" << endl;
	cout << "    \"Don't worry,\" said Monia, \"You won't lose it.\"" << endl;
	cout << "    \"You know I'm only going to undo your work after the meeting, don't you?\"" << endl;
	cout << "said the princess, referring to her hair." << endl;
	cout << "    \"I know,\" said Monia, \"and I don't care. I want you to look good for the" << endl;
	cout << "meeting. You have beautiful hair and a pretty face. I think you should show off" << endl;
	cout << "both.\"" << endl;
	cout << "    \"Thank you,\" said the princess." << endl;
	cout << "    Monia finished the princess's hair, then handed her the tiara." << endl;
	cout << "    \"All set,\" said Monia as she handed the tiara to the princess." << endl;
	cout << "    The princess put her tiara on, and Monia showed her what she did." << endl;
	cout << "    \"So,\" said Monia, \"what do you think?\"" << endl;
	cout << "    The princess looked into the wall mirror next to her dresser, and Monia" << endl;
	cout << "used a hand mirror to show her the sides and back." << endl;
	system ("pause");
	system ("cls");
	cout << ct9 << "120\n" << endl;
	cout << "    \"I like it,\" said the princess, \"beautiful, yet it says business. Kind of a" << endl;
	cout << "semi-casual look. It's perfect for the meeting.\"" << endl;
	cout << "    \"I'm glad you like it,\" said Monia, \"It was a pleasure.\"" << endl;
	cout << "    Time passed, and the princess went to the meeting, which took about an" << endl;
	cout << "hour, bringing the time to late morning." << endl;
	cout << "    When the meeting was over, the princess returned to her chambers. Monia had" << endl;
	cout << "come with the princess to her meeting, though stayed outside the meeting room," << endl;
	cout << "and was still with her. Another servant was cleaning her chambers when the two" << endl;
	cout << "came in." << endl;
	cout << "    When the princess entered her chambers, she sat down and Monia started to" << endl;
	cout << "undo her hair. She redid the princess's hair in a more free and relaxed style." << endl;
	cout << "When it was done, the princess put her tiara on. The hairstyle seemed to secure" << endl;
	cout << "the tiara more than if she had just placed it there." << endl;
	cout << "    \"Are you sure about me wearing this?\" the princess asked Monia." << endl;
	cout << "    \"Well,\" said Monia, \"If you're that concerned, we can always not go.\"" << endl;
	cout << "    \"I just wish I had a second tiara,\" said the princess, \"One I could afford" << endl;
	cout << "to lose.\"" << endl;
	cout << "    \"You'll just have to make sure you don't lose this one,\" said Monia, \"I'll" << endl;
	cout << "help you by making sure it doesn't come off, and if it does, I'll be right" << endl;
	cout << "there to get it. Between the two of us, I don't think you have much to worry" << endl;
	cout << "about.\"" << endl;
	cout << "    \"Come on,\" said the princess, \"Let's leave before it gets too late.\"" << endl;
	system ("pause");
	system ("cls");
	cout << ct9 << "121\n" << endl;
	cout << "    The princess and Monia left for the beach they had visited the day before.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" << endl;
	system ("pause");
	menu();
	return 0;
}
