#include <iostream>
#include <string>
#include "menu.h"

using namespace std;

int c_one()
{
	string ct1 = "The Princess    -    Chapter I    -    Page ";

	system ("cls");
	cout << "The Princess    -    Chapter One    -    Page 44\n" << endl;
	cout << "    It was two years after the royal wedding, and Queen Demril was expecting a" << endl;
	cout << "child. Eight months had passed since conception, and the queen had not been" << endl;
	cout << "feeling well for the past couple of weeks. That morning, though, she was in" << endl;
	cout << "better spirits." << endl;
	cout << "    It was a clear morning, with little to no seaweed, and the king had already" << endl;
	cout << "said good morning to the queen, and kissed her." << endl;
	cout << "    \"How are you feeling?\" asked the king, after the kiss." << endl;
	cout << "    \"Much better than I have been,\" said the queen, \"The doctor is due to see" << endl;
	cout << "me today.\"" << endl;
	cout << "    \"I know,\" said the king, \"Are you sure you don't want to know whether the" << endl;
	cout << "baby is a boy or girl?\"" << endl;
	cout << "   \"Mother always told me,\" said the queen, \"that it's bad luck to know the" << endl;
	cout << "gender of your baby before it's born. She used to say that knowing so could" << endl;
	cout << "cause bad things to happen to it, or make the child difficult. However, if you" << endl;
	cout << "really want to know...\"" << endl;
	cout << "     \"Well,\" said the king, \"that's interesting because I've heard some stories" << endl;
	cout << "about couples and their babies who did wait to find out.\"" << endl;
	cout << "    The king and his queen shared a laugh." << endl;
	cout << "    \"Well,\" said the queen,\" we'll find out soon enough. I think we should" << endl;
	cout << "wait. The surprise will be well worth the wait. Truthfully, though, I have a" << endl;
	cout << "feeling it's going to be a girl.\"" << endl;
	cout << "    \"You know what they say,\" said the king, \"there's nothing like an expecting" << endl;
	system ("pause");
	system ("cls");
	cout << ct1 << "45\n" << endl;
	cout << "mother's intuition, but I'm hoping it's going to be a boy.\"" << endl;
	cout << "    \"Have you chosen the names for the baby yet?\" asked the queen." << endl;
	cout << "    \"Yes,\" said the king, \"I believe we should go with Cadel if it's a boy and" << endl;
	cout << "Leanne if it's a girl.\"" << endl;
	cout << "    \"I like those names,\" said the queen." << endl;
	cout << "    \"I really hope it's a boy, though\" said the king, \"You know, a prince to" << endl;
	cout << "raise to learn to be king, eventually, and carry on the family name. After" << endl;
	cout << "that, it doesn't matter to me if we have ten girls.\"" << endl;
	cout << "    \"Ten?\" asked the queen, \"I don't think I'm willing or able to bear that" << endl;
	cout << "many children.\"" << endl;
	cout << "    \"Well,\" said the king, \"I was exaggerating a bit.\"" << endl;
	cout << "    \"You'll still love the baby the same if it's a girl, won't you?\" asked the" << endl;
	cout << "queen." << endl;
	cout << "    \"Of course, Demril,\" said the king, sincerely, \"she'll still be our baby," << endl;
	cout << "and I will do anything I can to be sure she grows up to be the princess she" << endl;
	cout << "should be.\"" << endl;
	cout << "    \"I'm glad,\" said the queen." << endl;
	cout << "    \"And I will kill anyone who would dare harm her,\" added the king." << endl;
	cout << "    The queen smiled, feeling very happy her king would be so protective of" << endl;
	cout << "their child." << endl;
	cout << "    The king and queen embraced each other, and then kissed on the lips. It was" << endl;
	cout << "a promising kiss that silently said their child would be loved and cherished no" << endl;
	system ("pause");
	system ("cls");
	cout << ct1 << "46\n" << endl;
	cout << "matter what gender it was." << endl;
	cout << "    A couple of hours passed before the royal doctor arrived. When he did" << endl;
	cout << "arrive, he paid his respects to both the king and the queen. Soon after that," << endl;
	cout << "he was escorted to a private room that would later be used for delivery of the" << endl;
	cout << "unborn child. For the time being though, it was being used as an examination" << endl;
	cout << "room." << endl;
	cout << "    A minute or two after the doctor was shown to the room, the midwife, who" << endl;
	cout << "took care of the queen through most of the pregnancy and would be helping to" << endl;
	cout << "deliver the baby, joined him." << endl;
	cout << "    The doctor performed the examination, and when it was over, and the queen" << endl;
	cout << "and unborn baby were declared healthy, the doctor bid them goodbye. The midwife" << endl;
	cout << "stayed with the queen to give her instructions, and recommendations for her" << endl;
	cout << "delivery. The queen then rejoined the king, while the midwife cleaned up. The" << endl;
	cout << "midwife then bid the king and queen goodbye, and left." << endl;
	cout << "    \"The doctor says everything's going well,\" said the queen, \"The baby's" << endl;
	cout << "healthy, but I might be a little late, but there's probably nothing to worry" << endl;
	cout << "about.\"" << endl;
	cout << "    \"We'll know more as the time gets closer,\" said the king, \"I'm sure" << endl;
	cout << "everything's going to be just fine.\"" << endl;
	cout << "    \"Me to,\" said the queen, \"Besides, it's pretty normal for the first child" << endl;
	cout << "to be born late anyway.\"" << endl;
	cout << "    \"True,\" said the king." << endl;
	system ("pause");
	system ("cls");
	cout << ct1 << "47\n" << endl;
	cout << "    The king and queen had made their way to a comfortable seating area and" << endl;
	cout << "were now sitting next to each other. The queen cuddled the king and thought of" << endl;
	cout << "all the wonderful things she would enjoy with their new baby." << endl;
	cout << "    \"We're going to have a beautiful child,\" said the queen." << endl;
	cout << "    \"Well,\" said the king, \"They say a child conceived out of love, will be a" << endl;
	cout << "very loving child.\"" << endl;
	cout << "    The king and queen continued to cuddle each other." << endl;
	cout << "    The days passed on, and Queen Demril delivered a baby girl two weeks past" << endl;
	cout << "her due date. The king and queen named her Leanne, and all was well with the" << endl;
	cout << "Coshens." << endl;
	cout << "    The Lorans, on the other hand, had been fighting a long, fierce war among" << endl;
	cout << "themselves. The war, however, ended with the birth of the Coshen princess. The" << endl;
	cout << "Lorans had no way of knowing about the birth, and the peace treaties were" << endl;
	cout << "signed as the queen gave birth to the princess." << endl;
	cout << "    There were celebrations among both the Lorans and the Coshens on the day" << endl;
	cout << "the princess was born. It had been for different reasons, but the world still" << endl;
	cout << "rejoiced, and peace was upon the Lorans and the Coshens. This was the day Cosha" << endl;
	cout << "received a new princess and the Lorans were finally united after centuries of" << endl;
	cout << "squabbling and fighting." << endl;
	cout << "    The Coshens had been aware of the Lorans for quite some time, while the" << endl;
	cout << "Lorans lived in ignorance about the Coshens. Although no real contact had been" << endl;
	cout << "made, a few coshen women had occasionally been spotted by loran fishermen." << endl;
	system ("pause");
	system ("cls");
	cout << ct1 << "48\n" << endl;
	cout << "Through the years, these fishermen would occasionally return home with stories" << endl;
	cout << "of beautiful women from the sea that looked like loran women, but more" << endl;
	cout << "beautiful, and with fins like a fish instead of feet." << endl;
	cout << "    These 'wild' stories were often dismissed as delusions of lonely fishermen." << endl;
	cout << "The fishermen were told they had actually seen a sea creature that they mistook" << endl;
	cout << "for one of these so-called seawomen. The stories were even dismissed as" << endl;
	cout << "overactive imaginations, brought on by either lack of rest, loneliness, or" << endl;
	cout << "both. Sometimes the stories were even dismissed as delirium." << endl;
	cout << "    These sightings were usually reported by deep-sea fishermen who often spent" << endl;
	cout << "months at sea. Eventually the sightings became less and less often until they" << endl;
	cout << "stopped altogether and fell into myths and fables. The Lorans started to create" << endl;
	cout << "stories about seamen and seawomen, based on the myths for amusement. Some of" << endl;
	cout << "these stories were unrealistic, while others were more believable. No one" << endl;
	cout << "really cared either way, as long as the stories were entertaining. It was all" << endl;
	cout << "considered fantasy, and thought that such creatures never existed in the first" << endl;
	cout << "place." << endl;
	cout << "    If only the Lorans knew how wrong, they were." << endl;
	cout << "    The Coshens were aware of the Lorans, but had made very little contact with" << endl;
	cout << "them. They would refer to the Lorans simply as land-dwellers. This was to" << endl;
	cout << "simplify and consolidate the many various other general terms used to describe" << endl;
	cout << "them. Over time, the general population had adopted the term." << endl;
	cout << "    At the present, King Toran was considering the idea of making official" << endl;
	system ("pause");
	system ("cls");
	cout << ct1 << "49\n" << endl;
	cout << "contact with these strange land-dwelling creatures, as he had once described" << endl;
	cout << "them. Before making contact, the king felt more should be learned about them." << endl;
	cout << "This way when official contact was made, there would be less chance of a" << endl;
	cout << "misinterpretation or disaster." << endl;
	cout << "    Since the Coshens had the ability to transform into the land-dwellers'" << endl;
	cout << "form, the king began to choose and train specially chosen Coshens to go on" << endl;
	cout << "observation missions." << endl;
	cout << "    The object of these missions were to observe the land-dwellers and assess" << endl;
	cout << "them for official contact. If they were ready, the king would lead a team on a" << endl;
	cout << "first-contact mission. If the land-dwellers were not ready, more observations" << endl;
	cout << "would be conducted until the land-dwellers were ready." << endl;
	cout << "    One such Coshen chosen to go on one of the observation missions was Coral" << endl;
	cout << "Me-Ak. She was a young Coshen of twenty-two, with shoulder-length, light brown" << endl;
	cout << "hair, light-green eyes, and her lower body was sea green." << endl;
	cout << "    She had been chosen for the mission because she could improvise, adapt" << endl;
	cout << "quickly to new, sudden, and unusual circumstances. She was also a fast learner" << endl;
	cout << "with an excellent memory. She was taught the land-dwellers' language and as" << endl;
	cout << "much knowledge about their culture as was known. She was then trained in using" << endl;
	cout << "the transformation." << endl;
	cout << "    Another Coshen sent on one of these missions was Tikel Dalmar. He was" << endl;
	cout << "twenty-three years old, with black hair that was cut short. He had brown eyes," << endl;
	cout << "and a dark-blue lower half." << endl;
	system ("pause");
	system ("cls");
	cout << ct1 << "50\n" << endl;
	cout << "    Tikel had been chosen for the mission because he was smart, had studied" << endl;
	cout << "loran culture, and was a good negotiator." << endl;
	cout << "    There were other pioneers in this field, each with a separate destination." << endl;
	cout << "Among the first were also Tameth Kindra, Sandy Amil, and Mido Wen." << endl;
	cout << "    These were the first five Coshens sent to observe and learn about the" << endl;
	cout << "Lorans. They became known as pre-contact missions, and were considered very" << endl;
	cout << "important." << endl;
	cout << "    More Coshens were later sent on other, more detailed missions. They were to" << endl;
	cout << "mingle and even live among the Lorans, as the Coshens quickly learned that was" << endl;
	cout << "what they were really called. This was so they could observe the Lorans in a" << endl;
	cout << "more detailed fashion." << endl;
	cout << "    Two years later, King Toran decided the Lorans were ready for official" << endl;
	cout << "contact. This would be a very important event in coshen history, and was to be" << endl;
	cout << "handled very delicately. King Toran decided that he himself would handpick" << endl;
	cout << "which Coshens would go with him on this mission." << endl;
	cout << "    The party would consist of five Coshens. Two guards, a medic, a scientist," << endl;
	cout << "and the king himself. The king, of course, would lead the party." << endl;
	cout << "    However, at the moment, King Toran of Cosha was watching his now two-year-" << endl;
	cout << "old daughter play with the sea horses. King Toran was a strong, proud man who" << endl;
	cout << "was six feet even with brown hair and blue eyes." << endl;
	cout << "    He wore a crown, which allowed him to have his power, and although ancient," << endl;
	cout << "it looked like it had been just made. This crown gave its wearer the power over" << endl;
	system ("pause");
	system ("cls");
	cout << ct1 << "51\n" << endl;
	cout << "the ocean and all the creatures and plants within." << endl;
	cout << "    His daughter was playing with sea horses, which were a little smaller than" << endl;
	cout << "her little hands. The sea horses, like the princess, were very playful. They" << endl;
	cout << "seemed to love teasing her by swimming close to her, waiting for her to try to" << endl;
	cout << "catch them, then quickly swimming away before she could. It was as if they were" << endl;
	cout << "daring her to try to catch them, then laughing at her when she could not." << endl;
	cout << "    The young princess was now two years old, and had soft, blond hair and" << endl;
	cout << "beautiful blue eyes. She was the kind of child that when she entered a room and" << endl;
	cout << "smiled, it would figuratively light up. She was a happy and lovable child who" << endl;
	cout << "loved to socialize." << endl;
	cout << "    The princess seemed to love the sea horses' games and laughed at their" << endl;
	cout << "antics. She would keep trying to catch them, but for now, they were too fast" << endl;
	cout << "for her." << endl;
	cout << "    King Toran and Queen Demril were expecting another child soon. It was" << endl;
	cout << "expected to be a boy this time, and the king was very pleased. It would be his" << endl;
	cout << "job to raise the little prince properly - that is once he passed the toddler" << endl;
	cout << "stage. The queen would have the job of raising the princess to be proper and" << endl;
	cout << "respectful." << endl;
	cout << "    The prince, of course, would be heir to the Coshen throne. Once the king" << endl;
	cout << "passed on, the oldest prince would take the throne." << endl;
	cout << "    The king had volunteered to watch the little princess while the queen went" << endl;
	cout << "on a relaxing ride for a couple of hours. This pregnancy had been hard on her," << endl;
	system ("pause");
	system ("cls");
	cout << ct1 << "52\n" << endl;
	cout << "and the king noticed she seemed tired, and thought a change of scenery would be" << endl;
	cout << "good to help her relax. He made the suggestion to her, and told her he would" << endl;
	cout << "watch the princess." << endl;
	cout << "    The queen was pleasantly surprised at the offer, though a bit concerned" << endl;
	cout << "about the princess. The king had told her not to worry, and that he would take" << endl;
	cout << "care of everything. Reassured, the queen took the king's suggestion, and went" << endl;
	cout << "out for a nice relaxing ride." << endl;
	cout << "    The princess was not only cute, but was also very smart. At age two, she" << endl;
	cout << "could talk and swim circles around most children her age." << endl;
	cout << "    Coshen legend had told of a girl very much like the princess, which caused" << endl;
	cout << "some concern in the king. If the legends were true, which the king and most" << endl;
	cout << "Coshens doubted they were, Queen Demril was soon to die at the hands of some" << endl;
	cout << "sort of strange creatures." << endl;
	cout << "    Fish food! Thought the king, The legends are thousands of years old. If" << endl;
	cout << "Leanne were the one Demril would be dead already. This and the legends never" << endl;
	cout << "mention another child or that the queen was with child. Since we are expecting" << endl;
	cout << "a son soon, Leanne can't be the one. Anyway, no known single creature could" << endl;
	cout << "defeat four of my best-trained guards, at least not without Demril escaping." << endl;
	cout << "    Still, Leanne dose fit the description of the child in the legends. If" << endl;
	cout << "Leanne is the one, then my wife and unborn son will soon be killed. What" << endl;
	cout << "creature, besides a shark, could be so cold as to kill an expecting mother and" << endl;
	cout << "her child? That is, what creature that could get past four trained guards?" << endl;
	system ("pause");
	system ("cls");
	cout << ct1 << "53\n" << endl;
	cout << "    The legends told of a young girl that was beautiful and bright. She was to" << endl;
	cout << "be the envy of all others, but modest, kind and loving towards them. She would" << endl;
	cout << "be very curious and one to take serious risks to explore the unknown." << endl;
	cout << "    Some of this had already surfaced in Princess Leanne. She was born very" << endl;
	cout << "curious and was very observant. She was always watching everything, except when" << endl;
	cout << "she was playing, as she was at that time." << endl;
	cout << "    The legends also told of war and great destruction before the beautiful" << endl;
	cout << "queen's time. Princess Leanne was born at the end of the land-dweller's most" << endl;
	cout << "recent and severe war. The war was very harsh, and even Cosha felt it." << endl;
	cout << "    The land-dwellers had been fighting among themselves for centuries and the" << endl;
	cout << "last war they fought was the worst of them. Millions of land-dwellers had died," << endl;
	cout << "and many of their cities were turned into rubble. They finally had stopped" << endl;
	cout << "fighting and united before destroying themselves. They were now recovering" << endl;
	cout << "quite well, despite the amount of damage and loss of life." << endl;
	cout << "    There was still a lot of cleanup to do, even for Cosha. The chemicals and" << endl;
	cout << "broken vessels littered parts of Cosha, and the Coshens were putting a" << endl;
	cout << "considerable amount of resources into cleaning the immediate debris and" << endl;
	cout << "chemicals up. The rest of it would be cleaned in time by nature." << endl;
	cout << "    Cosha had stayed out of the war, as they had every land-dweller war. The" << endl;
	cout << "king figured it was not Cosha's business to get involved with the land" << endl;
	cout << "dweller's affairs." << endl;
	cout << "    The Coshens were used to having to clean up after the land-dwellers, and" << endl;
	system ("pause");
	system ("cls");
	cout << ct1 << "54\n" << endl;
	cout << "had devised ways of keeping Cosha clean from their messes." << endl;
	cout << "    Cosha was split in two parts. The inhabited part, or Cosha-Prime, and the" << endl;
	cout << "uninhabited part, more commonly referred to as Fiana. Cosha-Prime only took up" << endl;
	cout << "less than one-third of Loran's oceans, and Fiana was the rest of the claimed" << endl;
	cout << "territory of Cosha. The claim spread from south of the northern arctic region" << endl;
	cout << "to just north of the southern arctic region. Cosha-Prime was located around the" << endl;
	cout << "equatorial and tropical regions." << endl;
	cout << "    Things were well in Cosha. The people had prospered over the last few" << endl;
	cout << "centuries, and no serious contact had been made with the land-dwellers. The" << endl;
	cout << "only technical contact made was a few sightings of coshen women by land-dweller" << endl;
	cout << "fishermen, and that was long ago." << endl;
	cout << "    King Toran felt it was now time to make official contact with the land" << endl;
	cout << "dwellers. It was only a matter of time before the land-dwellers' technology" << endl;
	cout << "reached Cosha and contact was made anyway. King Toran felt the land-dwellers" << endl;
	cout << "were finally ready for contact, so he put together a party, which he himself" << endl;
	cout << "would lead. He preferred for Cosha to reach out and make peaceful contact than" << endl;
	cout << "the land-dwellers causing an incident and starting another war, or something" << endl;
	cout << "else go wrong. He would still have to worry about an incident, but the Coshens" << endl;
	cout << "had been monitoring and studying the land-dwellers for a few years now, so the" << endl;
	cout << "chances of an incident were minimal." << endl;
	cout << "    The king was relaxing while the princess played with the sea horses. He" << endl;
	cout << "felt she needed brothers and sisters to play with and relate to, and was happy" << endl;
	system ("pause");
	system ("cls");
	cout << ct1 << "55\n" << endl;
	cout << "she would soon be getting a little brother not much younger than she was." << endl;
	cout << "    The king would raise the boy to be a proper prince, while the queen raised" << endl;
	cout << "Leanne to be a proper princess. It had been this way for centuries. Naturally," << endl;
	cout << "the children would have tutors and servants when they were old enough and there" << endl;
	cout << "would be people to make sure the children followed through with their parents'" << endl;
	cout << "instructions." << endl;
	cout << "    The king had been watching the princess for a few hours now, and was" << endl;
	cout << "wondering why his queen had not yet returned." << endl;
	cout << "    She must have taken the scenic route, thought the king, At least she will" << endl;
	cout << "be well relaxed when she comes home. I just hope she took my suggestion and" << endl;
	cout << "pampered herself while she was at it." << endl;
	cout << "    The king was now watching the princess play with the seahorses when there" << endl;
	cout << "was a sudden and urgent knock at the hall doors." << endl;
	cout << "    Being alert, the sea horses swam away, and the princess went over to the" << endl;
	cout << "door. The king swam quickly to answer, so that the little princess would not" << endl;
	cout << "try to open it, not that she had the strength to, but it was better to be safe." << endl;
	cout << "    The king scooted the princess away from the door, and then opened it. There" << endl;
	cout << "was a Coshen top official two guards, and the chief guard awaiting him. When" << endl;
	cout << "they saw the king, they bowed in respect to him." << endl;
	cout << "    \"Your majesty,\" said the official." << endl;
	cout << "    \"Arise and enter,\" said the king." << endl;
	cout << "    The chief guard and official entered the throne hall with the chief of" << endl;
	system ("pause");
	system ("cls");
	cout << ct1 << "56\n" << endl;
	cout << "guards while the king went back to his throne. The other two guards followed," << endl;
	cout << "closing the door behind them." << endl;
	cout << "    \"What seems to be the matter?\" asked the king." << endl;
	cout << "    \"There has been an unfortunate incident,\" The official quietly said as he" << endl;
	cout << "handed the king a report, \"It involves Queen Demril, four guards, and what we" << endl;
	cout << "believe to be land-dwellers." << endl;
	cout << "    \"Queen Demril and three guards were found dead among her toppled rider and" << endl;
	cout << "one land-dweller. There was also what we believe could be land-dweller" << endl;
	cout << "equipment with them. The fourth guard is missing and presumed to be dead." << endl;
	cout << "    \"The equipment is currently being analyzed. However, by the time anyone" << endl;
	cout << "found the Queen and her party, it was already too late to save the unborn" << endl;
	cout << "child." << endl;
	cout << "    \"You have our deepest symphony over this incident and our condolences to" << endl;
	cout << "you and your daughter.\"" << endl;
	cout << "The king read the report. It said it all. Three guards and Queen Demril were" << endl;
	cout << "found dead along with one land-dweller. The fourth guard was missing, and the" << endl;
	cout << "land-dweller equipment that was found was being analyzed along with the rider." << endl;
	cout << "It was suspected that this was an unprovoked attack by the land-dwellers, but" << endl;
	cout << "there was not enough evidence to confirm or deny this theory. It also referred" << endl;
	cout << "to a possibility of some sort of explosive being used in the attack." << endl;
	cout << "    \"You may leave,\" said the king after reading the report." << endl;
	cout << "    The chief guard and top official left the large hall quietly, and the two" << endl;
	system ("pause");
	system ("cls");
	cout << ct1 << "57\n" << endl;
	cout << "guards that came with them followed, closing the door behind them." << endl;
	cout << "    The king was crushed. How could this happen? After all the precautions he" << endl;
	cout << "had made, she still died." << endl;
	cout << "    \"Daddy?\" Princess Leanne asked the king, \"Daddy? What's wrong?\"" << endl;
	cout << "    The king picked up the toddler princess, and hugged her." << endl;
	cout << "    \"Leanne,\" he said, trying to hide the pain the news brought him, \"my" << endl;
	cout << "precious little princess. You are so young.\"" << endl;
	cout << "    The king tried not to show too much sorrow to the princess so she would not" << endl;
	cout << "feel sad herself. He would tell her of this when she was older and could" << endl;
	cout << "understand. The princess was now all that was left of his family, and the king" << endl;
	cout << "knew he must do everything he could to keep her safe." << endl;
	cout << "    \"I'm two,\" said the princess, holding up two fingers, unaware of what had" << endl;
	cout << "happened to her mother." << endl;
	cout << "    \"That's right,\" said the king, trying to focus on the princess to hide the" << endl;
	cout << "sadness for the time, \"and in five days you will be three.\"" << endl;
	cout << "    The king did not want the princess to see him upset. He wanted the princess" << endl;
	cout << "to be happy. If she sensed that he was upset, it could cause her to be the" << endl;
	cout << "same." << endl;
	cout << "    \"Where's Mommy?\" asked the princess." << endl;
	cout << "    \"Well,\" responded King Toran, \"Mommy went for a nice ride.\"" << endl;
	cout << "    \"Is Mommy home yet?\" asked the princess." << endl;
	cout << "    \"No,\" said the king, \"mommy's not home. Mommy went out.\"" << endl;
	system ("pause");
	system ("cls");
	cout << ct1 << "58\n" << endl;
	cout << "    \"Is she coming home soon?\" asked the princess." << endl;
	cout << "    \"No,\" said the king, \"Mommy's not coming home.\"" << endl;
	cout << "    \"Why?\" asked the princess." << endl;
	cout << "    \"Well,\" said the king, \"these bad people came and hurt your mommy while she" << endl;
	cout << "was out. They hurt her really bad, so now mommy's in a better place.\"" << endl;
	cout << "    \"Where'd mommy go?\" asked the princess." << endl;
	cout << "    \"It's a bit hard to explain,\" said the king, realizing that he had no" << endl;
	cout << "choice but to try to explain what had happened to his daughter, \"Your mother is" << endl;
	cout << "not with us anymore and can't be with us because of what the bad people did." << endl;
	cout << "She and your brother aren't coming home anymore, but you will still have me," << endl;
	cout << "and I will always be here for you.\"" << endl;
	cout << "    \"Where did baby go?\" asked the princess." << endl;
	cout << "    \"He went with your mommy,\" said the king." << endl;
	cout << "    \"Why?\"" << endl;
	cout << "    \"When the bad people hurt your mommy,\" said the king, \"They hurt your baby" << endl;
	cout << "brother too, so he and you mom left together.\"" << endl;
	cout << "    \"Why the bad people hurt mommy and baby?\" asked the princess, becoming" << endl;
	cout << "upset." << endl;
	cout << "    \"That's what bad people do,\" said the king, \"They hurt people and don't" << endl;
	cout << "care about it. Now why don't you go and play, daddy has to do some things to" << endl;
	cout << "make the bad people stay away.\"" << endl;
	cout << "    \"Whatcha going to do?\" asked the princess." << endl;
	system ("pause");
	system ("cls");
	cout << ct1 << "59\n" << endl;
	cout << "    \"Well,\" said the king, \"I have a lot of power behind this throne, and I'm" << endl;
	cout << "going to use it to make sure that the bad people can't hurt you too. It's bad" << endl;
	cout << "enough they did what they did. I want you and everyone else to be safe, so now" << endl;
	cout << "I have to make sure they stay away. Now why don't you go and play, daddy has a" << endl;
	cout << "lot of thinking and planning to do.\"" << endl;
	cout << "    \"Okay...\" the little princess said sadly, and unable to express verbally" << endl;
	cout << "how she felt." << endl;
	cout << "    Though sad inside, the little princess felt relieved at the same time. She" << endl;
	cout << "knew the tome in her father's voice. Although sad, he seemed determined, and" << endl;
	cout << "that comforted the princess." << endl;
	cout << "    The princess got down and went off to play. Though she did not feel much" << endl;
	cout << "like playing, she did not want her father to see it." << endl;
	cout << "    The king immediately ordered a full investigation. The investigation came" << endl;
	cout << "back inconclusive, and left two theories. Either the land-dwellers attacked the" << endl;
	cout << "guards and the queen, or they too were attacked with the rest. There was no" << endl;
	cout << "evidence of there being any more than one land-dweller, and an autopsy showed" << endl;
	cout << "the land-dweller died about ten minutes after the queen. The investigation" << endl;
	cout << "showed there was definitely a struggle of some sort, but with all the other" << endl;
	cout << "markings, and the ocean movement covering some; it was difficult to determine" << endl;
	cout << "what exactly had taken place." << endl;
	cout << "    Although the investigation and autopsy were inconclusive, the king blamed" << endl;
	cout << "the land-dwellers for the deaths of the queen, his son, and the guards. A land" << endl;
	system ("pause");
	system ("cls");
	cout << ct1 << "60\n" << endl;
	cout << "dweller and his equipment were found next to the queen and the dead guards, and" << endl;
	cout << "the land-dwellers were known to be violent. This was enough evidence for the" << endl;
	cout << "king." << endl;
	cout << "    The funeral for the queen and unborn prince was held two days later, and" << endl;
	cout << "all of Cosha grieved for the loss. The king would never forgive the land" << endl;
	cout << "dwellers for the death of his wife and unborn son.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" << endl;
	system ("pause");
	menu();
	return 0;
}
