#include <iostream>
#include <string>
#include "menu.h"

using namespace std;

int c_seven()
{
	string ct7 = "The Princess    -    Chapter VII    -    Page ";

	system ("cls");
	cout << "The Princess    -    Chapter Seven    -    Page 99\n" << endl;
	cout << "Princess Leanne woke up from a night's sleep, sat up, and stretched. She still" << endl;
	cout << "felt like a prisoner, and wondered when she was going to be 'freed' from her" << endl;
	cout << "'prison'. She saw it that way because she felt her father had treated her like" << endl;
	cout << "a criminal." << endl;
	cout << "    It had been a little over two months since her father set the punishment" << endl;
	cout << "upon her. Since she technically was not an adult, and would not be one for a" << endl;
	cout << "couple of days, her father could still tell her what to do, and when to do it." << endl;
	cout << "This and he was king, which meant that he could technically always tell her" << endl;
	cout << "what to do. As princess, though, she did have certain rights and privileges, so" << endl;
	cout << "there was always some leeway and exceptions." << endl;
	cout << "    Her birthday was in not more than a week away, and her presentation would" << endl;
	cout << "be on that day. The ceremony would publicly announce her adulthood and future" << endl;
	cout << "inheritance of the throne, not to mention also make her eligible for marriage." << endl;
	cout << "Since there was no prince's and she was the oldest, being an only child, the" << endl;
	cout << "princess would inherit the throne when her father passed on." << endl;
	cout << "    The princess had already made some preparations before she got into trouble" << endl;
	cout << "with her father. Since then, she had done what rehearsing she could in her" << endl;
	cout << "chambers. Her friend and personal servant, Monia, had been helping with" << endl;
	cout << "suggestions, guidance, and constructive criticism, not to mention lots of" << endl;
	cout << "encouragement. At the time of the punishment, Monia had been relieved from" << endl;
	cout << "Leanne, and a different servant was assigned. The new servant was more of a" << endl;
	cout << "general servant, and not a personal one. This did not stop the princess from" << endl;
	system ("pause");
	system ("cls");
	cout << ct7 << "100\n" << endl;
	cout << "summoning Monia to help with her presentation. The presentation had to be just" << endl;
	cout << "right. It was, after all, a major milestone in the princess's life." << endl;
	cout << "    The princess was about to get out of bed when there was a knock at her" << endl;
	cout << "bedroom door." << endl;
	cout << "    The princess got up while a guard and the king entered." << endl;
	cout << "    \"Daddy,\" said the princess, a bit surprised, \"What are you doing here?\"" << endl;
	cout << "    \"I've come here to see if you've learned anything from your punishment,\"" << endl;
	cout << "said the king." << endl;
	cout << "    \"Yes I have,\" said the princess, \"I've learned that even though I'm the" << endl;
	cout << "princess of Cosha, it doesn't entitle me to special treatment. I've learned" << endl;
	cout << "that your rules and law are very stringent. I've learned just how harsh you can" << endl;
	cout << "really be. I've learned the true meaning of boredom, and I've learned there are" << endl;
	cout << "three-hundred and twenty-seven unique notches in this ceiling.\"" << endl;
	cout << "    \"I see you haven't forgotten about your sense of humor,\" said the king," << endl;
	cout << "\"Well, anyway, you're almost twenty years old, now, which means you are almost" << endl;
	cout << "an adult. This and you need to finish preparing for your presentation. It's" << endl;
	cout << "going to be a big week for you, and you should be well prepared, so I'm" << endl;
	cout << "revoking your punishment. You have all your privileges and freedoms back, and" << endl;
	cout << "are no longer restricted to your chambers. However, I never want you to visit" << endl;
	cout << "land or even surface again. If I hear of such a thing, I will be much more" << endl;
	cout << "upset than I was this time.\"" << endl;
	cout << "    \"Yes, daddy,\" said the princess, \"I'm sorry about what I did, but I don't" << endl;
	system ("pause");
	system ("cls");
	cout << ct7 << "101\n" << endl;
	cout << "think I did any harm.\"" << endl;
	cout << "    \"Surfacing alone can be harmful,\" said the king, \"If one of those" << endl;
	cout << "land-dwellers see you, they won't stop until they capture you so they can" << endl;
	cout << "examine you like a specimen. Surfacing alone is forbidden. Never do it again.\"" << endl;
	cout << "    \"Okay,\" said the princess, half-heartedly." << endl;
	cout << "    \"Good,\" said the king, \"Have you thought of what you are going to do for" << endl;
	cout << "your presentation?\"" << endl;
	cout << "    \"Yes I have,\" said the princess, \"I've been practicing it too. When is the" << endl;
	cout << "first rehearsal?\"" << endl;
	cout << "    \"In three days,\" said the king, \"the day after your birthday.\"" << endl;
	cout << "    \"Great,\" said the princess, \"I'll show you the routine then. You're going" << endl;
	cout << "to love it.\"" << endl;
	cout << "    \"I look forward to it,\" said the king, \"Now, why don't you get dressed." << endl;
	cout << "I'll have your servants back at your disposal within the hour.\"" << endl;
	cout << "    \"Thanks,\" said the princess." << endl;
	cout << "    The king left the princess's chambers to allow her to get dressed." << endl;
	cout << "    It felt good to the princess to be free again, but she was still bitter" << endl;
	cout << "towards her father for destroying her collection and embarrassing her in the" << endl;
	cout << "open halls, though the embarrassment was mostly forgotten about. The princess" << endl;
	cout << "felt because she was the princess of Cosha, she should be entitled to special" << endl;
	cout << "rights and privileges above that of the common people." << endl;
	cout << "    When I'm queen, thought the princess to herself, and I have children of my" << endl;
	system ("pause");
	system ("cls");
	cout << ct7 << "102\n" << endl;
	cout << "own, they will be allowed to surface, that is, providing they take at least two" << endl;
	cout << "guards with them for safety. Daddy's right about one thing; it can be a bit" << endl;
	cout << "dangerous." << endl;
	cout << "    The princess went over to her dresser, took off her nightgown, and then" << endl;
	cout << "tossed it on her bed. She opened the top drawer where her tops were stored then" << endl;
	cout << "chose a white one and put it on. Afterwards, she decided to go for a long swim," << endl;
	cout << "since it had been over two months since she even saw the outside of her" << endl;
	cout << "chambers. Eager to go out, she took her tiara off the top of her dresser, put" << endl;
	cout << "it on, and left her chambers. It would be good to see the ocean again." << endl;
	cout << "    \"Your heinous,\" came a male voice as soon as the princess left her" << endl;
	cout << "chambers." << endl;
	cout << "    She turned to see a coshen official approaching her. The princess stopped" << endl;
	cout << "to let him catch up." << endl;
	cout << "    \"Wil,\" said the princess, happy to see a friendly face." << endl;
	cout << "    Wil Canton was a top official. His job was to coordinate and notify senior" << endl;
	cout << "royal members of new or changed laws. He was also the one who made the laws the" << endl;
	cout << "king made or changed official, and sometimes he acted as a messenger between" << endl;
	cout << "important royal members." << endl;
	cout << "    He was thirty-two years old, five feet and ten inches tall with a medium" << endl;
	cout << "build. He had brown eyes and short brown hair." << endl;
	cout << "    \"There is a meeting tomorrow,\" said Wil, \"to discuss the situation of the" << endl;
	cout << "land-dwellers, and the king wishes you to attend.\"" << endl;
	system ("pause");
	system ("cls");
	cout << ct7 << "103\n" << endl;
	cout << "    \"What time?\" asked the princess." << endl;
	cout << "    \"The eleventh hour,\" responded Wil, \"In the strategy room.\"" << endl;
	cout << "    \"The strategy room?\" asked the princess, a bit surprised, \"Is my father" << endl;
	cout << "planning to go to war?\"" << endl;
	cout << "    \"Not that I know of,\" said Wil, \"It's probably being held there due to the" << endl;
	cout << "renovations to the conference room.\"" << endl;
	cout << "    \"Of course,\" said the princess, as if it were obvious, \"Tell my father I'll" << endl;
	cout << "be attending the meeting.\"" << endl;
	cout << "    \"I'll let him know,\" said Wil, then swam off down the hall." << endl;
	cout << "    He's cute, thought the princess, then immediately thought, What am I" << endl;
	cout << "thinking? He's more than ten years older than me." << endl;
	cout << "    With that out of her mind, the princess went for her swim.\n\n" << endl;
	cout << "    The princess's birthday celebration was spectacular. It was her twentieth" << endl;
	cout << "birthday and her passage into adulthood. She was able to invite whomever she" << endl;
	cout << "pleased, and no expense was spared. The presentation to symbolize her being the" << endl;
	cout << "now official heiress to the throne, not to mention eligible for marriage, was" << endl;
	cout << "even more spectacular. The princess's own presentation was breathtaking, and" << endl;
	cout << "everyone thought she was radiant. She was now twenty years old, official" << endl;
	cout << "heiress to the Coshen throne, and fully eligible for marriage." << endl;
	cout << "    And so time passed, and as it did, the urge to return to land ate at" << endl;
	system ("pause");
	system ("cls");
	cout << ct7 << "104\n" << endl;
	cout << "Princess Leanne more and more each day. She tried to ignore it. She tried" << endl;
	cout << "distractions, busying herself with tasks, and anything else she could think of," << endl;
	cout << "but the urge only persisted and continued to grow." << endl;
	cout << "    Three months had passed since the princess's presentation. The urge to go" << endl;
	cout << "back to land was now becoming overwhelming. The princess knew she would have no" << endl;
	cout << "choice but to go back somehow. Even though she had made a promise to her father" << endl;
	cout << "never to return, she had to go there, someway, somehow." << endl;
	cout << "    She finally gave in to the overwhelming urge, and decided to leave the" << endl;
	cout << "castle quietly, and alone, so that no one would know she was gone, or where she" << endl;
	cout << "was heading. The less people that knew about what she was doing, the less" << endl;
	cout << "problems she would have." << endl;
	cout << "    The princess was about to leave the castle when her friend and personal" << endl;
	cout << "servant Monia stopped her." << endl;
	cout << "    \"Princess Leanne,\" Monia called to get the princess's attention." << endl;
	cout << "    The princess stopped to see Monia swimming toward her." << endl;
	cout << "    \"Where are you going?\" asked Monia, when she reached the princess." << endl;
	cout << "    It was unusual for any royal member to leave without their personal" << endl;
	cout << "servant, so Monia was naturally curious when she saw the princess leaving" << endl;
	cout << "alone." << endl;
	cout << "    \"Uh, nowhere,\" said the princess." << endl;
	cout << "    \"Then why where you about to leave the castle alone?\" asked Monia, then" << endl;
	cout << "said, \"I didn't think you were supposed to leave without at least taking your" << endl;
	system ("pause");
	system ("cls");
	cout << ct7 << "105\n" << endl;
	cout << "personal servant. Besides, you don't usually leave without notice.\"" << endl;
	cout << "    Princess Leanne took a moment to think. If she told Monia where she was" << endl;
	cout << "going and swore her to silence, she could take her where she was going. It" << endl;
	cout << "could turn out to be a fun, new, and educational experience for Monia. Besides," << endl;
	cout << "Princess Leanne was an adult and the princess of Cosha; it would be" << endl;
	cout << "inappropriate to leave without her personal servant." << endl;
	cout << "    Since she was the princess of Cosha, she figured she should be able to go" << endl;
	cout << "wherever she pleased, and take whomever she wanted. Not only that, but she felt" << endl;
	cout << "she was perfectly capable of taking care of herself." << endl;
	cout << "    On the other hand, she thought, if I bring Monia with me, and by some" << endl;
	cout << "unfortunate and remote chance something did happen, she could at least go and" << endl;
	cout << "tell my father." << endl;
	cout << "    \"Can you keep a secret?\" the princess asked Monia." << endl;
	cout << "    \"Of course,\" said Monia." << endl;
	cout << "    \"Good,\" said the princess, \"What I'm about to tell you must never be" << endl;
	cout << "repeated to anyone, especially my father.\"" << endl;
	cout << "    Monia held up her left hand and said in a serious tone, \"I, Monia Minerva" << endl;
	cout << "Tranko, daughter of Johab Tranko; daughter of Minerva Tranko; do solemnly swear" << endl;
	cout << "that the information about to be presented to me by Princess Leanne; Princess" << endl;
	cout << "of all Cosha; Daughter of King Toran; Daughter of the late Queen Demril; shall" << endl;
	cout << "never be revealed, except for such cases as it may save the princess's life.\"" << endl;
	cout << "    \"Okay...\" said the princess, having been taken off guard by Monia's unusual" << endl;
	system ("pause");
	system ("cls");
	cout << ct7 << "106\n" << endl;
	cout << "oath, I'll take that as an 'I swear'. I didn't expect a full official oath, but" << endl;
	cout << "it'll do. It was quite different.\"" << endl;
	cout << "    \"Thank you,\" said Monia, \"And I meant every word of it. Now, what's the big" << endl;
	cout << "secret?\"" << endl;
	cout << "    \"Follow me,\" said the princess, \"I want to make sure no one else hears" << endl;
	cout << "this.\"" << endl;
	cout << "    The princess led Monia out of the castle and through the garden. They swam" << endl;
	cout << "past the underwater arrangement of beautiful plants until the princess was sure" << endl;
	cout << "they were away from anyone that might overhear their conversation." << endl;
	cout << "    \"Okay,\" said the princess, turning to Monia, \"Actually, there are a number" << endl;
	cout << "of related secrets, but no one else can ever know about them.\"" << endl;
	cout << "    \"Hey,\" said Monia, \"I made an oath, remember?\"" << endl;
	cout << "    \"Right,\" said the princess, \"There's this beach I've been visiting for" << endl;
	cout << "quite some time now. It's very beautiful, abandoned, and full of land-dweller's" << endl;
	cout << "stuff. It's kind of like finding treasure.\"" << endl;
	cout << "    \"Where's this beach?\" asked Monia." << endl;
	cout << "    Almost immediately, Monia realized that beaches were above the water, and" << endl;
	cout << "usually were land." << endl;
	cout << "    \"Wait a second,\" said Monia, \"Isn't going to land totally forbidden?\"" << endl;
	cout << "    \"Technically, yes,\" said the princess, \"but you're with me, so there's" << endl;
	cout << "nothing for you to worry about. Besides, I have a strange need to go. I don't" << endl;
	cout << "understand it, but I want to find out why.\"" << endl;
	system ("pause");
	system ("cls");
	cout << ct7 << "107\n" << endl;
	cout << "    \"Wow...\" said Monia, \"That's really different. How do you move around on" << endl;
	cout << "land? It must be very difficult.\"" << endl;
	cout << "    \"Not anymore,\" said the princess, \"Once I got used to my legs, it was just" << endl;
	cout << "a matter of practice.\"" << endl;
	cout << "    \"Legs?\" asked Monia, \"What are those?\"" << endl;
	cout << "    \"You know how we have fins?\" asked the princess, \"Well, the land dwellers" << endl;
	cout << "have two long limbs that bend in the middle, called legs. It's how they get" << endl;
	cout << "around.\"" << endl;
	cout << "    \"Right!\" said Monia as if she just remembered something she had learned" << endl;
	cout << "long ago, \"I remember now, they taught us that when I was in school. The land-" << endl;
	cout << "dwellers have legs and feet, instead of fins. How did you get legs?\"" << endl;
	cout << "    \"I've taught myself the transformation,\" said the princess." << endl;
	cout << "    \"The transformation?\" asked Monia, both not quite believing the princess," << endl;
	cout << "and surprised, \"I thought that was just a fish-tale.\"" << endl;
	cout << "    \"Nah,\" said the princess, \"That's just what they tell you so people don't" << endl;
	cout << "try to figure it out. What they don't realize is that sometimes someone finds" << endl;
	cout << "out by accident. Like me. Come on, follow me and I'll show you exactly what I" << endl;
	cout << "mean.\"" << endl;
	cout << "    The princess swam off and Monia followed close behind her. The two swam" << endl;
	cout << "deep into what the Coshens referred to as Fiana, or the wilderness. Fiana was" << endl;
	cout << "also the uninhabited parts of Cosha, at least by Coshens anyway. When they got" << endl;
	cout << "close to Ashton beach, the princess stopped." << endl;
	system ("pause");
	system ("cls");
	cout << ct7 << "108\n" << endl;
	cout << "    \"Wait here,\" said the princess to Monia, \"I'm going to surface and check" << endl;
	cout << "for land-dwellers.\"" << endl;
	cout << "    Monia gave the princess a concerned look." << endl;
	cout << "    \"It's okay,\" said the princess, reassuring Monia, \"I used to do this all of" << endl;
	cout << "the time.\"" << endl;
	cout << "    \"Be careful,\" said Monia." << endl;
	cout << "    The princess surfaced, then took a good look around to make sure there were" << endl;
	cout << "no land-dwellers. Seeing there were none, she took one more careful look" << endl;
	cout << "around, and assured there were none, she swam down to where Monia was waiting." << endl;
	cout << "    \"It's all clear,\" said the princess to Monia." << endl;
	cout << "    The princess and Monia swam as close to shore as Monia could safely go." << endl;
	cout << "    \"Did you know,\" said the princess, \"That when you surface you can breathe" << endl;
	cout << "in the air?\"" << endl;
	cout << "    \"I've heard that,\" said Monia, \"But that too, has been dismissed as rumor.\"" << endl;
	cout << "    \"Well, it's true,\" said the princess, \"and I've done some studies. We can" << endl;
	cout << "breathe air, but only for a couple of hours. Want to try it?\"" << endl;
	cout << "    \"Why not?\" said Monia, not entirely sure." << endl;
	cout << "    The princess and Monia surfaced, and Monia took a breath. She started" << endl;
	cout << "coughing, unaccustomed to the strange sensation of her lungs changing to take" << endl;
	cout << "in air instead of seawater." << endl;
	cout << "    \"Oh, ya,\" said the princess, \"I should have warned you about that.\"" << endl;
	cout << "    Monia tried to say something, but all that came out was a strange, screechy" << endl;
	system ("pause");
	system ("cls");
	cout << ct7 << "109\n" << endl;
	cout << "noise." << endl;
	cout << "    \"You have to talk a different way,\" said the princess, \"since we're not"<< endl;
	cout << "under water. The air has different physics than the water. Here, let me show" << endl;
	cout << "you.\"" << endl;
	cout << "    The princess then started to teach Monia how to use the air to talk." << endl;
	cout << "    \"Wow! This is real different,\" said Monia after she caught on, \"Everything" << endl;
	cout << "here is so beautiful,\" she continued, taking in the scenery, \"The sky is so" << endl;
	cout << "blue, and the beach is so quiet.\"" << endl;
	cout << "    \"Isn't it?\" asked the princess, \"Look Monia, don't stay surfaced for more" << endl;
	cout << "than a few minutes. The sun is hot today and it can burn you. Believe me, you" << endl;
	cout << "don't want to know what that's like, so be careful.\"" << endl;
	cout << "    \"Thanks for telling me,\" said Monia \"I'll be careful.\"" << endl;
	cout << "    \"That's just the first few times you surface,\" said the princes, \"As you" << endl;
	cout << "surface mare and more, you'll get used to the sun, and can stay surfaced" << endl;
	cout << "longer." << endl;
	cout << "    \"Also remember that we are in Fiana, so there might be sharks nearby. I've" << endl;
	cout << "never seen any, but be aware anyhow. Even if a shark does come by I don't think" << endl;
	cout << "we'll have any trouble outrunning it.\"" << endl;
	cout << "    \"Are you joking?\" asked Monia, \"I happen to be an excellent summer, it runs" << endl;
	cout << "in my family.\"" << endl;
	cout << "    \"Nice,\" said the princes, \"then we have nothing to worry about.\"" << endl;
	cout << "    \"Not a thing,\" said Monia, \"This is very beautiful. I don't understand why"<< endl;
	system ("pause");
	system ("cls");
	cout << ct7 << "110\n" << endl;
	cout << "the king forbids it.\"" << endl;
	cout << "    \"It has something to do with the land-dwellers,\" said the princess, \"and my" << endl;
	cout << "father won't discuss the subject. That's all I know.\"" << endl;
	cout << "    \"Oh,\" said Monia, \"how unfortunate.\"" << endl;
	cout << "    \"Hey,\" said the princes, \"watch this.\"" << endl;
	cout << "    The princes dove in the water, jumped about, and dove in a few times. She" << endl;
	cout << "rode a couple of waves part way and splashed Monia a bit. The princess was" << endl;
	cout << "careful not to get too close to shore. Doing so could have made it very" << endl;
	cout << "difficult for her to get back without using the transformation." << endl;
	cout << "    \"This is so much fun,\" said Monia, \"It's no wonder you come here. It's too" << endl;
	cout << "bad it's forbidden, though. If his majesty is worried about land-dwellers," << endl;
	cout << "can't we just dive in the water and out swim them?\"" << endl;
	cout << "    The princess and her personal servant were out in the deeper waters and had" << endl;
	cout << "surfaced again. Monia was still quite taken in by the peaceful scenery." << endl;
	cout << "    \"True,\" said the princess, \"We'll be alright as long as my father doesn't" << endl;
	cout << "find out about this. Anyway, I'm the princess of Cosha. What's the point of" << endl;
	cout << "being princess if I don't have special rights and privileges?\"" << endl;
	cout << "    \"Good point,\" said Monia, \"So, when are you going to show me the" << endl;
	cout << "transformation? I'm dying to see it.\"" << endl;
	cout << "    \"Right now,\" said the princess." << endl;
	cout << "    The princess swam to the shallow waters, then used the transformation." << endl;
	cout << "Within four or five seconds, her body's cells had reorganized themselves and" << endl;
	system ("pause");
	system ("cls");
	cout << ct7 << "111\n" << endl;
	cout << "transformed her to loran form." << endl;
	cout << "    \"Wow,\" said Monia, \"that was amazing. How did you do that?\"" << endl;
	cout << "    \"I'll have to teach you that another time,\" said the princess." << endl;
	cout << "    \"Oh,\" said Monia, a bit disappointed, \"When do you think we'll be coming" << endl;
	cout << "back?\"" << endl;
	cout << "    \"I'm not sure,\" said the princess, \"Hopefully within a couple of days from" << endl;
	cout << "now. You know, this isn't the only reason I come here.\"" << endl;
	cout << "    \"What do you mean?\" asked Monia." << endl;
	cout << "    \"I'll show you,\" said the princess, \"Stay here. I'll be back with" << endl;
	cout << "something... unusual.\"" << endl;
	cout << "    \"Uh... okay,\" said Monia, unsure of the situation." << endl;
	cout << "    \"Don't fret,\" said the princess, \"I'll be fine.\"" << endl;
	cout << "    The princess walked to the sands and started looking for a loran item to" << endl;
	cout << "show Monia. She was half-naked and completely confident nothing would happen to" << endl;
	cout << "her or Monia.\n\n\n\n\n\n\n" << endl;
	system ("pause");
	menu();
	return 0;
}
