#include <iostream>
#include <string>
#include "menu.h"

using namespace std;

int c_three()
{
	string ct3 = "The Princess    -    Chapter III    -    Page ";

	system ("cls");
	cout << "The Princess    -    Chapter Three    -    Page 73\n" << endl;
	cout << "Princess Leanne quickly swam back to Cosha-Prime. She had been to that beach" << endl;
	cout << "many times before, though her father forbade it. She did not know the reason" << endl;
	cout << "that land was forbidden, all she knew was she had an overwhelming need to go" << endl;
	cout << "there." << endl;
	cout << "    It was forbidden to even surface, never mind go on land. In fact, the" << endl;
	cout << "transformation itself was forbidden. All Princess Leanne knew was that her" << endl;
	cout << "mother's death had something to do with it. Her mother had died when she was" << endl;
	cout << "very young. An investigation had been ordered, and since then, it was forbidden" << endl;
	cout << "to do such things." << endl;
	cout << "    The princess's father, King Toran, had become angry and distant since the" << endl;
	cout << "queen's death. He was angry at the land-dwellers, almost as if he had some sort" << endl;
	cout << "of vendetta against them. The king had also become distant from the princess," << endl;
	cout << "which made relations between the two difficult." << endl;
	cout << "    The king had to find someone to teach the little princess to be a proper" << endl;
	cout << "princess, and he had taught her what he could. To Princess Leanne, her father's" << endl;
	cout << "teachings were more like 'Do this', or 'Do that', or 'Don't do this or that'." << endl;
	cout << "Basically, he taught her the laws and rules of being royalty." << endl;
	cout << "    Visiting the beach was one 'don't' that the princess felt compelled to" << endl;
	cout << "'do'. She had been visiting that particular beach for almost two years, and" << endl;
	cout << "that was the first time she ever saw any land-dwellers there. In fact, that was" << endl;
	cout << "the first time she had seen land-dwellers in real life, ever. She had seen" << endl;
	cout << "drawings and sketches of them, but never actually got to see them like that." << endl;
	system ("pause");
	system ("cls");
	cout << ct3 << "74\n" << endl;
	cout << "The experience was both frightening and awe provoking. It also got her" << endl;
	cout << "curiosity going. Now that she had actually seen one of the land-dwellers, she" << endl;
	cout << "wanted even more now than ever to learn more about them." << endl;
	cout << "    The princess was now concerned that the land-dwellers were going to use the" << endl;
	cout << "beach for themselves. If this were to happen, she would no longer be able to" << endl;
	cout << "visit it. On the other hand, it may have been just a one-time incident. She" << endl;
	cout << "decided she would carefully check the next day. If the land-dwellers did not" << endl;
	cout << "show up, it just meant it was a one-time thing. If they did show up, she would" << endl;
	cout << "have to find another beach." << endl;
	cout << "    The princess had been visiting the beach for various reasons. The beach" << endl;
	cout << "gave the princess a sense of inner peace, serenity, and belonging. She felt she" << endl;
	cout << "belong to Cosha, though not in the palace, and she felt she also belonged at" << endl;
	cout << "the beach." << endl;
	cout << "    The beach was peaceful and had been deserted before the princess was born." << endl;
	cout << "The land-dwellers had abandoned the beach because of something that happened" << endl;
	cout << "during a war, and since then, the land-dwellers had been using it as a salvage" << endl;
	cout << "dumping area." << endl;
	cout << "    The princess had heard about the land-dweller's war. Apparently, the land" << endl;
	cout << "dwellers fought fiercely over the planet's resources. So fiercely, in fact," << endl;
	cout << "that they almost destroyed themselves. Fortunately, for them, they stopped" << endl;
	cout << "fighting and united. Cosha, on the other hand, had been united for centuries." << endl;
	cout << "    The Coshens had an ability that had been forbidden for almost a hundred" << endl;
	system ("pause");
	system ("cls");
	cout << ct3 << "75\n" << endl;
	cout << "years. The Coshens could 'transform' their bodies between coshen and loran" << endl;
	cout << "form. This transformation was accomplished through cellular reorganization." << endl;
	cout << "Certain cells throughout the coshen body had the ability to reorganize into" << endl;
	cout << "either form. An extra organ in the body would release a chemical, on command," << endl;
	cout << "which these cells responded to, causing the coshen to change into the other" << endl;
	cout << "form." << endl;
	cout << "    The technique had not been taught for several generations, and except for a" << endl;
	cout << "few rare Coshens that accidentally discovered it, most did not know about the" << endl;
	cout << "ability. Princess Leanne was one of the few that had discovered it, and used it" << endl;
	cout << "when she went to the beach." << endl;
	cout << "    The transformation was still heard of, but taught primarily as myth and" << endl;
	cout << "legend, and as a medical throwback. Those who were found having discovered the" << endl;
	cout << "ability, were usually forced to undergo surgery to have the extra organ" << endl;
	cout << "removed. The princess, however, could not be forced to undergo such a" << endl;
	cout << "procedure, so she was still able to use the transformation. This and the king" << endl;
	cout << "decided it might be of use someday." << endl;
	cout << "    As special as this transformation was, it did have its drawbacks. While in" << endl;
	cout << "loran form, it was possible to drown if one did not transform back in time." << endl;
	cout << "When the transformation was complete, one of course, would be naked from the" << endl;
	cout << "waist down, so it would be recommended to bring some cover. The transformation" << endl;
	cout << "was also painful for some Coshens, though it was never known why." << endl;
	cout << "    The Coshens had the ability to breathe air for a time while in coshen form," << endl;
	system ("pause");
	system ("cls");
	cout << ct3 << "76\n" << endl;
	cout << "before they were forced to go under water again. In loran form, water could not" << endl;
	cout << "be breathed at all." << endl;
	cout << "    The princess thought the price of the transformation was small compared to" << endl;
	cout << "the benefits. It was painless for her, though a bit uncomfortable, and the" << endl;
	cout << "beach had been deserted, so she did not have to worry about covering herself" << endl;
	cout << "up. She had a plan if she were to interact with the land-dwellers. Wear a long" << endl;
	cout << "shirt or a slim dress. This would provide mobility and cover." << endl;
	cout << "    Princess Leanne was a five foot, four inch Coshen with long, wavy, blond" << endl;
	cout << "hair and sea-blue eyes. She was an only child and had been educated in many" << endl;
	cout << "subjects. She had also been prepared to fulfill some sort of legend or destiny" << endl;
	cout << "about joining words or some sort of nonsense. That is what she and the general" << endl;
	cout << "population thought about it anyway." << endl;
	cout << "    It was presumed that because the legends were written over a thousand years" << endl;
	cout << "ago, that they were either not true, or already fulfilled. It was also thought" << endl;
	cout << "that they were made by religious and superstitious people of that time." << endl;
	cout << "    The facts remained though. Princess Leanne fit the description of the young" << endl;
	cout << "queen described in the legends, and her mother had been killed, as the legends" << endl;
	cout << "predicted. There was a period of war, at least for the land-dwellers, and now" << endl;
	cout << "the entire world seemed at peace. The unspecified destruction to Cosha had not" << endl;
	cout << "taken place, but the former queen was killed by what could have been" << endl;
	cout << "interpreted as 'strange creatures'." << endl;
	cout << "    The princess was almost in Cosha-Prime. She swam past its outer border," << endl;
	system ("pause");
	system ("cls");
	cout << ct3 << "77\n" << endl;
	cout << "marked by a series of sunken ships and chasms. She assured herself that things" << endl;
	cout << "would be okay the next day. She had figured that it was just coincidental that" << endl;
	cout << "the land-dwellers just happened to show up that day, but she still would have" << endl;
	cout << "to be careful the next time she visited, just in case.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" << endl;
	system ("pause");
	menu();
	return 0;
}
