#include <iostream>
#include <string>
#include "menua.h"

using namespace std;

int c_twenty()
{
	string ct20 = "The Princess    -    Chapter XX    -    Page ";

	system ("cls");
	cout << "The Princess    -    Chapter Twenty    -    Page 177\n" << endl;
	cout << "The king immediately ordered the Coshen military to train troops to use the" << endl;
	cout << "previously forbidden transformation." << endl;
	cout << "    \"Father,\" said the princess, \"I thought the transformation was forbidden.\"" << endl;
	cout << "    \"This is war Leanne,\" said the king, \"I have to make exceptions. These" << endl;
	cout << "creatures live on land and since we can adapt to land and sea, our military" << endl;
	cout << "must be trained for both.\"" << endl;
	cout << "    \"I see,\" said the princess, \"but wouldn't a peaceful approach be more" << endl;
	cout << "beneficial?" << endl;
	cout << "    \"After all they've done?\" asked the king, as if the princess had asked a" << endl;
	cout << "forbidden question, \"First, they murder your mother, then they sabotage contact" << endl;
	cout << "efforts, then they seduce, kidnap, and perform studies on you like some" << endl;
	cout << "experiment. For all you know, they were going to kill you.\"" << endl;
	cout << "    The princess's eyes grew wide with revelation, shock, and pain." << endl;
	cout << "    \"No,\" the king continued, \"The land creatures must be taught Cosha will not" << endl;
	cout << "stand for this. We will retaliate.\"" << endl;
	cout << "    \"Why didn't you tell me?\" asked the princess." << endl;
	cout << "    \"I figured you already knew,\" said the king, not noticing his daughter's" << endl;
	cout << "tone of voice, \"Maybe it was too obvious.\"" << endl;
	cout << "    \"Too obvious?\" said the princess, clearly upset, \"You wouldn't even speak" << endl;
	cout << "of her! All you ever told me is Mom died when I was two!\"" << endl;
	cout << "    The king looked at the princess a bit confused." << endl;
	cout << "    \"I beg your pardon ?\" he asked." << endl;
	system ("pause");
	system("cls");
	cout << ct20 << "178\n" << endl;
	cout << "    \"When I tried to talk to you,you always would dismiss me,you were too busy," << endl;
	cout << "or you would just shut me up! I never even knew what she was like! I always" << endl;
	cout << "thought she died peacefully, and now you tell me she was murdered?\"" << endl;
	cout << "    The king paused for a long moment before speaking." << endl;
	cout << "    \"Yes,\" said the king, thoughtfully, \"I did say that,didn't I?\"" << endl;
	cout << "    \"Yes,\" said the princess, \"you did.Why wouldn't you tell me?\"" << endl;
	cout << "    \"I didn't want you to go through the same pain as I have,\" said the king." << endl;
	cout << "    The princess stared at her father, feeling hurt and betrayed." << endl;
	cout << "    \"Now,\" said the king, looking at his chief military officer, \"That will be" << endl;
	cout << "all.The next meeting will be in the war room.\"" << endl;
	cout << "    \"We don't have a war room, your majesty,\" said the officer." << endl;
	cout << "    \"Yet,\" said the king, \"By the time we meet again,we will.\"" << endl;
	cout << "    \"Yes,your majesty,\" said the officer." << endl;
	cout << "    The military officer bowed to the king, then left." << endl;
	cout << "    \"Father,\" said the princess, still hurt by what she heard and that her" << endl;
	cout << "father never told her, \"Are you sure about this?\"" << endl;
	cout << "    \"More than anything, Leanne,\" said the king." << endl;
	cout << "    \"How did it happen?\" asked the princess." << endl;
	cout << "    \"Well,\" said the king, \"it started with the interference of surveillance" << endl;
	cout << "missions,leading up to your kidnapping-\"" << endl;
	cout << "    \"That's not what I meant,\" said the princess, \"I meant Mom. How was she" << endl;
	cout << "killed?\"" << endl;
	system("pause");
	system("cls");
	cout << ct20 << "179\n" << endl;
	cout << "    \"Now's not the time to discuss this, Leanne,\" said the king." << endl;
	cout << "    \"When is a good time to discuss this?\" asked the princess, frustrated," << endl;
	cout << "\"Every time I try to talk to you about her,you push me away.If you're not going" << endl;
	cout << "to tell me, then I'm going to find out for myself!\"" << endl;
	cout << "    The princess quickly swam away, leaving her father alone." << endl;
	cout << "    \"Leanne!\" The king called as she swam away." << endl;
	cout << "    The princess ignored her father's calls and swam off to find all she could" << endl;
	cout << "about her mother and her death." << endl;
	cout << "    She figured the record room would be a good place to start, so she headed" << endl;
	cout << "down that way. She was on her way when the gut feeling she had since her father" << endl;
	cout << "declared war finally got to her. She could not let the war happen; it would" << endl;
	cout << "only make a bad situation worse. On the other hand, her father seemed" << endl;
	cout << "determined to do this, and sometimes when he got this determined, there was no" << endl;
	cout << "stopping him. There may have been no way to talk him out of it, but she had to" << endl;
	cout << "try for Cosha's sake." << endl;
	cout << "    The princess turned around and started swimming back to where her father" << endl;
	cout << "was. She would have to deal with her personal issues later. Right now, she had" << endl;
	cout << "to deal with first, her taking off the way she did, even though she had been" << endl;
	cout << "very upset, then most importantly, trying to stop a war. In order to do the" << endl;
	cout << "latter, she would have to get through to her father, if that was even possible." << endl;
	cout << "    The king was very angry at a species he already thought of as barbaric and" << endl;
	system("pause");
	system("cls");
	cout << "cruel. It would be very difficult to persuade him not to go to war against them." << endl;
	cout << ct20 << "180\n" << endl;
	cout << "    The princess approached her father, ready to accept the consequences of her" << endl;
	cout << "actions." << endl;
	cout << "    \"Daddy?\" she said, quietly." << endl;
	cout << "    \"Leanne,\" said the king, \"Why did you swim off like that?\"" << endl;
	cout << "    \"Sorry,\" said the princess, trying to seem calm, \"It's a lot to take in. I" << endl;
	cout << "shouldn't have swam off or yelled at you.I'm sorry.\"" << endl;
	cout << "    \"It's okay,\" said the king in a loving tone, \"I should have told you" << endl;
	cout << "sooner. I knew this day would come. Sit down.\"" << endl;
	cout << "    The princess sat in the seat left of the throne. The seat on the right was" << endl;
	cout << "reserved in case there was a queen." << endl;
	cout << "    \"Your mother and I were close,and when she was murdered,it hurt so much I" << endl;
	cout << "didn't ever want to talk about it. Well, it's been eighteen years,and I think" << endl;
	cout << "it's past time you knew about your mother. The war will just have to wait for" << endl;
	cout << "now." << endl;
	cout << "    \"Your mother was the sweetest woman I ever met. It's somewhat funny how we" << endl;
	cout << "met. I was driving along looking for a woman who may have been suitable to" << endl;
	cout << "court, when I saw your mother swimming along the side of the road in the no" << endl;
	cout << "driving zone. Then it just hit me. She was the one I had been looking for." << endl;
	cout << "Well, we courted, and not long after, we were married. You were born about two" << endl;
	cout << "years later." << endl;
	cout << "    \"Well,when you were two,your mother and I were expecting another baby – a" << endl;
	cout << "boy. I'll never forget that fateful day. She went for a ride to relax," << endl;
	system("pause");
	system("cls");
	cout << ct20 << "181\n" << endl;
	cout << "accompanied by four guards. When they found her, she and your unborn brother" << endl;
	cout << "were dead. Three guards were also found dead, and the fourth was missing and" << endl;
	cout << "presumed the same. The chariot had been attacked by those barbaric" << endl;
	cout << "land-dwellers. They also found a land-dweller's body and their equipment among" << endl;
	cout << "the wreckage." << endl;
	cout << "    \"So,you see,Leanne,I wasn't just being cruel when forbidding you to go to" << endl;
	cout << "the surface, I know how dangerous these creatures can be. However, it seems" << endl;
	cout << "your curiosity has once again gotten the best of you and this time it got you" << endl;
	cout << "in a lot of trouble. This offense will not go unanswered. You are the princess" << endl;
	cout << "of Cosha and they will pay for what they've done to you.\"" << endl;
	cout << "    \"What did she look like?\" asked the princess." << endl;
	cout << "    \"Well,\" said the king, \"She was very pretty. You have both her hair and" << endl;
	cout << "eyes. She was kind, gentle, respectful, and curious. You get your curiousness" << endl;
	cout << "from her. She loved you a lot, you know. You were her pride and joy.\"" << endl;
	cout << "    \"Thank you for telling me. Now I understand why you hate the lorans so" << endl;
	cout << "much. However, wouldn't a war now be somewhat rash? I mean, it was a" << endl;
	cout << "land-dweller that saved me, and I am relatively unharmed. I know the lorans" << endl;
	cout << "kidnapped me and put me in some sort of lab, but maybe we should try talking" << endl;
	cout << "first, and if that fails, then what choice do we have? They can't keep" << endl;
	cout << "kidnapping us and treating us like kishmar, but if I am right, they are capable" << endl;
	cout << "of reasoning. Think of how much can be gained by peaceful talks, and how much" << endl;
	cout << "would be lost by all-out war.\"" << endl;
	system("pause");
	system("cls");
	cout << ct20 << "182\n" << endl;
	cout << "    The king considered his daughter's words for a few minutes before" << endl;
	cout << "responding." << endl;
	cout << "    \"I think I know just how to handle this. We won't go to outright war, yet," << endl;
	cout << "but I will send these lorans a message. We will attack one of their coastal" << endl;
	cout << "cities, then try talking. If that fails, both sides will want war. That much I" << endl;
	cout << "know.\"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" << endl;
	system("pause");
	menua();
	return 0;
}
