#include <iostream>
#include <string>
#include "menu.h"

using namespace std;

int c_two()
{
	string ct2 = "The Princess    -    Chapter II    -    Page ";

	system ("cls");
	cout << "The Princess    -    Chapter Two    -    Page 61\n" << endl;
	cout << "It had been eighteen years since the death of Queen Demril and the unborn" << endl;
	cout << "prince. Fortunately, there had been no further incidents with the land" << endl;
	cout << "dwellers. All was well with Cosha and the land-dwellers had not found them as" << endl;
	cout << "the king had feared." << endl;
	cout << "   Above on the surface at a beach, the woman spoke into the small transceiver" << endl;
	cout << "strapped on her wrist." << endl;
	cout << "    \"Alpha team reporting,\" said Jesella into the com-link, \"I'm detecting" << endl;
	cout << "nominal radiation here, well within safety limits. I see no reason this beach" << endl;
	cout << "can't be put for public use. The only thing it needs is some cleaning up.\"" << endl;
	cout << "    \"Got it,\" responded the male admiral." << endl;
	cout << "    Jesella Jantez was tall and slim with long, blond, hair and green eyes. She" << endl;
	cout << "was from one of the west coasts and very smart." << endl;
	cout << "    Jesella was continuing to scan the beach and about to terminate the com" << endl;
	cout << "signal when her palm scanner began to beep." << endl;
	cout << "    \"Stand by, Central Control,\" Jesella said, \"I just got a new signal. It" << endl;
	cout << "could be radiation.\"" << endl;
	cout << "    Jesella put her com-link on stand-by then adjusted her scanner. She then" << endl;
	cout << "tried to find the source of the radiation." << endl;
	cout << "    The radiation signal was weak and it was difficult to determine exactly" << endl;
	cout << "which direction it was coming from. The good thing was, Jesella did get a" << endl;
	cout << "pattern for the signal, but still could not pinpoint it. Jesella took her" << endl;
	cout << "com-link off stand-by." << endl;
	system ("pause");
	system ("cls");
	cout << ct2 << "62\n" << endl;
	cout << "    \"Central Control,\" she said, \"I can't pinpoint the source of the radiation," << endl;
	cout << "but I do have a pattern. I think it's some sort of Zeta radiation, but the" << endl;
	cout << "pattern's very unusual.\"" << endl;
	cout << "    \"Transmit the data back here,\" said the admiral, \"I'll take a look at it" << endl;
	cout << "myself and see what I can make of it.\"" << endl;
	cout << "    \"Aye, sir,\" said Jesella, \"Transmitting data.\"" << endl;
	cout << "    Jesella pressed a couple buttons on the pad of the scanner, then one on the" << endl;
	cout << "side. The scanner started to transmit the data she had collected back to" << endl;
	cout << "Loran's Central Control. A few moments of noises later the scanner beeped," << endl;
	cout << "indicating it was done. Jesella then pressed the same button on the side of it." << endl;
	cout << "    A couple of moments later, the admiral spoke." << endl;
	cout << "    \"Miss Jantez,\" he said, \"I want you to return to Central Command right" << endl;
	cout << "away. I'm going to send a science team with more sensitive equipment to" << endl;
	cout << "pinpoint this. I think we may have something important.\"" << endl;
	cout << "    \"Understood,\" said Jesella, \"I'll return right away.\"" << endl;
	cout << "    \"Understood, Admiral,\" said Jesella, \"I'll be back within two hours.\"" << endl;
	cout << "    \"Very good,\" said the admiral, \"Central command out.\"" << endl;
	cout << "    Jesella was a citizen working for the Loran Central Command center as a" << endl;
	cout << "training assignment. She had been sent to the beach to check if the radiation" << endl;
	cout << "levels left over from the war had dissipated enough to use the beach for the" << endl;
	cout << "public. She was to receive pay when the job was done." << endl;
	cout << "    She wondered why she was suddenly being pulled off the job. She was" << endl;
	system ("pause");
	system ("cls");
	cout << ct2 << "63\n" << endl;
	cout << "certainly qualified to locate the source of this radiation. All she needed was" << endl;
	cout << "better equipment." << endl;
	cout << "    Still, the strange pattern made her curious. She had seen Zeta band" << endl;
	cout << "radiation before, but not with such an unusual pattern as this one had. The" << endl;
	cout << "radiation also seemed to be distorted, as if something was trying to block it." << endl;
	cout << "Jesella was very curious to find out what was both causing and trying to block" << endl;
	cout << "the Zeta radiation." << endl;
	cout << "    The data seemed to have the admiral concerned. There was something about it" << endl;
	cout << "that did not seem right, which made her think that was why she was suddenly" << endl;
	cout << "being pulled off the job. As much as Jesella wanted to stay and help solve this" << endl;
	cout << "strange mystery, the admiral had precedent over the job, and she had to do as" << endl;
	cout << "he had said." << endl;
	cout << "    Jesella therefore packed her equipment, got in her hovercraft, and headed" << endl;
	cout << "back to the Loran Central Command center.\n\n" << endl;
	cout << "    \"A concentration of radiation was discovered yesterday at Ashton Beach by a" << endl;
	cout << "hired surveyor named Jesella Jantez. Upon further investigation, the radiation" << endl;
	cout << "was identified as Zeta band radiation. The pattern seemed unusual, so we sent" << endl;
	cout << "in specialists to find out what was going on. The radiation pattern was found" << endl;
	cout << "to match that of a prototype engine core referred to as the Zenix core." << endl;
	cout << "    \"As you may or may not know, the Zenix was used in an experimental war" << endl;
	system ("pause");
	system ("cls");
	cout << ct2 << "64\n" << endl;
	cout << "vessel during the latter part of the Fuel War. The name of the vessel was the" << endl;
	cout << "Demure. The Demure suffered a navigational failure after taking a few shots and" << endl;
	cout << "went down near the northwestern coast of this continent. The vessel was never" << endl;
	cout << "recovered, and the crew was considered missing and presumed dead." << endl;
	cout << "    \"It is believed the Demur's crew may have ejected the core before the" << endl;
	cout << "vessel crashed in the sea. There is also reason to believe that the Zenix has" << endl;
	cout << "either washed up on the shore, or is somewhere near Ashton Beach." << endl;
	cout << "    \"Much of the Zenix's technology is still classified even to this date, as" << endl;
	cout << "is your mission. You are not to discuss this mission or any information to" << endl;
	cout << "anyone except strictly authorized personnel only." << endl;
	cout << "    \"You lucky three have the mission of finding, recovering and securing the" << endl;
	cout << "Zenix core. Once found and secured, you are to report to me via com-link over a" << endl;
	cout << "secured channel." << endl;
	cout << "    \"Although Ashton Beach is already off-limits, I've ordered it secured for" << endl;
	cout << "security reasons. We don't want this getting out. The Zenix technology," << endl;
	cout << "although twenty years old, is still considered to be highly advanced." << endl;
	cout << "    \"You will be given pass-cards, com-links, equipment, and the necessary" << endl;
	cout << "information to locate and properly secure the Zenix, including the Zeta band " << endl;
	cout << "pattern, and its last known location." << endl;
	cout << "    \"You will begin your search in section twenty-two and continue to section" << endl;
	cout << "thirty. Once you have located the Zenix, you are to secure it, report to me," << endl;
	cout << "and await further orders.\"" << endl;
	system ("pause");
	system ("cls");
	cout << ct2 << "65\n" << endl;
	cout << "    The prime leader handed each of the three scientists a sealed packet." << endl;
	cout << "    \"Are there any questions?\" asked the prime leader." << endl;
	cout << "    \"Ya,\" said Slan, \"I got one. Do you want us to recover it or just report it" << endl;
	cout << "in?\"" << endl;
	cout << "    \"I want it recovered,\" said the prime leader, \"secured, then reported in." << endl;
	cout << "After which you are to maintain your position and await further orders.\"" << endl;
	cout << "    \"Got it,\" said Slan." << endl;
	cout << "    \"Good,\" said the prime leader, \"Now get going - And good luck.\"" << endl;
	cout << "    The three scientists gathered their equipment and headed for Ashton beach" << endl;
	cout << "to find the Zenix.\n\n" << endl;
	cout << "    Ashton Beach was beautiful, breezy, and vacant. It had been off-limits to" << endl;
	cout << "the public since the Fuel War. In the midst of the war, a bomb had radiated the" << endl;
	cout << "beach, and although the radiation levels were safe to people, there was still a" << endl;
	cout << "lot of debris left. Until the debris was cleared, the beach would be deemed" << endl;
	cout << "unsafe for public use." << endl;
	cout << "    The three scientists assigned there, Kang, Slan, and Zenron, were there to" << endl;
	cout << "look for radiation relative to an experimental core called the Zenix. The" << endl;
	cout << "scientists were using type three palm scanners, whereas the surveyor that had" << endl;
	cout << "initially discovered the radiation was using a slightly less sophisticated" << endl;
	cout << "scanner. The palm scanners the scientists were using resembled small, foldable," << endl;
	system ("pause");
	system ("cls");
	cout << ct2 << "66\n" << endl;
	cout << "hand-held, computers with a fancy display." << endl;
	cout << "    \"All clear in section twenty-four,\" Kang said into his com-link, \"Radiation" << endl;
	cout << "levels are minimal and well within safety limits. Now proceeding to section" << endl;
	cout << "twenty-five.\"" << endl;
	cout << "    Kang switched off his com-link. So far, it was just standard routine for" << endl;
	cout << "the scientists." << endl;
	cout << "    The com-links were transceivers that were strapped to the scientists'" << endl;
	cout << "wrists like a watch." << endl;
	cout << "    The three continued to look for the source of the radiation, and hoped that" << endl;
	cout << "it was coming from the Zenix. If the radiation was being produced by a" << endl;
	cout << "different source, it could complicate matters. The radiation signal was weak" << endl;
	cout << "and hard to pinpoint. This did not discourage the scientists; it just made" << endl;
	cout << "their job harder and more frustrating." << endl;
	cout << "    \"Hey,\" Kang suddenly said while stopping the others with a hand gesture," << endl;
	cout << "\"Look at that.\"" << endl;
	cout << "    Kang seemed surprised at whatever it was he was seeing." << endl;
	cout << "    Kang Krillon, six feet and six inches tall, was well built with short," << endl;
	cout << "brown, hair and deep-green eyes. He was the strongest and smartest of the" << endl;
	cout << "three, which was why he was chosen to lead the mission." << endl;
	cout << "    He came from the northern part of the central continent and felt it was hot" << endl;
	cout << "at the beach." << endl;
	cout << "    \"Lookit what?\" asked Slan with a dumb look." << endl;
	system ("pause");
	system ("cls");
	cout << ct2 << "67\n" << endl;
	cout << "    Slan Callik was short, fat, and stupid. Kang and Zenron did not know what" << endl;
	cout << "it was that got Slan on the mission. The only thing that made sense was," << endl;
	cout << "despite his obvious lack of intellect, Slan was an excellent driver. Either" << endl;
	cout << "that or the rumors that Slan got the job because one of his close uncles had a" << endl;
	cout << "lot of political influence were true." << endl;
	cout << "    Slan was born and raised in Central Loran and came from a family with a lot" << endl;
	cout << "of political power and influence in the loran senate." << endl;
	cout << "    \"Her,\" said Kang, pointing, \"Who is she and what does she think she's doing" << endl;
	cout << "here?\"" << endl;
	cout << "    Kang was pointing out a young woman who appeared to be in her early" << endl;
	cout << "twenties, about five and a half feet tall, with long, wavy, blond hair. She" << endl;
	cout << "wore some sort of decorative aqua bikini top and nothing else." << endl;
	cout << "    The woman seemed to be trying to dig something out of the mud in the" << endl;
	cout << "receding tide." << endl;
	cout << "    \"I have no idea,\" said Zenron, \"Maybe we should find out.\"" << endl;
	cout << "    Zenron Temrik, six feet and one inch tall, had short, sandy-blond hair, and" << endl;
	cout << "brown eyes. He had a medium build and a face that always looked like he needed" << endl;
	cout << "to shave, even after he just had." << endl;
	cout << "    Not much was known about Zenron, except he came from the deepest southwest" << endl;
	cout << "of Loran and did not like to talk about it." << endl;
	cout << "    The scientists observed the young woman and tried to figure out what she" << endl;
	cout << "was after, and why she was not wearing anything else. Slan observed while" << endl;
	system ("pause");
	system ("cls");
	cout << ct2 << "68\n" << endl;
	cout << "trying to subtly gawk at her." << endl;
	cout << "    \"I think she's lookin' for somethin',\" said Slan." << endl;
	cout << "    \"Let's find out what,\" said Kang, then started to head for the strange" << endl;
	cout << "woman." << endl;
	cout << "    \"Wait,\" said Slan, stopping Kang, \"Shouldn' we watch 'n' find out what she" << endl;
	cout << "doin' instead of disturbin' her?\"" << endl;
	cout << "    \"Don't you think she's a bit young for you, Slan?\" asked Zenron." << endl;
	cout << "    \"Whatcha mean?\" asked Slan." << endl;
	cout << "    \"I can tell the way you're looking at her,\" said Zenron, \"She can't be any" << endl;
	cout << "older than twenty, and you're well over thirty-five. Like I said, I think she's" << endl;
	cout << "a bit young for you.\"" << endl;
	cout << "    \"Never mind that,\" said Kang, \"We're just going to go over and talk to her." << endl;
	cout << "I want to find out what a mostly naked woman is doing on a beach that is both" << endl;
	cout << "restricted and secured, and I mean besides getting arrested. I also want to" << endl;
	cout << "know how she got past security, unless someone's not doing their job.\"" << endl;
	cout << "    \"She's probably just a nut 'r somethin',\" said Slan." << endl;
	cout << "    \"Then we should proceed with caution,\" said Zenron." << endl;
	cout << "    \"Agreed,\" said Kang." << endl;
	cout << "    The three scientists began to approach the woman." << endl;
	cout << "    \"By the way, Slan,\" said Kang, \"She is a bit young for you.\"" << endl;
	cout << "    \"Not funny,\" said Slan." << endl;
	cout << "    As the scientists approached the woman, she suddenly looked up at them and" << endl;
	system ("pause");
	system ("cls");
	cout << ct2 << "69\n" << endl;
	cout << "grabbed a small, rectangular, silver object from the mud, then quickly ran into" << endl;
	cout << "the water. She then dove in and did not surface." << endl;
	cout << "    \"Stop right there!\" Kang shouted at the woman when she started to run." << endl;
	cout << "    Kang drew out his laser-pistol, but by the time he could aim it, the" << endl;
	cout << "strange woman was gone." << endl;
	cout << "    \"Damn, she's fast,\" said Slan." << endl;
	cout << "    \"Where did she go?\" asked Kang, \"Start scanning.\"" << endl;
	cout << "    Kang and Slan took out their palm scanners. Zenron already had his out and" << endl;
	cout << "already had started taking readings." << endl;
	cout << "    \"Kang,\" said Zenron, \"I don't think we're going to find her. According to" << endl;
	cout << "the readings I've been getting, something… unusual just happened. I'm not sure" << endl;
	cout << "what exactly, but I do know the woman's heading at two-twelve by minus fifteen" << endl;
	cout << "at about fifteen knots.\"" << endl;
	cout << "    \"What?\" said Kang, not quite believing what he just heard, \"No one can swim" << endl;
	cout << "that fast.\"" << endl;
	cout << "    He checked his scanner, which confirmed the woman's speed and heading." << endl;
	cout << "    \"I don't believe this,\" said Kang, \"She's already almost out of range.\"" << endl;
	cout << "    \"Well,\" said Zenron, \"At almost fifteen knots, one hundred meters is not a" << endl;
	cout << "lot to cover.\"" << endl;
	cout << "    \"All this technology, and the range sucks,\" said Kang, referring to the" << endl;
	cout << "palm scanners, \"Zenron,\" said Kang, \"You said something unusual happened. Was" << endl;
	cout << "" << endl;
	system ("pause");
	system ("cls");
	cout << ct2 << "70\n" << endl;
	cout << "it the speed at which she swam away, or something else?\"" << endl;
	cout << "    \"Both,\" said Zenron, \"According to this funky scanner, the woman somehow" << endl;
	cout << "seems to have transformed into something with what seems to be fins instead of" << endl;
	cout << "feet, which could explain why she can swim so fast. It seems to be some sort of" << endl;
	cout << "cellular reorganization that affected most of her entire body. The cellular" << endl;
	cout << "reorganization seemed to be concentrated mostly from the midsection down. I'm" << endl;
	cout << "not sure what exactly took place, but if I were to speculate, I would say she" << endl;
	cout << "has the capability to adapt to land or sea.\"" << endl;	cout << "" << endl;
	cout << "    \"Let me see that data,\" said Kang, addressing Zenron." << endl;
	cout << "    \"Here you go,\" said Zenron, handing Kang his scanner." << endl;
	cout << "    Kang looked at the sensor data while Slan stared into space." << endl;
	cout << "    \"Well,\" said Kang, bringing Slan back into reality, \"It looks like we" << endl;
	cout << "either found a new life form, or a mutant. We'll make a report.\"" << endl;
	cout << "    \"Oh shr',\" said Slan, sarcastically, \"make a report and give it t' our" << endl;
	cout << "superiors. I bet we get a nice long vacation for such a nice repor'.\"" << endl;
	cout << "    \"What's that supposed to mean?\" asked Zenron." << endl;
	cout << "    \"I give you a hint,\" said Slan, \"Nice young men in clean white coats and a" << endl;
	cout << "padded room.\"" << endl;
	cout << "    \"I get it,\" said Zenron, \"I don't think we'll have to worry about that," << endl;
	cout << "besides most hospitals are nicer than that.\"" << endl;
	cout << "    \"How would ya know?\" asked Slan, \"Ever been in one?\"" << endl;
	system ("pause");
	system ("cls");
	cout << ct2 << "71\n" << endl;
	cout << "    \"No,\" said Zenron, \"but I pay attention to things around me.\"" << endl;
	cout << "    \"If we give a repor',\" said Slan, \"that some wom'n c'n transform into some" << endl;
	cout << "sea wom'n, they'll lock us up f' sure.\"" << endl;
	cout << "    \"I don't think so,\" said Kang, \"The data we have is quite solid. We'll make" << endl;
	cout << "that report when we get back to Central Command. Until then, we have an engine" << endl;
	cout << "core to find, although while we're at it, we'll keep searching for the woman," << endl;
	cout << "if it's even possible to locate her now." << endl;
	cout << "    \"Zenron, since you were the one to discover this… water girl, you're the" << endl;
	cout << "one who will keep looking for her just in case she returns. You are to" << endl;
	cout << "continuously scan for her, and if she shows up, let me know immediately.\"" << endl;
	cout << "    \"Got it,\" said Zenron, then after a long pause, \"'Water girl'? An" << endl;
	cout << "interesting term and kind of fitting, but wouldn't water woman be more" << endl;
	cout << "accurate? After all, she did seem to be an adult.\"" << endl;
	cout << "    \"Whatever,\" said Kang, \"It was a term off the top of my head. Just keep" << endl;
	cout << "scanning for her.\"" << endl;
	cout << "    \"Rightie-oh,\" said Zenron, while adjusting his scanner, \"Keeping a look-out" << endl;
	cout << "for the water person.\"" << endl;
	cout << "    Kang gave Zenron a strange look for the comments that he made, then started" << endl;
	cout << "ahead." << endl;
	cout << "    \"Let's go find that core,\" said Kang." << endl;
	cout << "    \"I'm righ' behin' ya,\" said Slan." << endl;
	cout << "    Slan and Kang scanned for the Zenix core, while Zenron continued scanning" << endl;
	system ("pause");
	system ("cls");
	cout << ct2 << "72\n" << endl;
	cout << "for the strange woman.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" << endl;
	system ("pause");
	menu();
	return 0;
}
