#include <iostream>
#include <string>
#include "menu.h"

using namespace std;

int pro()
{
	string titlep = "The Princess    -    Prologue    -    Page ";

	system ("cls");
	cout << "The Princess    -    Page 1" << endl;
	cout << "_______________________________________________________________________________" << endl;
	cout << "                                   Prologue\n" << endl;
	cout << "\"Hello and greetings, reader. My name is Louis Al'Fraize, you can call me" << endl;
	cout << "Louie. I was at one time the captain of the late E.A. Valkyries. I've been" << endl;
	cout << "retired from the fleet for almost five years now, and believe me, it's not the" << endl;
	cout << "same. Life in the fleet was interesting. We went to a wide variety of places on" << endl;
	cout << "all sorts of missions. We were assigned anything from diplomatic to" << endl;
	cout << "exploration, to search and rescue missions. We were even assigned the dreaded" << endl;
	cout << "border patrol. It was dreaded because for the most part there was nothing to do" << endl;
	cout << "while patrolling. The only thing that broke that pace would be an occasional" << endl;
	cout << "violator. Usually it didn't result in any thing major, just a warning. The" << endl;
	cout << "exploration missions were a little bit different. They could be boring," << endl;
	cout << "exciting, or draining, depending on what happened. One never knew what to" << endl;
	cout << "expect on those missions." << endl;
	cout << "    \"Two of the most memorable missions to me were the two we made to Loran." << endl;
	cout << "    \"It was a situation that started good, and turned bad very quickly. We were" << endl;
	cout << "originally sent there to evaluate the Lorans for entry into the alliance, and" << endl;
	cout << "ended up returning to mediate peace negotiations between the Lorans and" << endl;
	cout << "previously unknown Coshens." << endl;
	cout << "    \"Maybe I should tell you what isn't classified." << endl;
	cout << "    \"The story starts more than ten years before the Lorans broke the light" << endl;
	cout << "barrier, for back ground. It begins a little bit before the late Coshen king" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "2\n" << endl;
	cout << "met the Coshen queen Demril...\"\n" << endl;
	cout << "    Loran was a beautiful planet with peaceful weather. It was the fourth" << endl;
	cout << "planet in a system of eleven. The planet was populated with two major" << endl;
	cout << "intelligent species. One kind lived on land, while the other lived primarily in" << endl;
	cout << "the warmer parts of the Loran seas." << endl;
	cout << "    The people that lived on land called themselves Lorans, while the people" << endl;
	cout << "that lived in the seas called themselves Coshens. The Coshens were aware of the" << endl;
	cout << "Lorans, and were educated in what little they knew about them. The Lorans, on" << endl;
	cout << "the other hand, were mostly ignorant of the Coshens." << endl;
	cout << "    The only mention of Coshens in loran culture was in myths and legends that" << endl;
	cout << "spoke of unusually beautiful women from the sea that looked like the loran" << endl;
	cout << "women, but had fins instead of feet." << endl;
	cout << "    The Coshens had made little attempt to contact the Lorans. Some of the" << endl;
	cout << "contact that was made was accidental, led to the creation of the loran legends." << endl;
	cout << "Some of these loran myths and legends were true. Such myths and legends that" << endl;
	cout << "were, were ones about three kings that ruled the world. In Loran legend these" << endl;
	cout << "beings, very different from each other, worked together to keep Loran beautiful" << endl;
	cout << "and peaceful. One of these beings ruled the sky, one ruled the land, and the" << endl;
	cout << "third, not mentioned until later legends, ruled the waters." << endl;
	cout << "    The land king Sanken could create or stop earthquakes, control the growth" << endl;
	cout << "of plants and trees, and any animal that lived on land. The sky king, Honmar," << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "3\n" << endl;
	cout << "controlled the weather, winds, and any creature that could fly, or lived in the" << endl;
	cout << "sky. The sea king, who strangely enough was not mentioned in legends, ruled the" << endl;
	cout << "seas and all creatures that lived in the waters." << endl;
	cout << "    The twist about the legends was that the three kings were real at one time" << endl;
	cout << "or another. The land king and his kind had died centuries ago, while king" << endl;
	cout << "Honmar was the last of his kind. The sea king and his kind, on the other hand," << endl;
	cout << "were flourishing quite well, having developed an advanced civilized culture in" << endl;
	cout << "the depths of the oceans." << endl;
	cout << "    The loran legends were written during what the Coshens referred to as the" << endl;
	cout << "dark times. This was the period of time before the Coshens were united as one" << endl;
	cout << "people. Before the unification, the Coshens were split into several divisions," << endl;
	cout << "or factions. Each faction had its own government, and sometimes when" << endl;
	cout << "governments crossed, they would cause confrontations or, on occasion, wars." << endl;
	cout << "At the time, the legends were written there were three kings, also referred at" << endl;
	cout << "the time to as gods. Long before, though there was only the land king and the" << endl;
	cout << "sky king. At that time there were no Coshens, therefore there was no sea king." << endl;
	cout << "As time went by, the sea people, which resembled the Lorans unlike the land or" << endl;
	cout << "sky people, began to appear." << endl;
	cout << "    As even more time passed, the land king's people began slowly dying off," <<endl;
	cout << "and at present, they were extinct, having died centuries ago, shortly after" << endl;
	cout << "Cosha was united." << endl;
	cout << "    The king of the Coshens, King Toran, had been king since he was seventeen." << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "4\n" << endl;
	cout << "his father, King Kafin, had died quite unexpectedly, from unknown causes. There" << endl;
	cout << "was an investigation regarding this, but no explanation could be given. He" << endl;
	cout << "seemed to have just died for no reason." << endl;
	cout << "    King Toran's mother, on the other hand, had been killed almost two years" << endl;
	cout << "prior to his father's death. She died from a shark attack brought on by" << endl;
	cout << "treason." << endl;
	cout << "    The attack had been a set-up. It was suspected, after a long and" << endl;
	cout << "thorough investigation, the shark had been lured to where the queen was" << endl;
	cout << "expected to be taking her usual afternoon stroll in the garden." << endl;
	cout << "    Queen Pritma would take a stroll in the beautiful royal garden about mid" << endl;
	cout << "afternoon every day. It was like clockwork; the same time every day. This was" << endl;
	cout << "mostly because certain types of flora would bloom at that time, and those types" << endl;
	cout << "happened to be her favorite." << endl;
	cout << "	It was later further discovered that the queen had been betrayed by one" << endl;
	cout << "of the king's own top advisers. The adviser had hired people to capture the" << endl;
	cout << "shark. He then helped them get it past the Coshen security parameters, which" << endl;
	cout << "had been put there to keep out dangerous creatures, such as some of the larger" << endl;
	cout << "sea serpents that roamed the seas." << endl;
	cout << "    The hired then put the shark in a holding area and gave it no food. Later," << endl;
	cout << "the hired created a scent trail of blood to the garden where the queen was" << endl;
	cout << "expected to be. The starving shark followed the scent trail to the garden. By" << endl;
	cout << "the time the queen and the shark got to the garden, the queen could not sense" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "5\n" << endl;
	cout << "the trail. This was because Coshens did not have as good of a sense of smell as" << endl;
	cout << "a shark. The starving shark followed the scent, and attacked the queen, killing" << endl;
	cout << "her." << endl;
	cout << "    Once the adviser was found, he was executed for treason. When his hired" << endl;
	cout << "help was found, they were banished from all of Cosha forever, under the 'pain" << endl;
	cout << "of death'." << endl;
	cout << "    There had been other reports of attacks on Coshens, but those took place" << endl;
	cout << "under entirely different circumstances. Studies had shown the sharks were most" << endl;
	cout << "likely mistaking their victims for food. There were, however, no solid" << endl;
	cout << " conclusions." << endl;
	cout << "    Such conclusions were mostly based on studies that always needed more data." << endl;
	cout << " This was because the Coshens had a limited understanding on the behavior of" << endl;
	cout << "sharks." << endl;
	cout << "    One of the 'mistaken food' theories was based on the poor eyesight, low" << endl;
	cout << "intelligence, and highly developed sense of smell of the sharks. It was also" << endl;
	cout << "based on the fact the sharks could pickup, and often would react upon," << endl;
	cout << "vibrations in the waters. According to the theory, which had a strong basis," << endl;
	cout << "these factors were causing the sharks to associate the movements and appearance" << endl;
	cout << "of the Coshens in the water as just another fish to eat." << endl;
	cout << "    The Coshens were not part of the sharks' diet. The sharks usually ate the" << endl;
	cout << "fish, or other small sea animals that hung around in the shallow waters." << endl;
	cout << "    These facts were what led to the 'mistaken food' theory. In addition, when" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "6\n" << endl;
	cout << "a shark usually attacked a coshen, it would almost immediately let go. If the" << endl;
	cout << "coshen fought the shark during the attack, it would usually completely" << endl;
	cout << "disengage the attack, and leave the coshen alone, figuring there was easier" << endl;
	cout << "prey to find." << endl;
	cout << "    This was true for most species of shark. However, there are always" << endl;
	cout << "exceptions to the rules. For example, there were a couple of species that could" << endl;
	cout << "be very vicious. These sharks would attack with far more persistence. They were" << endl;
	cout << "considered some of the most dangerous species of sharks. Fortunately, these" << endl;
	cout << "types of shark were found mostly in shallow waters that Coshens tended to" << endl;
	cout << "avoid." << endl;
	cout << "    For the most part, the Coshens stayed away from the shallow waters to avoid" << endl;
	cout << " detection by the Lorans, and they pretty much avoided sharks altogether." << endl;
	cout << "    Of course, there were those who studied the sharks, but, as in any culture," << endl;
	cout << "there were those who purposely put themselves in danger. They were the" << endl;
	cout << "daredevils and entertainers. Despite the reckless behavior of these Coshens," << endl;
	cout << "attacks were still rare; however, those types of attacks were usually fatal." << endl;
	cout << "Thus, the mystery behind the queen's death had been solved, and the unexplained" << endl;
	cout << "death of King Kafin made the seventeen-year-old prince, Toran, king." << endl;
	cout << "    It had now been five years since the king inherited Cosha's throne, and" << endl;
	cout << "feeling lonely and wanting children, he felt it was time to choose a bride. He" << endl;
	cout << "took two of his top aids, and went for a ride around the city." << endl;
	cout << "    They had been looking most of the day. They came to a quieter part of the" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "7\n" << endl;
	cout << "city. It was still in the main city, but did not seem like it. They were on a" << endl;
	cout << "fairly quiet road, and the king was about to return to the palace when a" << endl;
	cout << "certain woman walking on the opposite side of the road caught his attention." << endl;
	cout << "    She was of average height, pretty with long, blond hair that had a slight" << endl;
	cout << "wave to it. Her body posture indicated a woman who was confident of herself," << endl;
	cout << "but not stuck-up." << endl;
	cout << "    \"She's beautiful,\" said the king, pointing out the woman he saw." << endl;
	cout << "    \"She seems rather plain, your majesty,\" said one of the aids." << endl;
	cout << "    \"Maybe I didn't get a good enough look at her,\" said the king, \"Driver," << endl;
	cout << "come about again, and this time drive slower.\"" << endl;
	cout << "    The driver did as the king said, and this time when they approached the" << endl;
	cout << "woman, the driver slowed the vehicle a bit, so the king could have a closer" << endl;
	cout << "look at her." << endl;
	cout << "    \"I was right,\" said the king, \"She is beautiful, and alert too, which is" << endl;
	cout << "a good sign of intelligence. Driver, go around the other way, as to approach" << endl;
	cout << "her from behind.\"" << endl;
	cout << "    The vehicle the king was in, was called a jet-runner, and was similar to a" << endl;
	cout << "fancy limousine modified for water travel. It was designed so that it could set" << endl;
	cout << "on its bottom when still, and had small underwater jet-like devices allowing" << endl;
	cout << "the vehicle to travel in virtually any direction." << endl;
	cout << "    \"As you wish,\" said the driver." << endl;
	cout << "    They drove around the area once again, approaching the woman from behind," << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "8\n" << endl;
	cout << "as the king had said. When they passed her by, the king instructed the driver" << endl;
	cout << "to stop the vehicle at the side of the road, out of the way of traffic. He then" << endl;
	cout << "waited for the attractive woman to swim up to them." << endl;
	cout << "    \"Excuse me,\" the king called to the woman when she was close enough to" << endl;
	cout << "hear his voice." << endl;
	cout << "The woman turned to the sound of the king's voice. The king and his two aids" << endl;
	cout << "then got out of the royal jet-runner. The two aids waited on either side of the" << endl;
	cout << "vehicle's open door." << endl;
	cout << "    \"Would you come here a moment?\" the king politely asked, now that he had" << endl;
	cout << "the woman's attention." << endl;
	cout << "    The woman approached the king." << endl;
	cout << "    \"Your majesty,\" said the woman as she bowed herself to the king." << endl;
	cout << "    \"Arise;\" said the king, \"Tell me, what is your name, fair lady?\"" << endl;
	cout << "    The woman rose up, facing the king." << endl;
	cout << "    \"My name,\" said the woman, respectfully, \"is Miss Demril A-Chik, your" << endl;
	cout << "majesty,\"" << endl;
	cout << "    \"Ahh...,\" said the king, taking in Demril's name, \"a name as beautiful as" << endl;
	cout << "its bearer.\"" << endl;
	cout << "    \"Thank you, your Majesty,\" said Demril." << endl;
	cout << "    \"How would you like a royal tour of the castle?\" asked the king." << endl;
	cout << "    \"It would be an honor,\" said Demril, humbly." << endl;
	cout << "    \"Very good,\" said the king, \"Come with me.\"" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "9\n" << endl;
	cout << "    \"You mean, right now?\" asked Demril, surprised at the timing of the" << endl;
	cout << "invitation." << endl;
	cout << "    \"Yes, right now,\" said the king, a bit amused by Demril's surprised" << endl;
	cout << "reaction." << endl;
	cout << "    The king helped Demril into the royal jet-runner as more of a polite" << endl;
	cout << "gesture than a necessity. Once she was in, the king and his two aids got in," << endl;
	cout << "the king and one of his aids on her side, and the other aid on the other side." << endl;
	cout << "    \"To the castle,\" the king told the driver." << endl;
	cout << "    The driver drove off, taking them to the castle. When they arrived there," << endl;
	cout << "the king and his two aids got out of the royal jet-runner, then the king helped" << endl;
	cout << "Demril out." << endl;
	cout << "    \"Thank you,\" said Demril as the king helped her out." << endl;
	cout << "    Demril understood the gesture, even though it was rarely used. She had" << endl;
	cout << "heard of the gesture through the older Coshens who remembered their" << endl;
	cout << "grandparents doing it. The gesture had been discontinued mostly by Demril's" << endl;
	cout << "grandparents' generation, with the exception of the rich and royalty. That" << endl;
	cout << "tradition was still practiced by them to the day, and Demril felt special when" << endl;
	cout << "the king helped her out." << endl;
	cout << "    \"It's been really nice of you to do this, your majesty,\" said Demril, as" << endl;
	cout << "the king escorted her to the castle." << endl;
	cout << "    \"The pleasure is mine,\" said the king." << endl;
	cout << "    The king gave Demril a tour of the castle. He showed her all sorts of" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "10\n" << endl;
	cout << "beautiful and unusual things. The king was a very good host, telling Demril" << endl;
	cout << "about the relics in an interesting way, while telling the stories behind them" << endl;
	cout << "and showing her some of the writings. Demril was very interested, and felt she" << endl;
	cout << "wanted to learn more." << endl;
	cout << "    Some of the things the king showed her were ancient, dating back to Cosha's" << endl;
	cout << "prehistoric times. Others were more modern, and some were more mysterious," << endl;
	cout << "being of completely unknown origin." << endl;
	cout << "    The king spent a couple of hours showing Demril the castle and conversing" << endl;
	cout << "with her. Demril enjoyed both the tour and the conversations. When the evening" << endl;
	cout << "approached, the king asked Demril to dine with him." << endl;
	cout << "    \"It would be an honor,\" said Demril." << endl;
	cout << "    The king smiled, and then said, \"Seeing as it's still early, why don't you" << endl;
	cout << "freshen up?\"" << endl;
	cout << "    \"Thank you, your majesty,\" said Demril, \"I think I will.\"" << endl;
	cout << "    The king summoned for a female servant." << endl;
	cout << "    \"You called for me?\" asked the servant upon arrival." << endl;
	cout << "    \"Escort Lady Demril to a washroom, so she may freshen up,\" the king told" << endl;
	cout << "the servant." << endl;
	cout << "    \"Yes, your majesty,\" said the servant, then to Demril, \"Right this way," << endl;
	cout << "please.\"" << endl;
	cout << "    The servant began to escort Demril to the washroom." << endl;
	cout << "    \"Wait,\" said the king to the servant, \"Demril, you go ahead, my servant" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "11\n" << endl;
	cout << "will meet up with you down the hall.\"" << endl;
	cout << "    Demril acknowledged the king, and then continued down the hall, while the" << endl;
	cout << "servant went back to the king." << endl;
	cout << "    \"While Demril's freshening up, you are to arrange for there to be a change" << endl;
	cout << "of clothes,\" said the king, \"then have the clothes she's wearing to be cleaned." << endl;
	cout << "She'll go home in clean, new, clothes, not in her work clothes. Be sure the new" << endl;
	cout << "clothes are at least something elegant. I want them to make a good impression" << endl;
	cout << "on her.\"" << endl;
	cout << "    \"I believe I have just the thing for her, your majesty,\" said the servant." << endl;
	cout << "    \"Good,\" said the king, \"If you need another servant to assist you, feel" << endl;
	cout << "free to call for one. The new clothes are to be delivered, and the ones she's" << endl;
	cout << "wearing washed as soon as possible.\"" << endl;
	cout << "    \"Yes your majesty,\" said the servant, \"It shall be done immediately.\"" << endl;
	cout << "    \"Excellent,\" said the king, \"That will be all.\"" << endl;
	cout << "    The servant left to meet up with Demril, then continued to escort her to" << endl;
	cout << "the washroom." << endl;
	cout << "    It was an honor and tradition, dating back many royal generations, for" << endl;
	cout << "royalty to extend this courtesy to special guests. It was a special honor if" << endl;
	cout << "the guests were common people. The honor was considered an acceptance into" << endl;
	cout << "royal hospitality. The changing of clothes was a symbol of transition and" << endl;
	cout << "appreciation of this royal acceptance. It was considered extremely rude and" << endl;
	cout << "insulting not to accept this gesture of hospitality. The clothing provided was" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "12\n" << endl;
	cout << "usually very nice, and comfortable, and never had been worn before. When the" << endl;
	cout << "guest left, they usually left wearing the clothes, which were theirs to keep." << endl;
	cout << "    Demril's new clothes were delivered promptly upon Demril entering the" << endl;
	cout << "washroom. She looked at the servant who was offering her the clothes, then" << endl;
	cout << "smiled a thankful smile." << endl;
	cout << "    \"Thank you,\" said Demril, taking the clothes." << endl;
	cout << "    \"You're welcome, Lady Demril,\" said the servant." << endl;
	cout << "    \"Lady?\" asked Demril, not expecting the term." << endl;
	cout << "    \"Yes,\" said the servant, \"as a guest of the king, you will be addressed as" << endl;
	cout << "Lady Demril. It's an honorary title and a matter of protocol.\"" << endl;
	cout << "    \"I see,\" said Demril, feeling honored, \"Thank you,\"" << endl;
	cout << "    The servant left Demril to freshen up." << endl;
	cout << "    Demril freshened up then put the new clothes on. They were beautiful, and" << endl;
	cout << "felt sturdy and soft, like the expensive clothing she felt when browsing the" << endl;
	cout << "high-class, expensive stores. When Demril was finished, she was escorted back" << endl;
	cout << "to where the king awaited. Her clothes were picked up by another servant to be" << endl;
	cout << "cleaned." << endl;
	cout << "    \"Much better,\" said the king, \"You look elegant. Shall we dine?\"" << endl;
	cout << "    \"Yes,\" said Demril, \"we shall.\"" << endl;
	cout << "    The king put his elbow out in gesture, and Demril, recognizing the gesture," << endl;
	cout << "placed her hand in his elbow. The king then escorted her to the dining hall." << endl;
	cout << "When they arrived, the king pulled out a seat for Demril, who sat in it. The" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "13\n" << endl;
	cout << "king then pushed her in to the table, and then sat across from her. The" << endl;
	cout << "servants then began serving the food." << endl;
	cout << "    The meal was exquisite, and simple. It had a variety, without being overly" << endl;
	cout << "filling." << endl;
	cout << "    Demril and the king talked some more while they ate dinner. They talked" << endl;
	cout << "about a variety of subjects, such as the previous rulers of Cosha, how Cosha" << endl;
	cout << "became united, Demril's job, her family history, and such. The king had" << endl;
	cout << "pleasantly discovered that despites Demril's youth of twenty-one, she was well" << endl;
	cout << "educated." << endl;
	cout << "    \"Would you care to take a swim in the garden?\" the king asked after the" << endl;
	cout << "meal was finished." << endl;
	cout << "    \"It would be a pleasure,\" said Demril." << endl;
	cout << "    The king and Demril got up and swam out to the garden." << endl;
	cout << "    The garden was very large, with various sea-plants, and flora. There were" << endl;
	cout << "coral formations and designs that added multi-level uniqueness. Demril had" << endl;
	cout << "never seen anything like it before. The garden spanned multiple levels, seeing" << endl;
	cout << "as Coshens could swim in any direction, and there were smooth stones creating" << endl;
	cout << "paths on the garden floor. There were some plants on top of the upper levels," << endl;
	cout << "and some hanging from others." << endl;
	cout << "    \"This is... magnificent,\" said Demril, finding it difficult to find the" << endl;
	cout << "words to describe the breathtaking beauty of the artistic designs. It was very" << endl;
	cout << "entrancing, and if one allowed themselves, they could get lost in it." << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "14\n" << endl;
	cout << "    \"I'm glad you like it,\" said the king." << endl;
	cout << "    \"I love it,\" said Demril, \"I've never seen anything like it before. It's" << endl;
	cout << "quite breath-taking.\"" << endl;
	cout << "    \"You won't see anything like it anywhere else either,\" said the king, \"It's" << endl;
	cout << "considered to be the most unique and beautiful in all of Cosha, and as king," << endl;
	cout << "it's my duty to make sure it stays that way.\"" << endl;
	cout << "    \"It must've taken a lot to build all this,\" said Demril." << endl;
	cout << "    \"Well,\" said the king, \"I'm sure it did. This garden was designed more than" << endl;
	cout << "one hundred and fifty years ago. Sure, it's had a few additions since then, but" << endl;
	cout << "the original part has been unaltered, aside from a few repairs. The garden was" << endl;
	cout << "designed as a symbol of nature.\"" << endl;
	cout << "    \"Well, I think it expresses it very well,\" said Demril." << endl;
	cout << "    The king and Demril smiled at each other." << endl;
	cout << "    She has very beautiful eyes, thought the king, the kind of blue one could" << endl;
	cout << "get lost in." << endl;
	cout << "    The king and Demril continued their swim through the garden. The king" << endl;
	cout << "pointed out some rare plants and told Demril about them. Demril listened," << endl;
	cout << "interested in what the king was saying." << endl;
	cout << "    \"How much do you know about plants?\" the king asked Demril." << endl;
	cout << "    \"Not much,\" responded Demril, \"Botany was never a strong subject for me.\"" << endl;
	cout << "    \"Truthfully,\" said the king, \"It's not for me either. I had made it a" << endl;
	cout << "special point to study about the rare plants in this garden, and ended up" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "15\n" << endl;
	cout << "studying more. However, I've forgotten most of what I've learned.\"" << endl;
	cout << "    The king and Demril shared a laugh. The king's laugh was like music to" << endl;
	cout << "Demril's ears." << endl;
	cout << "    After the king and Demril finished their swim in the garden, the king" << endl;
	cout << "escorted her back to the castle." << endl;
	cout << "    \"Well,\" said the king, when they got back to the castle, \"this has been a" << endl;
	cout << "very pleasant evening.\"" << endl;
	cout << "    \"Agreed,\" said Demril, \"I found it very enjoyable. Thank you.\"" << endl;
	cout << "    \"The pleasure was mine,\" said the king." << endl;
	cout << "    The king walked Demril out to an awaiting vehicle to bring her home." << endl;
	cout << "    This vehicle was different in the respect that it was not as fancy as the" << endl;
	cout << "one the king rode in, but the presentation and markings said royalty." << endl;
	cout << "    \"The driver will bring you home,\" said the king." << endl;
	cout << "    \"It has been an honor being with you this evening,\" said Demril." << endl;
	cout << "    \"I hope we can do this again,\" said the king." << endl;
	cout << "    The chauffeur helped Demril in to the vehicle." << endl;
	cout << "    \"Goodnight, Lady Demril,\" the king said as she got in." << endl;
	cout << "    \"Goodnight, your majesty,\" responded Demril when she was seated." << endl;
	cout << "    \"I think she's the one,\" the king said thoughtfully to himself, as the" << endl;
	cout << "vehicle pulled away, down the long royal road." << endl;
	cout << "    \"I beg your pardon?\" asked his aid, taken off-guard by the king's comment." << endl;
	cout << "    \"Demril,\" said the king, \"She's a very nice woman, and I think I'm going to" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "16\n" << endl;
	cout << "continue to see her.\"" << endl;
	cout << "    \"Your majesty,\" said the aid, \"Consider these things before making a hasty" << endl;
	cout << "decision. You should marry to be happy, and though Lady Demril seems like a" << endl;
	cout << "very nice lady, she may not be compatible with you. An incompatible-\"" << endl;
	cout << "    \"Be quiet, Halik,\" said the king, interrupting, \"I have a very strong sense" << endl;
	cout << "about her, and I trust my senses. Besides, I didn't say I was going to marry" << endl;
	cout << "her yet.\"" << endl;
	cout << "    \"Yes, your majesty,\" said Halik." << endl;
	cout << "    A while later, Demril arrived at her home. The chauffeur got out, then" << endl;
	cout << "opened Demril's door. She got out of the royal vehicle." << endl;
	cout << "    \"Thank you,\" Demril said to the Chauffeur." << endl;
	cout << "    \"You're very welcome,\" said the chauffeur, \"and good night, Lady Demril.\"" << endl;
	cout << "    \"Good night,\" said Demril." << endl;
	cout << "    Demril went into her home then closed the door. The chauffeur, assured that" << endl;
	cout << "Demril was safe, got back in the vehicle and left. After closing the door," << endl;
	cout << "Demril locked it, and then leaned her back against it. She was still taken" << endl;
	cout << "aback by what had happened to her that evening and by the garden. When she" << endl;
	cout << "quieted herself inside, Demril went to freshen up. She then put the newly" << endl;
	cout << "acquired clothes away, and her own cloths to be washed. Then she put her" << endl;
	cout << "nightgown on." << endl;
	cout << "    When she had finished, Demril called a friend on something similar to a" << endl;
	cout << "phone." << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "17\n" << endl;
	cout << "    The Coshens had long ago developed a type of power system using water" << endl;
	cout << "pressure and light, working similar to fiber optics. It was developed shortly" << endl;
	cout << "before the unification of Cosha, and had a lot of development since." << endl;
	cout << "    Demril let the phone ring for a while, and somebody finally answered." << endl;
	cout << "    \"Hello?\" answered a female voice." << endl;
	cout << "    \"Hi, Pinel,\" said Demril, \"Is Celesta there?\"" << endl;
	cout << "    \"Hang on,\" answered Pinel, \"She's in the wash room, I think she's just" << endl;
	cout << "getting out.\"" << endl;
	cout << "    A few moments of silence later, another female started talking to Demril." << endl;
	cout << "    \"Hello?\" she said." << endl;
	cout << "    \"Celesta,\" said Demril, \"Guess where I've been for the past few hours.\"" << endl;
	cout << "    \"Not home,\" said Celesta, \"I've been trying to reach you all evening, like" << endl;
	cout << "you said, but you haven't been answering. I was about to try again, and if you" << endl;
	cout << "didn't answer this time, I was going to come over. It's rude not to be home" << endl;
	cout << "when you tell someone to call you. Where have you been, anyway?\"" << endl;
	cout << "    \"I've just had the most amazing evening of my life,\" said Demril, \"King" << endl;
	cout << "Toran, out of nowhere, invited me to the royal palace.\"" << endl;
	cout << "    \"Yah, right,\" said Celesta." << endl;
	cout << "    \"Yah,\" said Demril, \"it is right.\"" << endl;
	cout << "    \"Really?\" Celesta asked, skeptically, \"If you just spent the last few hours" << endl;
	cout << "leisurely with the king, then not only can I swim really well, but I can also" << endl;
	cout << "fly.\"" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "18\n" << endl;
	cout << "    \"In that case,\" said Demril, \"get your wings, or whatever you use, ready," << endl;
	cout << "and show me how.\"" << endl;
	cout << "    \"What?\" asked Celesta, not expecting such a literal response, \"I can't" << endl;
	cout << "really fly, just like you didn't really spend all this time with the king. I" << endl;
	cout << "mean, he's royalty, and you were probably just swimming home from work. Another" << endl;
	cout << "thing; why would his majesty just randomly stop and pick up a commoner, if" << endl;
	cout << "you'll excuse the term?\"" << endl;
	cout << "    \"I don't know,\" said Demril, \"but he did. I'm not sure, but I think he" << endl;
	cout << "likes me.\"" << endl;
	cout << "    Celesta laughed at the idea." << endl;
	cout << "    \"The king likes you?\" asked Celesta in disbelief, \"I find that very hard to" << endl;
	cout << "believe. Not that you're ugly, or anything, but you're not exactly royal" << endl;
	cout << "material.\"" << endl;
	cout << "    \"Maybe I should start from the beginning,\" said Demril, annoyed at Celesta" << endl;
	cout << "for her comments, \"Maybe then you'll understand a bit better.\"" << endl;
	cout << "    \"This should be interesting,\" said Celesta." << endl;
	cout << "    \"Okay,\" said Demril, \"Here goes. I was swimming home along Central Avenue," << endl;
	cout << "as usual, from the refinery, when I saw this fancy jet-runner pass by a couple" << endl;
	cout << "of times. I figured no big deal; it was just someone checking the area out. You" << endl;
	cout << "know, for security or something. A few minutes later, though, the same" << endl;
	cout << "jet-runner pulls along side me. Now I'm thinking I've done something wrong. The" << endl;
	cout << "next thing that happened was someone from the vehicle calls me. I turned to see" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "19\n" << endl;
	cout << "toward the jet-runner and realized it was a royal one, and the king had just" << endl;
	cout << "called me over.\"" << endl;
	cout << "    \"Just like that?\" asked Celesta, \"Out of the green?\"" << endl;
	cout << "    \"Yep,\" said Demril, \"Just like that. Actually, it was more like, 'Hey you'," << endl;
	cout << "but the notion was the same. So he calls me over, and the king and two of his" << endl;
	cout << "advisers step out. Now I'm thinking I'm in real big trouble.\"" << endl;
	cout << "    \"I see,\" said Celesta." << endl;
	cout << "   \"So,\" said Demril, \"I went over and paid my respects to the king. He then" << endl;
	cout << "asks me my name, so I told him my name, and family name.\"" << endl;
	cout << "    \"Naturally,\" said Celesta." << endl;
	cout << "     \"Then,\" said Demril, \"he tells me my name is as beautiful as I am. After" << endl;
	cout << "which, he asks me if I would like a royal tour of the castle. My heart started" << endl;
	cout << "beating fast, and I felt a little shaky, but I kept control. So I naturally" << endl;
	cout << "accepted.\"" << endl;
	cout << "    \"Of course,\" said Celesta, \"You'd be a fool to refuse, not to mention very" << endl;
	cout << "rude.\"" << endl;
	cout << "    \"Exactly,\" said Demril, \"Not to mention this was a once in a lifetime" << endl;
	cout << "opportunity, and not to be taken lightly. Anyway, as I said, I accepted. The" << endl;
	cout << "king then helps me in to the royal jet-runner, and we headed for the castle." << endl;
	cout << "Then the king gave me a complete tour, and I'm telling you, it was the most" << endl;
	cout << "interesting tour I've ever been on. He was always interesting, even at times I" << endl;
	cout << "thought it was going to be boring. You'd be surprised on how much history, and" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "20\n" << endl;
	cout << "how many interesting stories some of the things hold." << endl;
	cout << "    \"After the tour, I went to freshen up, and ended up being able, at the" << endl;
	cout << "king's suggestion, to wash completely. Then the servant brought me some" << endl;
	cout << "expensive, elegant, clean clothes. They took my work clothes and washed them." << endl;
	cout << "I thought that was kind of strange. Very nice, but strange." << endl;
	cout << "    \"Well, after dinner, the king takes me for a swim in the royal garden. It" << endl;
	cout << "was breathtaking. It's like it was very calming, and I could feel my troubles" << endl;
	cout << "just melting away. The king said it had been built over a hundred and fifty" << endl;
	cout << "years ago. There had been additions over the years, but the original part" << endl;
	cout << "remains the same.\"" << endl;
	cout << "    \"Sounds to me like you had quite an evening,\" said Celesta, \"I still find" << endl;
	cout << "it hard to believe it happened, but if it did, you are a very lucky woman.\"" << endl;
	cout << "    \"I'm finding it hard to believe too,\" said Demril, \"and I was there. I" << endl;
	cout << "don't think I'm going to be the same.\"" << endl;
	cout << "    \"You'll be alright,\" said Celesta, \"It'll just take a few weeks for the" << endl;
	cout << "effects to wear off. I do have just one question.\"" << endl;
	cout << "    \"What's that?\" asked Demril." << endl;
	cout << "    \"Did he kiss you?\" asked Celesta." << endl;
	cout << "    \"What?\" asked Demril, \"No, of course not.\"" << endl;
	cout << "    \"Good thing,\" said Celesta, \"If he had kissed you, you probably would've" << endl;
	cout << "been washed away for weeks.\"" << endl;
	cout << "    \"That's not funny,\" said Demril, \"True, but not funny.\"" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "21\n" << endl;
	cout << "    Celesta and Demril both laughed at the last comment." << endl;
	cout << "    \"You should've seen the garden,\" said Demril, \"It was well... very" << endl;
	cout << "different. It had several levels, all intertwined, and platforms, almost like a" << endl;
	cout << "bunch of little gardens within a big garden.\"" << endl;
	cout << "    \"Well,\" said Celesta, \"Maybe you could show me sometime.\"" << endl;
	cout << "    \"Unfortunately,\" said Demril, \"I don't think that's going to happen. This" << endl;
	cout << "was a once in a lifetime thing. It's not going to happen again.\"" << endl;
	cout << "    \"That's what you think,\" said Celesta." << endl;
	cout << "    \"What do you mean, that's what I think?\" asked Demril, \"There is no way" << endl;
	cout << "this is ever going to happen again. I mean, this is King Toran of Cosha we're" << endl;
	cout << "talking about. Like you said, I'm not exactly what would be considered royal" << endl;
	cout << "material. I work at a mineral refinery, for Poseidon's sake.\"" << endl;
	cout << "    \"Poseidon?\" asked Celesta, perplexed, \"Who in the sea is Poseidon?\"" << endl;
	cout << "    \"Never mind,\" said Demril, \"Just a name I heard in a dream.\"" << endl;
	cout << "    \"Sounds interesting,\" said Celesta, \"I've got to hear about this dream" << endl;
	cout << "sometime. But anyway, despite the fact that you're a commoner that works in a" << endl;
	cout << "refinery, I still say someone important has his eyes on you.\"" << endl;
	cout << "    \"Get real, Celesta,\" said Demril, \"Why would the king choose me? There are" << endl;
	cout << "better-dressed, more proper, and better-educated woman in the city. Why would" << endl;
	cout << "he be interested in someone like me?\"" << endl;
	cout << "    \"Look,\" said Celesta, \"I don't pretend to understand it, but think about" << endl;
	cout << "this. Of all the woman, proper or not, rich or poor, he picked you. That alone" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "22\n" << endl;
	cout << "says there's something special about you to him.\"" << endl;
	cout << "    \"Yeah, but-\" said Demril." << endl;
	cout << "    \"Okay,\" said Celesta, interrupting Demril, \"that alone might not say much," << endl;
	cout << "maybe he was bored, and you just happen to be there. Not likely, but possible." << endl;
	cout << "However, he then invites you for a royal tour of the castle. Not your ordinary" << endl;
	cout << "tour that some boring tour guide would give, but a royal tour by the king" << endl;
	cout << "himself. Then after the tour, he invites you for what was probably the best" << endl;
	cout << "meal of your life. Afterwards, he then takes you for a leisurely swim in the" << endl;
	cout << "royal garden. Trust me, you're going to see him again.\"" << endl;
	cout << "    \"Why would the king want to see me, though?\" asked Demril." << endl;
	cout << "    \"I don't know for sure,\" said Celesta, \"But I do know the king is looking" << endl;
	cout << "for someone to make queen, and I think you're the woman.\"" << endl;
	cout << "    \"How would you know if the king is looking for a queen?\" asked Demril." << endl;
	cout << "    \"It's been all over the news,\" said Celesta, \"Haven't you heard, or have" << endl;
	cout << "you been living under a shell for the past few weeks?\"" << endl;
	cout << "    \"I've heard,\" said Demril, \"but the sources weren't exactly reliable.\"" << endl;
	cout << "    \"Let me guess,\" said Celesta, \"Misty and Shelly.\"" << endl;
	cout << "    \"Well,\" said Demril, \"You know how they like to spread rumors.\"" << endl;
	cout << "    \"Well,\" said Celesta, \"this time the rumors are true.\"" << endl;
	cout << "    \"Maybe so,\" said Demril." << endl;
	cout << "    \"Trust me,\" said Celesta, \"They are. If you read the news once in a while,\"" << endl;
	cout << "you would know.\"" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "23\n" << endl;
	cout << "    \"You know I don't read the news,\" said Demril, \"because there are too many" << endl;
	cout << "depressing things in it.\"" << endl;
	cout << "    \"I know,\" said Celesta, \"but it might help to pick it up once in a while." << endl;
	cout << "This way you won't be so uninformed. The king is looking to marry, and I" << endl;
	cout << "believe you're a candidate.\"" << endl;
	cout << "    \"I don't know,\" said Demril, \"I've only seen him this once, and that" << endl;
	cout << "doesn't mean he'll choose me to be queen.\"" << endl;
	cout << "    \"I think he already has, Demril,\" said Celesta, \"I happen to know it's a" << endl;
	cout << "matter of history that royalty doesn't take their time at these matters. I've" << endl;
	cout << "got a real good feeling that says you're soon going to be queen of Cosha, and" << endl;
	cout << "as you know, my instincts are really good, and usually right.\"" << endl;
	cout << "    \"Come on, Celesta,\" said Demril, \"The king wouldn't make a decision that" << endl;
	cout << "fast. He's much more thoughtful than that.\"" << endl;
	cout << "    \"I don't know,\" said Celesta, \"but if I were you, I'd buy the nicest dress" << endl;
	cout << "I could buy, and the prettiest necklace, one with a charm, and wear them the" << endl;
	cout << "next time I saw the king.\"" << endl;
	cout << "    \"I can't do that,\" said Demril, \"Right now, I can't even afford a cheap" << endl;
	cout << "dress, never mind what you're suggesting. My budget's stretched on fixing my" << endl;
	cout << "runner. Normally I probably could afford to go and get a second-hand dress, but" << endl;
	cout << "charmlaces, even synthetic ones, don't come cheap. At the rate I'm going, it" << endl;
	cout << "would take months to come up with that kind of money.\"" << endl;
	cout << "    \"Why don't you just buy a new runner?\" asked Celesta." << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "24\n" << endl;
	cout << "    \"Because,\" answered Demril, \"A new runner would be more expensive. Look," << endl;
	cout << "this dress thing is a really good idea, and I'd probably do it if I could, but" << endl;
	cout << "on my current budget, the cost of repairs on my runner, plus the pay cut, I" << endl;
	cout << "can't afford to do it right now.\"" << endl;
	cout << "    \"Pay-cut?\" asked Celesta, \"When did you get a pay-cut?\"" << endl;
	cout << "    \"The refinery has been making cut-backs,\" said Demril, \"I didn't want to" << endl;
	cout << "tell you because I didn't want to worry you, but the refinery has been" << endl;
	cout << "laying-off a lot of employees. We've been doing more and more by machine," << endl;
	cout << "thanks to the new pressure technology. I know a lot was already done by" << endl;
	cout << "machine, but it's all becoming automated. That means less workers are needed." << endl;
	cout << "to do that, but Clean Sea Refineries has been gaining more and more water" << endl;
	cout << "against Sanlo. They wanted me to stay on, so they kept me, but cut my pay by" << endl;
	cout << "one-third. However, someone has to run the machines, right?\"" << endl;
	cout << "    \"What are they going to do?\" asked Celesta, \"train you on the machines?\"" << endl;
	cout << "    \"Nah,\" said Demril, \"I can already run the machines. They're going to do" << endl;
	cout << "something even better. In exchange for a temporary pay-cut, they want to" << endl;
	cout << "promote me to section supervisor, which means I'll be making almost twice what" << endl;
	cout << "I was making. The position is supposed to start by the end of next week.\"" << endl;
	cout << "    \"So, what's the problem?\" asked Celesta, \"It's a temporary set-back for a" << endl;
	cout << "better life. Another thing; why didn't you tell me any of this?\"" << endl;
	cout << "    \"Well,\" said Demril, \"I didn't want you to worry, and I only found about" << endl;
	cout << "the promotion today. That's why I wanted you to call me when you got home." << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "25\n" << endl;
	cout << "However, I didn't expect for the king to just pick me up out of nowhere, and" << endl;
	cout << "spend what probably was the most enchanting evening of my life with him.\"" << endl;
	cout << "    \"So,\" said Celesta, \"the pay-cut is why you're short on money, but" << endl;
	cout << "you're going to get a promotion which is going to almost double your regular" << endl;
	cout << "pay. Sounds like a pretty good exchange to me.\"" << endl;
	cout << "    \"That's what I figure,\" said Demril." << endl;
	cout << "    \"Why did you take the pay-cut to begin with?\" asked Celesta, \"I mean you" << endl;
	cout << "didn't know about the promotion, did you?\"" << endl;
	cout << "    \"Well,\" said Demril, \"First Mister Sanlo said it was temporary, and" << endl;
	cout << "second, he said he'd make it up to me. Besides, the cut wasn't that bad, and I" << endl;
	cout << "doubt I could find another job with the same pay. It's the repair costs that" << endl;
	cout << "are getting me. If this keeps up, I'm going to have to get rid of my runner." << endl;
	cout << "This is costing me in more ways than one.\"" << endl;
	cout << "    \"I see,\" said Celesta, \"Well, since you're short on money, and this is a" << endl;
	cout << "very important matter; important enough that a second hand store won't do, I'll" << endl;
	cout << "help you get the dress and charm necklace.\"" << endl;
	cout << "    \"No way,\" said Demril, \"I can't let you do that.\"" << endl;
	cout << "    \"Why not?\" asked Celesta." << endl;
	cout << "    \"Because,\" said Demril, \"you can't afford it either.\"" << endl;
	cout << "    \"Don't worry about it,\" said Celesta, \"I've got it covered.\"" << endl;
	cout << "    \"Don't worry about it?\" asked Demril, \"Consider this: The king hasn't" << endl;
	cout << "exactly made any decision I'm aware of, and I'm expecting him to choose someone" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "26\n" << endl;
	cout << "else. The king may have just wanted company. Now you're talking about spending" << endl;
	cout << "money that can be either saved, or put to better use. You can't afford to do" << endl;
	cout << "this. No offense, but you still make less than I do. If you really want to help" << endl;
	cout << "me, you can help get my vehicle fixed. Believe me, I would be much more" << endl;
	cout << "appreciative of that, and most likely can pay you back. Buying a dress and" << endl;
	cout << "charmlace isn't going to get me to work or pay my bills.\"" << endl;
	cout << "    \"So,\" said Celesta, \"what are you going to do about his majesty?\"" << endl;
	cout << "    \"I don't know,\" said Demril, \"The king's probably not going to see me," << endl;
	cout << "but if he does...\"" << endl;
	cout << "    \"If he does,\" said Celesta, \"and I believe he will, you are going to have" << endl;
	cout << "the proper attire. We're not playing around here. You're in the big league," << endl;
	cout << "Demril. You've got to make a good impression. Just because you haven't dated in" << endl;
	cout << "a long time, doesn't mean you can be indecisive about this too.\"" << endl;
	cout << "    \"With what money are we supposed to do this with?\" asked Demril, \"In case" << endl;
	cout << "you weren't listening, my pay has been cut, my runner's being fixed, and my new" << endl;
	cout << "position hasn't started yet. Now where in the ocean am I supposed to get that" << endl;
	cout << "kind of money?\"" << endl;
	cout << "    \"I'm going to loan it to you,\" said Celesta." << endl;
	cout << "    \"Where are you going to get the money from?\" asked Demril." << endl;
	cout << "    \"I already have it,\" said Celesta." << endl;
	cout << "    \"Really?\" asked Demril." << endl;
	cout << "    \"Really,\" said Celesta." << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "27\n" << endl;
	cout << "    \"Where did you get it from?\" asked Demril." << endl;
	cout << "    \"Truthfully,\" said Celesta, \"I can't tell you. But I do have the money," << endl;
	cout << "and I did obtain it legally, so you're going to get a dress and charmlace" << endl;
	cout << "tomorrow. I'll pick you up at about two-and-a-half past first light. We'll have" << endl;
	cout << "breakfast first. This is the king we're talking about, and you're going to look" << endl;
	cout << "like a princess, or at very least a lady.\"" << endl;
	cout << "    \"Are you sure you want to do this?\" asked Demril." << endl;
	cout << "    \"Absolutely,\" said Celesta." << endl;
	cout << "    \"How much do you have?\" asked Demril." << endl;
	cout << "    \"Enough,\" answered Celesta, \"I'll see you tomorrow. Be ready, we have a" << endl;
	cout << "busy day ahead, and get plenty of rest.\"" << endl;
	cout << "    \"Alright,\" said Demril, still not certain, \"I'll see you then.\"" << endl;
	cout << "    \"Good,\" said Celesta, and then hung up." << endl;
	cout << "    Celesta always hung up without saying bye. She did not believe in it, and" << endl;
	cout << "so she ended phone conversations abruptly, when the conversation was over." << endl;
	cout << "    I'll never get used to that, thought Demril." << endl;
	cout << "    Demril put down the phone, and then went to bed." << endl;
	cout << "    The next morning, Celesta picked-up Demril as scheduled. They went to a" << endl;
	cout << "nice, but well priced place for breakfast. After they ate, Celesta took Demril" << endl;
	cout << "to get the dress and charmlace." << endl;
	cout << "    Celesta was a coshen of about the same age as Demril. She had long, red" << endl;
	cout << "hair that had a slight wave to it, green eyes, and thin, bright lips. She was" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "28\n" << endl;
	cout << "about five feet and five inches tall, and had a small build. She had met Demril" << endl;
	cout << "when they had just gotten out of school, and the two had been friends since." << endl;
	cout << "    Demril spent quite some time trying various dresses on, while Celesta" << endl;
	cout << "judged them, and made suggestions. In the end, they had found the perfect dress" << endl;
	cout << "for Demril. It was elegant and simple." << endl;
	cout << "    \"I can't believe you're doing this,\" said Demril, \"I have no way of" << endl;
	cout << "paying you back.\"" << endl;
	cout << "    \"Yes, you do,\" said Celesta." << endl;
	cout << "    \"I do?\" asked Demril, skeptically, \"how?\"" << endl;
	cout << "    \"Very simple,\" said Celesta, cunningly, \"You can make me a bride's maid" << endl;
	cout << "in your royal wedding.\"" << endl;
	cout << "    Demril laughed, and then asked, \"What makes you think there's going to be a" << endl;
	cout << "royal wedding?\"" << endl;
	cout << "    Celesta paid for the dress and charmlace, and the two started to swim out" << endl;
	cout << "of the store." << endl;
	cout << "    \"I told you,\" said Celesta, \"I trust my instincts. I knew something good" << endl;
	cout << "was going to happen to you, but I never suspected this. Oh, and about your" << endl;
	cout << "job?\"" << endl;
	cout << "    \"Yes,\" said Demril." << endl;
	cout << "    \"I hate to tell you,\" said Celesta, \"and I hope I'm wrong, but I think it's" << endl;
	cout << "about to bottom out. Sanlo Refinery is going out for good.\"" << endl;
	cout << "    \"What do you mean?\" asked Demril, \"I've got a promotion coming up.\"" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "29\n" << endl;
	cout << "    \"Well,\" said Celesta, \"Last night I had this real strange, vivid dream, and" << endl;
	cout << "I think it was another vision.\"" << endl;
	cout << "    \"Let me guess,\" said Demril, becoming very concerned, \"Something real bad" << endl;
	cout << "is going to happen.\"" << endl;
	cout << "    \"Why do you say that?\" asked Celesta." << endl;
	cout << "    \"Just your approach,\" said Demril, \"It tells me you're delivering bad" << endl;
	cout << "news.\"" << endl;
	cout << "    \"Let's just put it this way,\" said Celesta, \"I saw a building that had been" << endl;
	cout << "abandoned. It had broken windows and a sign with the letters S, A, then two" << endl;
	cout << "missing letters, then O. Then below were parts of the word refinery.\"" << endl;
	cout << "    \"That could mean anything,\" said Demril, \"You don't know when that takes" << endl;
	cout << "place, and from the sound of the dream, it seems that happens in the distant," << endl;
	cout << "not near, future.\"" << endl;
	cout << "    Celesta and Demril exited the store, and swam toward Celesta's runner." << endl;
	cout << "    Celesta's runner was a small, powder blue economy runner, which, unlike the" << endl;
	cout << "more expensive models that were propelled by jets, was moved by propellers. It" << endl;
	cout << "had a three-passenger capacity and was very fuel-efficient." << endl;
	cout << "    \"That wasn't all,\" said Celesta, \"After that, I was taken to a strange, but" << endl;
	cout << "beautiful place I had never been before. You and somebody I couldn't quite make" << endl;
	cout << "out, but I think it was the king, were getting married.\"" << endl;
	cout << "    \"Now you're just teasing,\" said Demril." << endl;
	cout << "    \"No I'm not,\" said Celesta, \"Why else would I be urging you to do this? Why" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "30\n" << endl;
	cout << "would I be so sure this is going to happen? Not only that, last night wasn't" << endl;
	cout << "the first time I had that sort of dream, so I'm real sure about this.\"" << endl;
	cout << "    \"I don't know,\" said Demril, as she and Celesta got in the runner." << endl;
	cout << "    \"There you have it,\" said Celesta." << endl;
	cout << "    \"Still,\" said Demril, \"You haven't explained why you suddenly think I'm" << endl;
	cout << "going to loose my job.\"" << endl;
	cout << "    \"Well,\" said Celesta, \"I don't think you're going to like this.\"" << endl;
	cout << "    \"But...\" said Demril, waiting for Celesta to tell her the rest." << endl;
	cout << "    \"Are you sure you want to hear this?\" asked Celesta." << endl;
	cout << "    \"Yes,\" said Demril, \"If something bad's going to happen, I want to know" << endl;
	cout << "about it.\"" << endl;
	cout << "    \"Okay,\" said Celesta, hesitantly, \"I also saw Mister Sanlo dead, and the" << endl;
	cout << "date on the coffin was the day after tomorrow, at the twenty-sixth hour.\"" << endl;
	cout << "    There was a moment of silence as Celesta started driving to their next" << endl;
	cout << "destination." << endl;
	cout << "    \"So,\" said Demril, \"You're telling me that Mister Sanlo is going to die?" << endl;
	cout << "What about the refinery? That shouldn't shut down just because of that.\"" << endl;
	cout << "    \"It's a private refinery,\" said Celesta, \"As you know, private refineries" << endl;
	cout << "are quickly loosing water against those huge industrial refineries owned by big" << endl;
	cout << "companies. I don't believe the refinery's going to make it without Mister" << endl;
	cout << "Sanlo. It's a real shame, he seems to be a really nice guy, and he's been one" << endl;
	cout << "of the strongest oppositions of big companies coming in and taking over. It'll" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "31\n" << endl;
	cout << "be sad to see it go.\"" << endl;
	cout << "    \"Are you sure about this?\" asked Demril, feeling the dread that Celesta was" << endl;
	cout << "probably right." << endl;
	cout << "    \"Absolutely,\" said Celesta, \"The refinery is already losing both money" << endl;
	cout << "and employees, as you know, and once Mister Sanlo dies, there'll be nothing to" << endl;
	cout << "keep Sanlo Refinery going.\"" << endl;
	cout << "    \"That's awful, Celesta!\" said Demril, \"Why did you tell me this?\"" << endl;
	cout << "    \"Ahh, the troubles of the fortunetellers,\" said Celesta." << endl;
	cout << "    \"What?\" asked Demril, not quite understanding her friend's comment." << endl;
	cout << "    \"The troubles of the fortunetellers,\" said Celesta, \"You asked me to tell" << endl;
	cout << "you what is going to happen, and after you're told, you get upset if it doesn't" << endl;
	cout << "make you happy. Why do you ask, if you don't want to accept the" << endl;
	cout << "disappointment?\"" << endl;
	cout << "    \"I didn't ask,\" said Demril, \"You just told me.\"" << endl;
	cout << "    \"Partially true,\" said Celesta, correcting Demril, \"You asked me some" << endl;
	cout << "information, and I volunteered some. Besides, if I didn't tell you, and it" << endl;
	cout << "happened, then you found out I knew ahead of time, you would've been mad at me" << endl;
	cout << "for not telling you in the first place.\"" << endl;
	cout << "    \"Okay,\" said Demril, realizing that Celesta was right, \"You have a point. I" << endl;
	cout << "would have been very upset if you hadn't told me, and I found out you knew. Is" << endl;
	cout << "there anything I can do about this?\"" << endl;
	cout << "    \"I don't think so,\" said Celesta, \"The vision was clear, which usually" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "32\n" << endl;
	cout << "means it's pretty much carved in coral.\"" << endl;
	cout << "    \"In that case,\" said Demril, \"I'd better get a head start on finding a new" << endl;
	cout << "job. Where are we going anyway?\"" << endl;
	cout << "    \"To find you accessories,\" said Celesta." << endl;
	cout << "    Celesta drove Demril to a nice shop where such accessories were sold, and" << endl;
	cout << "bought some that matched, and looked beautiful with what Demril would be" << endl;
	cout << "wearing. Afterwards, they drove out somewhere away from the city to hang out" << endl;
	cout << "for a few hours and talk girl-talk. They talked a bit more about Celesta's" << endl;
	cout << "vision, and the supposedly upcoming wedding. They also talked about other" << endl;
	cout << "things, including a male coshen that Celesta had a crush on, but did not seem" << endl;
	cout << "to know she even existed. After all that, Celesta drove Demril home, and then" << endl;
	cout << "went home herself." << endl;
	cout << "    Everything about Demril's job went according to what Celesta had said." << endl;
	cout << "Mister Sanlo died exactly when Celesta's vision had predicted, and the refinery" << endl;
	cout << "shut down soon after, leaving Demril out of a job." << endl;
	cout << "    With little other skills, and low demand for what skills she did have," << endl;
	cout << "Demril was finding it difficult to find employment. She continued looking for" << endl;
	cout << "jobs over the next few days. The king did not seem to be attempting to contact" << endl;
	cout << "her, and she was beginning to think Celesta was wrong, and she had wasted the" << endl;
	cout << "money on the things they bought. She also was forced to sell her runner, being" << endl;
	cout << "unable to afford what it would cost for repairs, and was considering selling" << endl;
	cout << "the dress and charmlace, but after talking to Celesta, she could not bring" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "33\n" << endl;
	cout << "herself to do it." << endl;
	cout << "    Demril was getting ready to go out and find a job again, when her door" << endl;
	cout << "chimes rang." << endl;
	cout << "    Who could that be? she wondered." << endl;
	cout << "    Demril went and opened the door to find an important-looking man there." << endl;
	cout << "    \"Can I help you?\" asked Demril." << endl;
	cout << "    \"Lady Demril?\" asked the man." << endl;
	cout << "    \"Yes?\" responded Demril." << endl;
	cout << "    Demril looked beyond the man to see an official-looking jet-runner that" << endl;
	cout << "looked similar to the last one she was in. There were two important-looking men" << endl;
	cout << "on either side of the opened rear passenger's side door. They seemed to be just" << endl;
	cout << "waiting." << endl;
	cout << "    \"Did I do something wrong?\" asked Demril." << endl;
	cout << "    \"Not that I'm aware of,\" said the man, \"I was sent to inform you that your" << endl;
	cout << "presence is requested by his majesty, King Toran, at the royal castle tomorrow" << endl;
	cout << "at the fifth hour of light.\"" << endl;
	cout << "    Demril's heart started to beat faster in anticipation. She tried to speak," << endl;
	cout << "but found it hard to do so." << endl;
	cout << "    \"What shall I tell his majesty?\" asked the man." << endl;
	cout << "    \"Uh,\" said Demril, calming herself, \"Tell his majesty I will be there.\"" << endl;
	cout << "    \"Very well,\" said the man." << endl;
	cout << "    The man then turned and left." << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "34\n" << endl;
	cout << "    Demril closed the door and started to wonder." << endl;
	cout << "    Maybe the king likes me after all, thought Demril, Maybe Celesta was right," << endl;
	cout << "after all, she's been right up to now. Maybe the king does like me." << endl;
	cout << "    Demril went over to her shell-like phone, and called Celesta." << endl;
	cout << "    \"Hello?\" answered Pinel, after a couple of rings." << endl;
	cout << "    \"Is Celesta there?\" asked Demril." << endl;
	cout << "    \"Who's calling?\" asked Pinel, suspecting Demril." << endl;
	cout << "    \"It's me, Demril,\" answered Demril." << endl;
	cout << "    \"Hey, Demril,\" said Pinel, \"What's happening?\"" << endl;
	cout << "    \"Did Celesta tell you about my evening with the king?\" asked Demril." << endl;
	cout << "    \"Kind of,\" said Pinel, \"Something about having dinner and going for a walk" << endl;
	cout << "in the garden. The details were a bit sketchy, and Celesta wouldn't tell me" << endl;
	cout << "more. Why?\"" << endl;
	cout << "    \"Well,\" said Demril, \"You basically heard right. However, now he wants to" << endl;
	cout << "see me again.\"" << endl;
	cout << "    \"Are you serious?\" asked Pinel." << endl;
	cout << "    \"Yes I am,\" said Demril, \"Now, can I talk to Celesta?\"" << endl;
	cout << "    \"Hang on,\" said Pinel, \"You girls are going to tell me about this, right?\"" << endl;
	cout << "    \"You bet,\" said Demril." << endl;
	cout << "    \"Good,\" said Pinel, \"Hold on, I'll get Celesta.\"" << endl;
	cout << "    There were a couple moments of silence before Celesta spoke on the phone." << endl;
	cout << "    \"Hey Demril,\" said Celesta, \"what's going on? Find a job yet?\"" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "35\n" << endl;
	cout << "   \"No, not yet,\" said Demril, \"I'm still working on it. It's tough to find a" << endl;
	cout << "job when all you have are skills that aren't in demand. But that's not why I'm" << endl;
	cout << "calling.\"" << endl;
	cout << "    \"Then why did you call?\" asked Celesta, suspecting Demril was up to" << endl;
	cout << "something." << endl;
	cout << "    \"Only to let you know that the king wants to see me tomorrow on the fifth" << endl;
	cout << "hour of light,\" responded Demril." << endl;
	cout << "    \"Really?\" asked Celesta, \"What did I tell you?\"" << endl;
	cout << "    \"Okay,\" said Demril, \"maybe your visions are right. I mean, the ones about" << endl;
	cout << "my job were, what's to say the others aren't?\"" << endl;
	cout << "    \"Right,\" said Celesta, sounding as if not all was right." << endl;
	cout << "    \"What's that supposed to mean?\" asked Demril, noticing Celesta's tone." << endl;
	cout << "    \"What do you mean?\" asked Celesta." << endl;
	cout << "    \"I heard how you said that.\" said Demril." << endl;
	cout << "    \"It's nothing,\" said Celesta, covering herself, \"You're going to wear the" << endl;
	cout << "dress and charmlace, right?\"" << endl;
	cout << "    There was a brief moment of silence, before Demril spoke again." << endl;
	cout << "    \"Yes,\" she finally said, \"Yes I am, though I'm not so sure I should.\"" << endl;
	cout << "    \"What do you mean you're not so sure you should?\" asked Celesta, \"Of course" << endl;
	cout << "you should. That's why we bought it, remember?\"" << endl;
	cout << "    \"I know,\" said Demril, \"but I don't want to overdress for the occasion.\"" << endl;
	cout << "    \"Trust me,\" said Celesta, \"You're not. The king won't be courting you for" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "36\n" << endl;
	cout << "long, and you want him to know you can be elegant and simple, while having some" << endl;
	cout << "strength to. He's seen your strength, now it's time to show the king your" << endl;
	cout << "elegance.\"" << endl;
	cout << "    \"I have no idea what you're talking about,\" said Demril, \"but I'll do as" << endl;
	cout << "you suggest. I just hope you're right.\"" << endl;
	cout << "    \"Look,\" said Celesta, \"Do you want to spend your life in average or below" << endl;
	cout << "jobs, making less pay than you have, or do you want to live the dream?\"" << endl;
	cout << "    \"Dream?\" asked Demril, \"Some dream. Look this way, talk this way, walk this" << endl;
	cout << "way, be so prim and proper, don't break a nail...\" Demril drifted off in" << endl;
	cout << "sarcasm." << endl;
	cout << "    \"Yep,\" said Celesta, \"Having servants wait on you hand and fin, getting" << endl;
	cout << "nail care, hair care, and getting totally pampered, not to mention wearing" << endl;
	cout << "expensive, fancy clothes, and having the king himself as your lover, oh yes," << endl;
	cout << "and being next to get the throne. That's right; if the king dies, the throne" << endl;
	cout << "automatically goes to the queen, then the prince. I don't know, Demril, Most of" << endl;
	cout << "us only dream of the kind of life fate presents you. If I were you, I'd stop" << endl;
	cout << "complaining and worrying, and start making the best of this. Even if the king" << endl;
	cout << "decides that you're not the one, you still have something most women only dream" << endl;
	cout << "of - you went out with the king.\"" << endl;
	cout << "    \"Okay,\" said Demril, \"You're right. I'm going to make the best of this" << endl;
	cout << "while it lasts.\"" << endl;
	cout << "    \"As you should,\" said Celesta, \"Trust me, this is only the beginning.\"" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "37\n" << endl;
	cout << "    \"I don't understand,\" said Demril, \"How can you be so sure? Talking to you," << endl;
	cout << "it's like it's carved in coral.\"" << endl;
	cout << "    \"Trust me,\" said Celesta, \"When I get visions this vivid, they usually" << endl;
	cout << "happen. You are going to marry the king...\"" << endl;
	cout << "    Celesta went silent, and Demril got the feeling there was something wrong" << endl;
	cout << "with her closest friend." << endl;
	cout << "    \"Celesta,\" Demril said, \"Is everything okay?\"" << endl;
	cout << "    \"Yah,\" said Celesta, \"It's nothing. Look, I've got to go. I'm taking Pinel" << endl;
	cout << "out shopping, and probably won't be back until late, okay?\"" << endl;
	cout << "    \"No problem,\" said Demril, \"Are you sure every thing's alright? Because I" << endl;
	cout << "get a sense there's something wrong.\"" << endl;
	cout << "    \"Nothing's wrong,\" said Celesta reassuring Demril, \"Everything is fine." << endl;
	cout << "It's just... I'll talk to you later.\"" << endl;
	cout << "    \"I know there's something you're not telling me,\" said Demril, \"I know you" << endl;
	cout << "too well.\"" << endl;
	cout << "    \"Like I said,\" said Celesta, \"it's nothing.\"" << endl;
	cout << "    \"Like I said, I know you better than that,\" said Demril, \"Is something else" << endl;
	cout << "supposed to happen? You can tell me. I promise I won't get mad.\"" << endl;
	cout << "    \"I don't know,\" said Celesta, \"It's not something I care to think about.\"" << endl;
	cout << "    \"Maybe talking about it will help,\" said Demril, \"I mean if something was" << endl;
	cout << "bothering me this much, I would tell you, if anything just to have someone there" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "38\n" << endl;
	cout << "to listen.\"" << endl;
	cout << "    \"You know what they say about knowing too much about your own future...\"" << endl;
	cout << "said Celesta." << endl;
	cout << "    \"Does something happen to you?\" asked Demril, going with her instincts." << endl;
	cout << "    \"You might say that,\" said Celesta." << endl;
	cout << "    \"Well, if you tell me, maybe we can prevent it from happening,\" said" << endl;
	cout << "Demril." << endl;
	cout << "    \"No, this was too vivid,\" said Celesta, \"It's definitely going to happen.\"" << endl;
	cout << "    \"Well, what is it?\" asked Demril, \"You'll probably feel better if you talk" << endl;
	cout << "about it.\"" << endl;
	cout << "    Celesta hesitated for a while, realizing Demril was right. She would feel a" << endl;
	cout << "bit better after talking about it." << endl;
	cout << "    \"I saw my own death,\" Celesta finally said." << endl;
	cout << "    \"What?\" asked Demril surprised, and concerned." << endl;
	cout << "    \"Yep,\" said Celesta, \"The good thing is it wasn't too bad, and the bad" << endl;
	cout << "thing is, it's going to be within the year. I think I'm going to get real sick" << endl;
	cout << "or something.\"" << endl;
	cout << "    \"Oh my goodness,\" said Demril, \"Do you feel well now?\"" << endl;
	cout << "    \"Yah,\" said Celesta, \"I feel fine. I'm going to get a check-up as soon as I" << endl;
	cout << "can, but I don't think I'll be able to stop it.\"" << endl;
	cout << "    \"That's awful,\" said Demril, \"You're not that old either.\"" << endl;
	cout << "    \"At least I know where I'm going to be buried,\" said Celesta in a lighter" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "39\n" << endl;
	cout << "tone." << endl;
	cout << "    \"Where?\" asked Demril." << endl;
	cout << "    \"Rhine Cemetery,\" said celesta, \"that's another reason why I'm sure you're" << endl;
	cout << "going to marry the king. The only people buried in a royal cemetery are royal" << endl;
	cout << "members, or very close friends. It also means I'm going to at least get a taste" << endl;
	cout << "of royalty.\"" << endl;
	cout << "    \"Why didn't you tell me about this earlier?\" asked Demril." << endl;
	cout << "    \"Like I said,\" said Celesta, \"I don't care to think about it, though I" << endl;
	cout << "can't really help it, either. That and I didn't want you to worry about me.\"" << endl;
	cout << "    \"I'm your best friend,\" said Demril, \"Of course I'm going to be concerned," << endl;
	cout << "but I promise not to worry.\"" << endl;
	cout << "    \"Good,\" said Celesta, \"and don't you dare treat me any differently. That" << endl;
	cout << "especially means no walking on egg shells, or special treatment.\"" << endl;
	cout << "    \"Well,\" said Demril, \"I promise not to walk on eggshells, but I do think" << endl;
	cout << "you should get special treatment. I mean I've got probably another sixty years" << endl;
	cout << "or so. I think you should take this time and do everything you always wanted" << endl;
	cout << "to. You're not going to get another chance, after all.\"" << endl;
	cout << "    \"When you put it that way,\" said Celesta, \"it seems like a nice idea. Look," << endl;
	cout << "I've got to go. Let me know how it turns out with his majesty.\"" << endl;
	cout << "    \"Sure will,\" said Demril, \"bye.\"" << endl;
	cout << "    Celesta hung up the phone." << endl;
	cout << "    There she goes again, thought Demril after Celesta's usual abrupt hang-up," << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "40\n" << endl;
	cout << "at least I got in a bye, though." << endl;
	cout << "    From then forth, Demril was going to make the best of their friendship," << endl;
	cout << "knowing there was not much time left for Celesta." << endl;
	cout << "    The next morning, Demril prepared for her date with the king. She ate" << endl;
	cout << "breakfast, washed up real good, then put on the dress and charmlace that she" << endl;
	cout << "and Celesta had bought." << endl;
	cout << "    She was getting ready to leave, when there was a knock at her front door." << endl;
	cout << "She opened the door to see the same important-looking man she had seen the day" << endl;
	cout << "before. It was exactly like the previous day; the exact same man wearing" << endl;
	cout << "exactly the same outfit, the same jet-runner parked in the same place with the" << endl;
	cout << "same two men standing in the same exact place they had been the day before." << endl;
	cout << "Demril knew they had left the previous day, and was amused at the accuracy of" << endl;
	cout << "the repetition. It was done neatly and precise, as if they had memorized" << endl;
	cout << "exactly where to park the jet-runner, and exactly where to stand." << endl;
	cout << "    \"Are you ready, Lady Demril?\" asked the gentleman at her door." << endl;
	cout << "    Lady. A title used for very important woman who either owned or had" << endl;
	cout << "husbands who owned important parts of the waters. It was also a term used for" << endl;
	cout << "women who were close to royalty. This title had been given to Demril by the" << endl;
	cout << "king almost immediately after he met her. Demril felt awkwardly special hearing" << endl;
	cout << "the title with her name." << endl;
	cout << "    \"Yes, I am,\" said Demril, \"Can I just lock-up first?\"" << endl;
	cout << "    \"Of course,\" said the man." << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "41\n" << endl;
	cout << "    Demril made sure the lights were out and then locked her home. She was" << endl;
	cout << "escorted to the jet-runner, and then helped in. The other two men got in and" << endl;
	cout << "sat on side of her, and the third got in the front passenger side. The driver" << endl;
	cout << "brought them to the castle, where she was greeted by yet another important" << endl;
	cout << "looking man, who helped her out of the vehicle, then escorted her into the" << endl;
	cout << "castle to the main hall." << endl;
	cout << "    \"The king will be with you shortly,\" said the man, \"Please wait here.\"" << endl;
	cout << "    The man walked away, leaving Demril alone to wait for the king." << endl;
	cout << "    A few minutes later, the king entered the hall and greeted her." << endl;
	cout << "    \"Hello, Demril,\" he said." << endl;
	cout << "    \"Your majesty,\" said Demril, paying her respects to the king." << endl;
	cout << "    The king took her hand and gently helped her up." << endl;
	cout << "    \"You look radiant,\" said the king." << endl;
	cout << "    \"Thank you,\" said Demril, blushing slightly." << endl;
	cout << "    The king spent most of the day with Demril. They went to an expensive" << endl;
	cout << "restaurant, and shopping at the finest stores, and then they went for a long" << endl;
	cout << "ride away from the city." << endl;
	cout << "    Demril and the king enjoyed each other's company, and it was that day the" << endl;
	cout << "king made his mind to marry her. The next time he was going to see her, he" << endl;
	cout << "would tell her." << endl;
	cout << "    Or should I tell her now? thought the king." << endl;
	cout << "    Time was running out, as the day was wearing on. The king knew he had to" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "42\n" << endl;
	cout << "make a decision on when to tell her by the end of that day." << endl;
	cout << "    Demril was glad that Celesta had insisted she get the dress and charmlace." << endl;
	cout << "As expensive as they were, they seemed to have made a very good impression on" << endl;
	cout << "the king." << endl;
	cout << "    By the end of the day, the king had decided he was going to see Demril some" << endl;
	cout << "more before asking her hand in marriage. He wanted to be sure about his" << endl;
	cout << "decision before he actually married her. There was not much time, though, and" << endl;
	cout << "the king knew he would have to tell her soon. The Coshens were on the brink of" << endl;
	cout << "making contact with the Lorans, and once that was underway, the king would be" << endl;
	cout << "very busy, especially if all went well." << endl;
	cout << "    The king saw Demril a couple times more, and the fourth time he saw her, he" << endl;
	cout << "asked for her hand in marriage. Demril gladly and graciously accepted, and the" << endl;
	cout << "wedding was three days later." << endl;
	cout << "    Celesta's visions had come true. First the ones about Sanlo Refineries, and" << endl;
	cout << "now the one about Demril's marriage to the king. Demril kept her promise to" << endl;
	cout << "Celesta, and made her a bridesmaid in the wedding. Celesta's friendship with" << endl;
	cout << "the new queen got her an important position in the royal structure." << endl;
	cout << "    Unfortunately, though, Celesta's position was short-lived. Four months" << endl;
	cout << "after Demril's wedding, Celesta suddenly and mysteriously became very ill. The" << endl;
	cout << "doctors said there was nothing that could be done, and it would only be a" << endl;
	cout << "matter of time before Celesta passed on. Six months after she fell ill, Celesta" << endl;
	cout << "died. Still, she left Demril with the feeling that her death was not the" << endl;
	system ("pause");
	system ("cls");
	cout << titlep << "43\n" << endl;
	cout << "terrible thing that was going to happen. Celesta started to tell Demril just" << endl;
	cout << "before her death what was supposed to happen, but did not have the time to" << endl;
	cout << "finish. All Demril knew was that in four years, something bad was going to" << endl;
	cout << "happen, but to whom and where, she did not know. Celesta had taken the secret" << endl;
	cout << "with her to her grave." << endl;
	cout << "    It was a very sad time for Demril and those who knew Celesta. The two were" << endl;
	cout << "like sisters to one another. Demril grieved for seven months, and then moved" << endl;
	cout << "on." << endl;
	cout << "    The king loved Queen Demril more than anything or anyone else. Even though" << endl;
	cout << "his duties were taking a lot of his time, he never forgot about the queen, and" << endl;
	cout << "always found a way to make time for her. The queen was often found by the" << endl;
	cout << "king's side, and would advise him on important issues. She seemed to be with" << endl;
	cout << "him almost all of the time, except when the king journeyed outside the main" << endl;
	cout << "city." << endl;
	cout << "    This was for security purposes. The trips could be dangerous at times, and" << endl;
	cout << "sometimes led him into shallow waters, where he would have to be careful of" << endl;
	cout << "sharks and being detected by land-dwellers.\n\n\n\n\n" << endl;
	system ("pause");
	menu();
	return 0;
}
