#include <iostream>
#include "menu.h"

using namespace std;

void progress()
{
	system ("cls");
	cout << "The Princess    -     Progress\n" << endl;
	cout << ">>Version 1.0<<\n" << endl;
	cout << "12-23-2006" << endl;
	cout << "    Made the help file" << endl;
	cout << "    Added the Table of Contents" << endl;
	cout << "    Added the Prophesy" << endl;
	cout << "    Added Characters Pages" << endl;
	cout << "    Added the Prologue" << endl;
	cout << "    Added Chapter 1" << endl;
	cout << "12-24-2006" << endl;
	cout << "    Added chapters 2 through 18" << endl;
	cout << "02-09-2007" << endl;
	cout << "    Re-copied Chapter 1" << endl;
	cout << "    Separated some of the prologue into separate frames" << endl;
	cout << "02-13-2007" << endl;
	cout << "    Got rid of the prophesy" << endl;
	cout << "02-23-2007" << endl;
	cout << "    Copied entire book into program" << endl;
	cout << "    Split the chapters into separate frames - one for each chapter" << endl;
	cout << "    Finished Chapter 20" << endl;
	cout << "    Split up some more of the prologue" << endl;
	cout << "    No more character sheet" << endl;
	system("pause");
	system ("cls");
	cout << "The Princess    -     Progress (cont.)\n" << endl;
	cout << "02-27-2007" << endl;
	cout << "    Finished prologue" << endl;
	cout << "    Worked some more on splitting up Chapter 1" << endl;
	cout << "02-28-2007" << endl;
	cout << "    Added sound to prologue" << endl;
	cout << "03-01-2007" << endl;
	cout << "    Put sound in the rest of book; now there is a sound when you click the" << endl;
	cout << "arrows and the table of contents buttons" << endl;
	cout << "03-02-2007" << endl;
	cout << "    Finished up Chapters 1 through 6" << endl;
	cout << "    Started Chapter 7" << endl;
	cout << "03-07-2007" << endl;
	cout << "    Finished Chapters 7 through 10" << endl;
	cout << "    Did some minor adjustments to the program itself" << endl;
	cout << "03-08-2007" << endl;
	cout << "    Finished chapters 11 through 13" << endl;
	cout << "03-09-2007" << endl;
	cout << "    Finished chapter 14" << endl;
	cout << "    Worked on chapter 15" << endl;
	cout << "03-10-2007" << endl;
	cout << "    Finished the program" << endl;
	cout << "03-21-2007" << endl;
	system("pause");
	system ("cls");
	cout << "The Princess    -     Progress (cont.)\n" << endl;
	cout << "    Changed the fonts up to the first frame of Chapter 7 to Times New Roman" << endl;
	cout << "because the print was not defined for some reason" << endl;
	cout << "    Fixed frame appearance of Chapter 2" << endl;
	cout << "03-23-2007" << endl;
	cout << "    Defined the fonts up to Chapter 14" << endl;
	cout << "    Got rid of the sounds" << endl;
	cout << "    Fixed frame appearance to Chapter 8" << endl;
	cout << "03-27-2007" << endl;
	cout << "    Fixed Events and fonts up to Chapter 15" << endl;
	cout << "    Events are now global (except for Table of Contents)" << endl;
	cout << "03-30-2007" << endl;
	cout << "    Finished defining the fonts" << endl;
	cout << "    Fixed the rest of the frames for display" << endl;
	cout << "04-17-2007" << endl;
	cout << "    Decided to put sounds on all the buttons" << endl;
	cout << "    Changed the icon" << endl;
	cout << "_______________________________________________________________________________\n" << endl;
	cout << ">>Version 1.1<<\n" << endl;
	cout << "" << endl;
	cout << "" << endl;
	system("pause");
	system ("cls");
	cout << "The Princess    -     Progress (cont.)\n" << endl;
	cout << "07-29-2007" << endl;
	cout << "    Changed one of the sounds" << endl;
	cout << "    Redid some of the prologue" << endl;
	cout << "    Changed the program icon" << endl;
	cout << "07-30-2007" << endl;
	cout << "    Worked some more on the prologue" << endl;
	cout << "07-31-2007" << endl;
	cout << "    Changed one of the sounds" << endl;
	cout << "    Worked more on the prologue" << endl;
	cout << "    Added some effects" << endl;
	cout << "08-04-2007" << endl;
	cout << "    Added music" << endl;
	cout << "    Added Copyright frame" << endl;
	cout << "09-24-2007" << endl;
	cout << "    Worked some more on rearranging the prologue" << endl;
	cout << "    Changed some sounds" << endl;
	cout << "    Made some corrections" << endl;
	cout << "10-01-2007" << endl;
	cout << "    Worked more on the prologue" << endl;
	cout << "10-02-2007" << endl;
	cout << "    Worked a little more on fixing the prologue" << endl;
	cout << "Checked over the rest - decided it was not worth fixing" << endl;
	system("pause");
	system ("cls");
	cout << "The Princess    -     Progress (cont.)\n" << endl;
	cout << ">>Version 1.2<<\n" << endl;
	cout << "10-23-2007" << endl;
	cout << "    Changed the display size from 800x600 to 640x480 (was having display" << endl;
	cout << "problems on some systems) - will have to redo everything" << endl;
	cout << "    Redid some of the prologue" << endl;
	cout << "10-27-2007" << endl;
	cout << "    Got rid of intro picture " << endl;
	cout << "    Changed the color display to 256 colors" << endl;
	cout << "    Redid some more of the prologue" << endl;
	cout << "11-01-2007" << endl;
	cout << "    Worked on some more of the prologue" << endl;
	cout << "11-03-2007" << endl;
	cout << "    Changed the menu a little" << endl;
	cout << "    Finished fixing the prologue" << endl;
	cout << "    Started fixing Chapter 1" << endl;
	cout << "    Changed the intro a bit" << endl;
	cout << "11-04-2007" << endl;
	cout << "    Did some more fixing of Chapter 1" << endl;
	cout << "11-14-2007" << endl;
	cout << "    Finished fixing Chapter 1" << endl;
	cout << "    Fixed the end screen" << endl;
	system("pause");
	system ("cls");
	cout << "The Princess    -     Progress (cont.)\n" << endl;
	cout << "    Started on Chapter 2" << endl;
	cout << "11-15-2007" << endl;
	cout << "    Finished Chapter 2 through 4" << endl;
	cout << "    Started on Chapter 5" << endl;
	cout << "11-17-2007" << endl;
	cout << "    Finished the rest of the chapters" << endl;
	cout << "_______________________________________________________________________________\n" << endl;
	cout << ">>Version 1.3<<\n" << endl;
	cout << "11-16-2007" << endl;
	cout << "    Started programing the book in visual basic" << endl;
	cout << "    Started on the prologue" << endl;
	cout << "11-17-2007" << endl;
	cout << "    Finished the Prologue" << endl;
	cout << "    Started on Chapter 1" << endl;
	cout << "11-18-2007" << endl;
	cout << "    Finished Chapter 1" << endl;
	cout << "    Started Chapter 2" << endl;
	cout << "    Worked on the splash screen - Turned it to blue" << endl;
	cout << "    Worked on the Table of Contents" << endl;
	cout << "11-19-2007" << endl;
	system("pause");
	system ("cls");
	cout << "The Princess    -     Progress (cont.)\n" << endl;
	cout << "    Finished Chapter 2 through 4" << endl;
	cout << "    Started Chapter 5" << endl;
	cout << "    Worked on the splash screen - turned it white" << endl;
	cout << "    Worked on the Table of Contents" << endl;
	cout << "11-20-2007" << endl;
	cout << "    Finished Chapters 5 through 8" << endl;
	cout << "    Started on Chapter 9" << endl;
	cout << "11-21-2007" << endl;
	cout << "    Finished Chapters 9 through 12" << endl;
	cout << "11-22-2007" << endl;
	cout << "    Finished Chapters 13 through 15" << endl;
	cout << "11-23-2007" << endl;
	cout << "    Finished the program" << endl;
	cout << "11-24-2007" << endl;
	cout << "    Made some changes to the story" << endl;
	cout << "11-25-2007" << endl;
	cout << "    Made some changes" << endl;
	cout << "11-28-2007" << endl;
	cout << "    Made some more changes" << endl;
	cout << "11-29-2007" << endl;
	cout << "    Made even more changes" << endl;
	cout << "12-01-2007" << endl;
	system("pause");
	system ("cls");
	cout << "The Princess    -     Progress (cont.)\n" << endl;
	cout << "    Added help screen" << endl;
	cout << "    Changed the icons" << endl;
	cout << "12-03-2007" << endl;
	cout << "    Made some changes to the story" << endl;
	cout << "12-05-2007" << endl;
	cout << "    Made some more changes" << endl;
	cout << "    Made some more changes to Chapter 1; had to add a new screen" << endl;
	cout << "12-10-2007" << endl;
	cout << "    Made some more story changes" << endl;
	cout << "    Started changing the page numbers" << endl;
	cout << "    Fixed the rest of the page numbers" << endl;
	cout << "    Checked some of the Grammar and spelling" << endl;
	cout << "12-11-2007" << endl;
	cout << "    Made some changes" << endl;
	cout << "12-17-2007" << endl;
	cout << "    Added and changed a couple of things" << endl;
	cout << "12-19-2007" << endl;
	cout << "    Made some more changes to the story" << endl;
	cout << "12-25-2007" << endl;
	cout << "    Made some changes to the story" << endl;
	cout << "12-27-2007" << endl;
	cout << "    Made some technical changes" << endl;
	system("pause");
	system ("cls");
	cout << "The Princess    -     Progress (cont.)\n" << endl;
	cout << "02-23-2007" << endl;
	cout << "    Changed the menu some" << endl;
	cout << "    Made some changes to the story" << endl;
	cout << "03-20-2008" << endl;
	cout << "    Made some more changes to the story" << endl;
	cout << "03-24-2008" << endl;
	cout << "    Finished making changes to the story" << endl;
	cout << "    Fixed the splash screen" << endl;
	cout << "03-25-2008" << endl;
	cout << "    Made some cosmetic changes to the program" << endl;
	cout << "_______________________________________________________________________________\n" << endl;
	cout << ">>Version 1.4<<\n" << endl;
	cout << "01/01/2012" << endl;
	cout << "    Worked on the prologue and Batch files" << endl;
	cout << "02-02-2012" << endl;
	cout << "    Made the about and progress files" << endl;
	cout << "02-03-2012" << endl;
	cout << "    Worked on the about and history files" << endl;
	cout << "02-04-2012" << endl;
	cout << "    Worked some more on the history files" << endl;
	system("pause");
	system ("cls");
	cout << "The Princess    -     Progress (cont.)\n" << endl;
	cout << "02-09-2012" << endl;
	cout << "    Compiled some more of the prologue" << endl;
	cout << "    Worked some more on converting the progress file to C++" << endl;
	cout << "    Had to fix all the projects for \"The Princess\"" << endl;
	cout << "02-10-2012" << endl;
	cout << "    Compiled more of the prologue" << endl;
	cout << "02-23-2012" << endl;
	cout << "    Worked on the prologue a bit" << endl;
	cout << "02-24-2012" << endl;
	cout << "    Worked on the prologue" << endl;
	cout << "02-15-2012" << endl;
	cout << "    Worked on sections 5 through 10 of the prologue" << endl;
	cout << "02-29-2011" << endl;
	cout << "    Worked a bit on the Prologue" << endl;
	cout << "04-23-2012" << endl;
	cout << "    Worked some more on the prologue" << endl;
	cout << "    Finished up to page 16" << endl;
	cout << "06-26-2012" << endl;
	cout << "    Worked on the prologue some more" << endl;
	cout << "06-27-2012" << endl;
	cout << "    Did some more work on the prologue" << endl;
	cout << "    Finished up to page 18" << endl;
	system("pause");
	system ("cls");
	cout << "The Princess    -     Progress (cont.)\n" << endl;
	cout << "07-11-2012" << endl;
	cout << "    Worked on the prologue" << endl;
	cout << "    Finished up to page 20" << endl;
	cout << "    Recompiled the prologue to reflect updates" << endl;
	cout << "08-15-2012" << endl;
	cout << "    Finished up to page 20" << endl;
	cout << "    Did some more work on the Prologue" << endl;
	cout << "    Split the rest of the chapters from the main .docx file" << endl;
	cout << "    Recompiled the Prologue to reflect changes" << endl;
	cout << "08-16-2012" << endl;
	cout << "    Worked on some more of the prologue" << endl;
	cout << "    Finished to Page 23" << endl;
	cout << "    Recompiled the Prologue to reflect changes" << endl;
	cout << "10-01-2012" << endl;
	cout << "    Worked on the prologue" << endl;
	cout << "    Finished to page 24" << endl;
	cout << "11-21-2012" << endl;
	cout << "    Worked some on the prologue" << endl;
	cout << "    Finished to page 25" << endl;
	cout << "    Worked on combining the book into a single file with a menu instead of" << endl;
	cout << "running a batch file and separate files for the book" << endl;
	cout << "" << endl;
	system("pause");
	system ("cls");
	cout << "The Princess    -     Progress (cont.)\n" << endl;
	cout << "11-24-2012" << endl;
	cout << "    Worked on the menus" << endl;
	cout << "    Worked some more on the prologue" << endl;
	cout << "    Finished to page 32" << endl;
	cout << "11-26-2012" << endl;
	cout << "    Worked more on the Prologue" << endl;
	cout << "    Finished the Menus" << endl;
	cout << "12-12-2012" << endl;
	cout << "    Worked on the prologue some more" << endl;
	cout << "    Finished to Page 35" << endl;
	cout << "    Fixed some errors in the program" << endl;
	cout << "12-16-2012" << endl;
	cout << "    Worked on the prologue" << endl;
	cout << "    Tidied up some of the code" << endl;
	cout << "12-26-2012" << endl;
	cout << "    Worked on the prologue more" << endl;
	cout << "01-29-2013" << endl;
	cout << "    Finished the prologue" << endl;
	cout << "    Worked on Chapter 1" << endl;
	cout << "    Finished up to page 46" << endl;
	cout << "04-03-2013" << endl;
	cout << "    Worked some on chapter 1" << endl;
	system("pause");
	system ("cls");
	cout << "The Princess    -     Progress (cont.)\n" << endl;
	cout << "    Finished up to page 52" << endl;
	cout << "04-16-2013" << endl;
	cout << "    Put in the progress part, but commented it out for the time being" << endl;
	cout << "    Worked on Chapter 1 some more" << endl;
	cout << "07-16-2013" << endl;
	cout << "    Finished up Chapter 1" << endl;
	cout << "    Started work on Chapter 2" << endl;
	cout << "07-17-2013" << endl;
	cout << "    Worked on Chapter 2" << endl;
	cout << "    Finished up to page 62" << endl;
	cout << "07-25-2013" << endl;
	cout << "    Finished Chapter 2" << endl;
	cout << "    Finished Chapter 3" << endl;
	cout << "    Worked on Chapter 4" << endl;
	cout << "    Finished up to page 78" << endl;
	cout << "    Fixed a few things with the coming chapters" << endl;
	cout << "    Fixed the coming soon information" << endl;
	cout << "    Fixed a date in the Progress section that was showing the wrong year" << endl;
	cout << "07-26-2013" << endl;
	cout << "    Worked on Chapter 4" << endl;
	cout << "    Finished up to page 79" << endl;
	cout << "    Did some reformatting for the Progress section" << endl;
	system("pause");
	system ("cls");
	cout << "The Princess    -     Progress (cont.)\n" << endl;
	cout << "07-27-2013" << endl;
	cout << "    Finished Chapter 4" << endl;
	cout << "    Worked on Chapter 5" << endl;
	cout << "    Finished up to page 85" << endl;
	cout << "08-07-2013" << endl;
	cout << "    Worked some more on Chapter 5" << endl;
	cout << "    Finished up to page 87" << endl;
	cout << "08-18-2013" << endl;
	cout << "    Worked on Chapter 5" << endl;
	cout << "    Finished pp to page 95" << endl;
	cout << "08-22-2013" << endl;
	cout << "    Worked more on Chapter 5" << endl;
	cout << "    Finished to page 96" << endl;
	cout << "09-08-2013" << endl;
	cout << "    Finished Chapter 5" << endl;
	cout << "    Started Chapter 6" << endl;
	cout << "    Finished up to page 97" << endl;
	cout << "09-10-2013" << endl;
	cout << "    Finished Chapter 6" << endl;
	cout << "    Worked on Chapter 7" << endl;
	cout << "    Reformatted this progress list" << endl;
	cout << "10-02-2013" << endl;
	system("pause");
	system ("cls");
	cout << "The Princess    -     Progress (cont.)\n" << endl;
	cout << "    Worked more on Chapter 7" << endl;
	cout << "    Finished to Page 101" << endl;
	cout << "10-03-2013" << endl;
	cout << "    Worked more on Chapter 7" << endl;
	cout << "    Finished to page 103" << endl;
	cout << "10-04-2013" << endl;
	cout << "    Worked more on Chapter 7" << endl;
	cout << "    Finished to page 106" << endl;
	cout << "10-06-2013" << endl;
	cout << "    Worked more on Chapter 7" << endl;
	cout << "    Finished to page 107" << endl;
	cout << "10-08-2013" << endl;
	cout << "    Did a bit of reformatting in the code; nothing noticeable to the end-user" << endl;
	cout << "    Reformatted a bit of the text; some minor changes there" << endl;
	cout << "    Finished Chapter 7" << endl;
	cout << "    Started Chapter 8" << endl;
	cout << "    Finished to page 112" << endl;
	cout << "10-09-2013" << endl;
	cout << "    Finished Chapter 8" << endl;
	cout << "    Started Chapter 9" << endl;
	cout << "    Finished to Page 118" << endl;
	cout << "10-27-2013" << endl;
	system("pause");
	system ("cls");
	cout << "The Princess    -     Progress (cont.)\n" << endl;
	cout << "    Finished Chapter 9" << endl;
	cout << "    Started Chapter 10" << endl;
	cout << "    Finished up to page 122" << endl;
	cout << "10-28-2013" << endl;
	cout << "    Finished Chapter 10" << endl;
	cout << "11-07-2013" << endl;
	cout << "    Finished Chapter 11" << endl;
	cout << "11-09-2013" << endl;
	cout << "    Finished Chapter 12" << endl;
	cout << "    Changed the Coming Soon area; added in the details" << endl;
	cout << "12-26-2013" << endl;
	cout << "    Changed the program icon" << endl;
	cout << "    Removed the descriptions in the Coming Soon/Coming Later section" << endl;
	cout << "01-12-2014" << endl;
	cout << "    Started Chapter 13" << endl;
	cout << "02-07-2014" << endl;
	cout << "    Finished Chapter 13" << endl;
	cout << "    Started Chapter 14" << endl;
	cout << "02-28-2014" << endl;
	cout << "    Worked on Chapter 14" << endl;
	cout << "    Finished up to Page 134" << endl;
	cout << "03-30-2014" << endl;
	system("pause");
	system ("cls");
	cout << "The Princess    -     Progress (cont.)\n" << endl;
	cout << "    Worked more on Chapter 14" << endl;
	cout << "    Finished up to page 139" << endl;
	cout << "    Fixed some spelling and grammar errors" << endl;
	cout << "04-11-2014" << endl;
	cout << "    Worked some on Chapter 14" << endl;
	cout << "    Finished to Page 141" << endl;
	cout << "    Reformatted the Progress section; now it is no longer in reverse order" << endl;
	cout << "04-21-2014" << endl;
	cout << "    Worked more on Chapter 14" << endl;
	cout << "    Finished to Page 144" << endl;
	cout << "04-22-2014" << endl;
	cout << "    Fixed Chapter 14 a bit - found there was a line skiped and corrected it" << endl;
	cout << "    Finished Chapter 14" << endl;
	cout << "    Started Chapter 15" << endl;
	cout << "    Finished to page 147" << endl;
	cout << "05-15-2014" << endl;
	cout << "    Continued with Chapter 15" << endl;
	cout << "    Finished to Page 148" << endl;
	cout << "05-20-2014" << endl;
	cout << "    Continued work on Chapter 15" << endl;
	cout << "    Finished to Page 148" << endl;
	cout << "05-30-2014" << endl;
	system("pause");
	system ("cls");
	cout << "The Princess    -     Progress (cont.)\n" << endl;
	cout << "    Worked on Chapter 15" << endl;
	cout << "    Finished to Page 151" << endl;
	cout << "06-13-2014" << endl;
	cout << "    Worked more on Chapter 15" << endl;
	cout << "06-23-2014" << endl;
	cout << "    Started splitting up the code to help with reading it" << endl;
	cout << "06-24-2014" << endl;
	cout << "    Continued splitting up the code" << endl;
	cout << "    Finished splitting up the code" << endl;
	cout << "    Continued work on Chapter 15" << endl;
	cout << "    Finished to page 157" << endl;
	cout << "06-25-2014" << endl;
	cout << "    Continued work on Chapter 15" << endl;
	cout << "    Finished to page 160" << endl;
	cout << "06-26-2014" << endl;
	cout << "    Finished Chapter 15" << endl;
	cout << "07-09-2014" << endl;
	cout << "    Finished Chapter 16" << endl;
	cout << "07-14-2014" << endl;
	cout << "    Updated the Coming Soon section" << endl;
	cout << "07-19-2014" << endl;
	cout << "    Started Chapter 17" << endl;
	system("pause");
	system ("cls");
	cout << "The Princess    -     Progress (cont.)\n" << endl;
	cout << "    Finished Chapter 17" << endl;
	cout << "    Started Chapter 18" << endl;
	cout << "    Finished to Page 171" << endl;
	cout << "08-20-2014" << endl;
	cout << "    Continued Work on Chapter 18" << endl;
	cout << "    Got to the end of the Chapter on Page 171" << endl;
	cout << "    DevC++ was giving compile problems, so I switched to MSVS Express 2013" << endl;
	cout << "    Started Chapter 19" << endl;
	cout << "08-24-2014" << endl;
	cout << "    Continued on Chapter 19" << endl;
	cout << "    Finished to Page 173" << endl;
	cout << "08-26-2014" << endl;
	cout << "    Continued work on Chapter 19" << endl;
	cout << "    Finished to Page 175" << endl;
	cout << "08-31-2014" << endl;
	cout << "    Continued work on Chapter 19" << endl;
	cout << "    Finished Chapter 19" << endl;
	cout << "09-03-2014" << endl;
	cout << "    Removed the Coming Soon section, as it is obsolete." << endl;
	cout << "09-04-2014" << endl;
	cout << "    Started on Chapter 20" << endl;
	cout << "    Finished to page 178" << endl;
	system("pause");
	system ("cls");
	cout << "The Princess    -     Progress (cont.)\n" << endl;
	cout << "09-05-2014" << endl;
	cout << "    Continued work on Chapter 20" << endl;
	cout << "    Finished to Page 180" << endl;
	cout << "09-12-2014" << endl;
	cout << "    Replaced the 'Press any key' wait period in the into a timed wait period of" << endl;
	cout << "15 seconds" << endl;
	cout << "09-28-2014" << endl;
	cout << "    Worked more on finishing Chapter 20 - finished to page 182" << endl;
	cout << "    Changed the About page a little - nothing major there" << endl;
	cout << "10-23-2014" << endl;
	cout << "    Finished Chapter 20." << endl;
	cout << "    Made final recompilation\n\n\n\n\n\n\n\n\n\n" << endl;
	system("pause");
	menu();
}
